src/executor/externals.rs, src/header.rs, src/header/babe.rs, src/header/grandpa.rs, src/trie.rs, src/trie/node_value.rs, src/util.rs, src/verify/execute_block.rs
Removes most usage of `parity_scale_codec::Compact`.
This saves allocating `Vec`s all the time, and also avoids having to convert `usize`s to `u64`s all the time.
=> Add custom SCALE-compact encoding

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, bin/full-node/main.rs, bin/json-rpc-test/main.rs, src/executor/vm.rs, src/json_rpc/websocket_server.rs, src/lib.rs, src/network/with_buffers.rs
cc #106 
I reviewed every single dependency to check whether it's `no_std` compatible, and added remarks if not.
=> Rename `os-networking` feature to `std` and move dependencies around

bin/full-node/main.rs, bin/full-node/network_service.rs
This should fix Kusama and Westend. I haven't tested it because the chain specs fail to parse at the moment.
=> Use the correct protocol ID for block requests

src/executor/vm/jit.rs
The entire code under the `vm` module should be re-reviewed and partially rewritten.
In the meanwhile, here's a quickfix to make Kusama sync.
=> Quickfix for Kusama syncing malfunction

src/executor/vm/jit.rs
Some very unscientific testing has shown that passing `Speed` here speeds up sync speed by around 25%.
While the percentage is probably not exact, it's clear that there *is* a good speedup.
=> Pass configuration options to wasmtime

bin/full-node/network_service.rs, src/network/connection/established.rs
I have no idea how to design this. The current system with `TProtosList` and `TProto` generics is quite bad.
This PR replaces this with good old `Vec`s and `String`s, in order to be able to continue.
=> Use strings and vecs for network protocols

bin/full-node/main.rs, bin/full-node/network_service.rs
The sync stalling is simply because I forgot a couple of `await`s.
Ignoring warnings has once again bitten me in the arse.
=> Fix disconnects not being detected by network service

src/executor/externals.rs
`ed25519_dalek::PublicKey::from_bytes` can legitimately return an error, as not all combinations of bytes are valid public keys.
=> Fix panic in ext_crypto_ed25519_verify_version_1

src/executor/vm/jit.rs
Reading https://docs.rs/wasmtime/0.21.0/wasmtime/struct.Store.html:
> A Store is not intended to be a long-lived object in a program. No form of GC is implemented at this time so once an instance is created within a Store it will not be deallocated until all references to the Store have gone away (this includes all references to items in the store). This makes Store unsuitable for creating an unbounded number of instances in it because Store will never release this memory. It's instead recommended to have a long-lived Engine and instead create a Store for a more scoped portion of your application.
=> Fix memory leak with wasmtime

bin/wasm-node/javascript/package.json
It's already published. This PR bumps the version.
=> Publish substrate-lite 0.1.2 on npm

bin/wasm-node/rust/src/sync_service.rs
It was assuming a verification speed of 1k blocks/sec. This is true for the full node, but the light client can go faster than that.
=> Bump the size of the browser light client import queue size

src/chain/blocks_tree.rs, src/chain/chain_information.rs, src/chain_spec.rs, src/database/finalized_serialize/defs.rs, src/database/full_sled.rs, src/database/full_sled/open.rs, src/finality/justification/decode.rs
cc #221 
Changes `ChainInformation` and extracts all the Grandpa field to an enum `ChainInformationFinality`. This enum contains only one variant at the moment `Grandpa`, but the idea is to add a new `RelayChain`/`Manual` variant later.
Some notes:
- The format of justifications doesn't contain any indication about which engine they refer to, and therefore we have to deduce it based on the finality engine of the chain. If we add a `Manual` variant, `verify_justification` would always return an error.
- `NonFinalizedTree::set_finalized_block` would work just fine. All this method does regarding Grandpa is go through the headers of the finalized blocks and update the state of Grandpa. If there's no Grandpa, there's just no state update.
- The Grandpa-related database fields are still …
=> Allow for different finality engines

src/chain/blocks_tree.rs, src/chain/chain_information.rs, src/database/full_sled/open.rs, src/verify/header_body.rs, src/verify/header_only.rs
cc #221 
With `AllAuthorized`, any node has the permission to submit a block at any time. :cowboy_hat_face: 
Intended to be used for parachains, at least until Cumulus supports Aura/Babe.
=> Add an AllAuthorized consensus engine

src/database/full_sled.rs
If no Aura/Babe field is found, reporting as `AllAuthorized` instead of returning an error.
=> Fix database reporting as corrupted with AllAuthorized consensus

bin/full-node/main.rs, bin/tick_v1.json, src/chain_spec.rs, src/informant.rs
cc #221 
When some chain specs contain a parachain name, we try to load `<parachain>.json` in the same directory. This is kind of hacky, but I don't know of any better solution nor if the chain specs format will change in the future.
This PR makes us load the relay chain specs, start a sync service for the relay chain, and show it in the informant.
The syncing of the relay chain doesn't work yet because the network doesn't support multiple chains at a time.
=> Update the full node code and informant for parachains

Cargo.lock, bin/wasm-node/rust/Cargo.toml, bin/wasm-node/rust/src/lib.rs, bin/wasm-node/rust/src/sync_service.rs
The sync service now reports every single block to the outside.
The JSON-RPC storage queries are now handled by asking for storage proofs from other nodes.
=> Tweak storage queries for light-browser client

bin/full-node/src/network_service.rs, src/network/service.rs
In the case of `tick`+`rococo`, for instance, we would only discover tick's nodes and not rococo's.
=> Properly start one discovery task per chain

src/network/connection/established.rs
I realized right after #310 and shutting down my computer that we didn't send the length of the notification as we should.
=> Fix notification length prefix not being sent

bin/wasm-node/rust/src/network_service.rs
Follow-up to https://github.com/paritytech/substrate-lite/pull/304
=> Restore block announces propagation on Wasm

src/network/protocol.rs
Err, I didn't realize that https://github.com/paritytech/substrate-lite/pull/293 broke the justifications download.
=> Fix justifications not being downloaded

bin/wasm-node/javascript/index.js, bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/ffi/bindings.rs
This was laziness from my side to pass 1 millisecond for the delay, even when want "immediate".
=> Fix spurious 1ms delay in JS node

bin/full-node/src/main.rs
`stream::unfold` doesn't actually yield the initial seed, meaning that these two timers were starting respectively one and five seconds later than they're supposed to start.
=> Start the timers as soon as possible

src/chain/blocks_tree/verify.rs, src/chain/sync/optimistic.rs, src/executor/host.rs, src/executor/runtime_host.rs, src/verify/header_body.rs
Fix #320 
In case of runtime upgrade, the block verification code now also compiles the new runtime.
Also relates to #144
=> Block verification now also verifies new runtime

bin/wasm-node/javascript/demo.js
We truncate log messages to 100 characters. This can be confusing. As such, add `…` at the end of truncated messages.
=> Add ellipsis in demo when message is too long

bin/wasm-node/javascript/.gitignore, bin/wasm-node/javascript/demo.js, bin/wasm-node/javascript/index.js, bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/ffi/bindings.rs, bin/wasm-node/rust/src/lib.rs, bin/wasm-node/rust/src/sync_service.rs
The demo will now save the state of the finalized chain every 15 seconds in `substrate-lite-demo-db.json`, and load it back on start-up.
The title of the PR says "restore", because this used to work a long time ago, and I broke it (intentionally) when removing the dependency on `wasm-bindgen`.
=> Restore the database system of the Wasm node

Cargo.lock, Cargo.toml, bin/full-node/src/network_service.rs, bin/wasm-node/rust/src/network_service.rs, src/libp2p.rs, src/network/service.rs, src/util.rs
Replaces the manual `Context` usage with a `futures::oneshot::channel()`.
This is not the most optimal way to implement this future, but right now I'm trying to reduce the complexity of `libp2p.rs` until a proper design is found.
cc #288
=> Improve API of the thread-safe read_write functions

Cargo.lock, Cargo.toml, bin/wasm-node/javascript/demo.js, bin/wasm-node/javascript/index.js, bin/wasm-node/rust/Cargo.toml, bin/wasm-node/rust/src/lib.rs, bin/wasm-node/rust/src/network_service.rs, bin/wasm-node/rust/src/sync_service.rs, src/informant.rs
This adds a lot of logging to the code of the Wasm node, which should hopefully make it easier to figure out where issues come from.
I've also fixed `index.js` to properly buffer the stdout/stderr output and split them by `\n`. This removes a lot of extra accidental new lines.
Relates to #384
=> Add logging to the Wasm node

bin/wasm-node/rust/src/lib.rs, src/json_rpc/methods.rs
After this PR:
> {"jsonrpc":"2.0","method":"state_runtimeVersion","params":{"subscription":"0","result":{"specName":"westend","implName":"parity-westend","authoringVersion":2,"specVersion":47,"implVersion":0,"transactionVersion":3,"apis":[["0xdf6acb689907609b",3],["0x37e397fc7c91f5e4",1],["0x40fe3ad401f8959a",4],["0xd2bc9897eed08f15",2],["0xf78b278be53f454c",2],["0xaf2c0297a23e6d3d",1],["0xed99c5acb25eedf5",2],["0xcbca25e39f142387",2],["0x687ad44ad37f03c2",1],["0xab3c0572291feb8b",1],["0xbc9d89904f5b923f",1],["0x37c8bb1350a9a2a8",1]]}}}
Comparing with official Westend node:
> {"jsonrpc":"2.0","method":"state_runtimeVersion","params":{"result":{"apis":[["0xdf6acb689907609b",3],["0x37e397fc7c91f5e4",1],["0x40fe3ad401f8959a",4],["0xd2bc9897eed08f15",2],["0xf78b278be53f454c",2],["0xaf2c0297a23 …
=> Fix RuntimeVersion not sent back correctly

.github/mergify.yml, .github/workflows/ci.yml, .github/workflows/deploy.yml
I've added a new `automerge` label. When applied to a pull request, it should now, thanks to Mergify, automatically merge the pull request as soon as CI passes, essentially like bors does. The main point is of course to enforce a linear history.
=> Plug Mergify

bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/json_rpc_service.rs, bin/wasm-node/rust/src/lib.rs
Instead of using `spawn_task` multiple times, and thus calling `setTimeout` a multitude of times, this groups all tasks into one future, which should lead to a better utilization of the browser's resources.
=> Group everything in one task in the wasm-node

Cargo.lock, bin/wasm-node/javascript/demo.js, bin/wasm-node/javascript/index.js, bin/wasm-node/rust/Cargo.toml, bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/ffi/bindings.rs, bin/wasm-node/rust/src/lib.rs
Adds a `max_log_level` parameter to the configuration, configuring the logs verbosity.
Pass 0 to disable all logging. 1 = Error, 2 = Warn, 3 = Info, 4 = Debug, 5+ = Trace
Additionally, logs are now reported through a new ffi function called `log` that gets passed the level, target, and message. This allows additional filtering from the JS side, if needed.
Relates to https://github.com/paritytech/smoldot/issues/384
=> Make maximum log level configuration from JS

bin/wasm-node/rust/src/json_rpc_service.rs, src/executor.rs, src/executor/read_only_runtime_host.rs, src/executor/runtime_host.rs, src/json_rpc/methods.rs
Right now, querying the runtime version does a storage query on the network. If the storage query fails, we simply panic.
The correct way to do is to maintain a version of the runtime of the best block.
Since it's not trivial to do that, let's add another quick hack and fall back to returning the genesis runtime specs.
Also improves the decoding of the runtime specs to handle the potentially missing `transaction_version` field.
=> Don't panic if runtime version is asked when we have no peers and fix core version decoding

src/libp2p.rs, src/libp2p/peerset.rs
Two bugs fixed:
- `remove_pending_substream` would remove the substream even if it returns an error.
- Fixed using `remove_pending_substream` instead of `remove_substream` after a `NotificationsOutReset`.
=> Fix NotificationsOutReset panicking in libp2p module

bin/wasm-node/rust/src/json_rpc_service.rs, src/json_rpc/methods.rs
Adds two RPC method definitions, one of them hardcoded and the other one erroring.
This way, the node no longer crashes just by clicking on the "Transfer" button of PolkadotJS.
=> Don't panic when making a transfer with PolkadotJS

bin/wasm-node/rust/src/json_rpc_service.rs
- Turns `JsonRpcService` into an `Arc`-friendly struct.
- Spawns a separate task for each incoming request.
- Subscriptions now directly use the sync_service without going through a JSON-RPC task.
- Storage subscriptions are now properly implemented by downloading the value of the storage entry at each block notification.
=> Properly implement storage subscriptions

bin/wasm-node/rust/src/json_rpc_service.rs
Turns the two function into methods of `JsonRpcService` that take `&self`.
Most of the diff is the change in the indentation.
=> Improve general style of json-rpc-service by using `self`

bin/wasm-node/rust/src/json_rpc_service.rs, bin/wasm-node/rust/src/network_service.rs
Close #455 
The strategy is as follows:
- At initialization, we get the runtime code of the genesis block and extract the metadata and runtime specs.
- At every new best block, we download the runtime code and compare it with the previous one. If it has changed, recompile the runtime and extract metadata and runtime specs.
- The JSON-RPC functions that retreieve the metadata and runtime spec simply get the latest known version.
- If an error happens when compiling a new runtime, we update this latest known runtime with the information that the runtime is invalid. The JSON-RPC functions to query it will now return errors.
- There is a minimum of 3.5 seconds between two queries for the runtime on the network, to avoid spamming too much. If two or more new best blocks happen within 0.5 …
=> Properly implement runtime subscription

src/chain/chain_information/babe_fetch_epoch.rs, src/chain/sync/grandpa_warp_sync.rs
Closes #449. Fixes the structure of `DecodableBabeEpochInformation` and passes in a chain spec to `GrandpaWarpSync` in order to get the babe genesis configuration.
=> Fix `babe_fetch_epoch`

bin/wasm-node/javascript/index.js
- Introduce a subtype of error.  
- It's best practice not to throw strings. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling#exception_handling_statements
- In V8 subtypes of Error implicitly call the V8 specific Error.captureStacktrace which gives better context on the Error which is understood by the devtools.
=> Throw proper JavaScript errors

bin/wasm-node/rust/src/json_rpc_service.rs
Improves the readability of the JSON-RPC service by moving the biggest methods separately.
Doesn't change any of the logic, just moves code.
=> Move voluminous methods to separate functions

bin/wasm-node/javascript/index.d.ts, bin/wasm-node/javascript/index.test-d.ts, bin/wasm-node/javascript/package-lock.json, bin/wasm-node/javascript/package.json, bin/wasm-node/javascript/tsconfig.json
This typings file means people using the smoldot client from typescript get the type information without having to write their own definitions.  The trade-off is that any future changes to the JavaScript API should now be accompanied with a corresponding update to the typings file.
I have tested by npm linking my local clone of smoldot to my clone of substrate-connect and removing the typings I created there.  It compiled fine and passed all the tests.
=> Add typescript typings for javascript package

Cargo.lock, Cargo.toml, src/executor/vm/interpreter.rs
Integrates https://github.com/paritytech/wasmi/pull/246
This switches a dependency from crates.io to git, but I don't think it'd be a problem to ask for a new version if we want to publish smoldot.
=> Remove memory copies when reading Wasmi memory

bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/json_rpc_service.rs, bin/wasm-node/rust/src/lib.rs, bin/wasm-node/rust/src/network_service.rs, bin/wasm-node/rust/src/sync_service.rs
Changes can be summarized by three things:
- Changes the network service to allow connecting to multiple chains at the same time.
- The JSON-RPC service and sync service now have an extra "chain index" being passed in order to identify which chain to use when it interacts with the network service.
- The lib.rs file now accepts multiple chains and will spawn the sync service multiple times.
This lays down some foundation for later work.
=> Allow passing multiple chains to start

bin/wasm-node/javascript/index.d.ts, bin/wasm-node/javascript/index.js, bin/wasm-node/javascript/index.test-d.ts, bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/ffi/bindings.rs
cc @raoulmillais 
I've added a new `relay_chain_spec` field.
For example, if you want to connect to Tick, you need to pass the Tick chain specs in the `chain_spec` field, and the Rococo chain spec in the `relay_chain_spec` field.
At the moment smoldot isn't capable of understanding the relationship between Tick and Rococo and just treats them as two individual chains. But eventually, you'll get an error if the content of `relay_chain_spec` doesn't match the relay chain expected by `chain_spec` or if `relay_chain_spec` is empty and `chain_spec` is a parachain.
I went for adding a new `relay_chain_spec` field so that `database_content` and the JSON-RPC calls still always refer to the the chain passed through `chain_spec`. In the long term this will change again with #501.
=> Allow passing a relay chain spec from the JS side

src/chain/sync/grandpa_warp_sync.rs
There was some misunderstanding in my review of the Grandpa warp sync PR.
The Grandpa warp sync state machine should contain a list of sources. The `TSrc` parameter, however, shouldn't be used as an identifier for a source, but rather as some "extra data" that the user can associate to each source in the list. Instead, an identifier for a source is now a `SourceId` attributed by the GP warp sync state machine itself.
The list of sources is stored in a `Slab` instead of a `Vec`, so that indices don't change even if you remove a source.
While the current code works, this change would be appreciated in order to integrate it with the "all syncing" system.
The "all syncing" system is going to use the `TSrc` object to store for example the best block of the source, which is an information …
=> Change the source system of GP warp sync

src/chain/sync/all.rs, src/chain/sync/grandpa_warp_sync.rs
- Should I remove these functions from the respective variants? So that there's only the `source_user_data_mut` function implemented on `InProgressGrandpaWarpSync` and not `StorageGet` etc..
- Any other functions that I should add?
=> Add `source_user_data_mut` and `as_chain_information` to `InProgressGrandpaWarpSync`

Cargo.toml, src/author/runtime.rs, src/chain/chain_information.rs, src/chain/sync/all_forks.rs, src/chain/sync/all_forks/pending_blocks.rs, src/chain/sync/all_forks/sources.rs, src/chain/sync/grandpa_warp_sync.rs, src/chain/sync/optimistic.rs, src/chain_spec.rs, src/chain_spec/light_sync_state.rs, src/chain_spec/structs.rs, src/database/finalized_serialize.rs, src/executor/read_only_runtime_host.rs, src/executor/runtime_host.rs, src/executor/vm.rs, src/executor/vm/interpreter.rs, src/finality/grandpa/chain_config.rs, src/finality/grandpa/warp_sync.rs, src/finality/justification/decode.rs, src/json_rpc/methods.rs, src/lib.rs, src/libp2p.rs, src/libp2p/connection/established.rs, src/libp2p/connection/handshake.rs, src/metadata/query.rs, src/network/protocol/identify.rs, src/network/service.rs, src/trie/trie_structure.rs
cc #106 
Adds `#![no_std]` in `lib.rs` and fixes the resulting compilation errors.
=> Enable #![no_std]

bin/full-node/src/sync_service.rs, bin/wasm-node/rust/src/sync_service.rs, src/chain/sync/all.rs, src/chain/sync/optimistic.rs, src/executor/host.rs
Before: the optimistic sync queries for `:code` and `:heappages` from the API user, then internally compiles the runtime. In case of a runtime upgrade, we demand these values again from the user at the next block.
After: the optimistic sync must be passed the finalized block runtime at initialization. In case of a runtime upgrade, the new runtime overrides the old one.
This is possible thanks to https://github.com/paritytech/smoldot/pull/347
=> Change the way the optimistic syncing handles the runtime

bin/wasm-node/rust/src/json_rpc_service.rs, bin/wasm-node/rust/src/network_service.rs, bin/wasm-node/rust/src/sync_service.rs, src/trie.rs, src/trie/nibble.rs, src/trie/prefix_proof.rs, src/trie/proof_verify.rs
Fix #523 
I've implemented the verification part of the code, but remains the do the actual querying.
=> Allow querying all keys with a prefix through storage queries

bin/wasm-node/rust/src/runtime_service.rs, src/author/runtime.rs, src/chain/blocks_tree/verify.rs, src/chain/chain_information/aura_config.rs, src/chain/chain_information/babe_config.rs, src/chain/chain_information/babe_fetch_epoch.rs, src/executor/host.rs, src/executor/read_only_runtime_host.rs, src/executor/runtime_host.rs, src/executor/vm.rs, src/executor/vm/interpreter.rs, src/executor/vm/jit.rs, src/finality/grandpa/chain_config.rs, src/metadata/query.rs, src/sync/optimistic.rs, src/verify/execute_block.rs, src/verify/header_body.rs
Fix #597 
It turns out that I need this for parachains syncing (cc #221), because storage proofs can reasonably fail, in which case we need to interrupt the execution but keep the compiled runtime.
=> Properly return the prototype in case of error

src/header.rs, src/header/babe.rs
Happens when syncing Rococo.
Reference: https://github.com/paritytech/substrate/blob/93b231e79f5b4e551c34234e89fa4a2e5e9c1510/primitives/consensus/babe/src/digests.rs#L140-L141
=> Fix bad decoding/encoding of Babe next config digest

src/database/full_sled.rs, src/metadata/decode.rs, src/sync/para.rs, src/util.rs
The return value of the runtime call is in fact an `Option`, not just a plain struct.
cc #221
=> Fix persisted validation data decoding and tweak nom_option_decode

bin/wasm-node/rust/src/lib.rs, bin/wasm-node/rust/src/lossy_channel.rs, bin/wasm-node/rust/src/runtime_service.rs, bin/wasm-node/rust/src/sync_service.rs
More changes needed for parachains (cc #221)
- Makes `lossy_channel` accessible from the `runtime_service`.
- Use a `lossy_channel` for the runtime service subscriptions, similar to the sync service. This fixes a potential deadlock.
- Add `runtime_service::subscribe_best`. See function documentation for details.
=> Add runtime_service::subscribe_best

bin/wasm-node/rust/src/runtime_service.rs, src/chain/chain_information/babe_fetch_epoch.rs, src/executor/read_only_runtime_host.rs, src/metadata/query.rs, src/sync/grandpa_warp_sync.rs
cc #221 #301
Allows obtaining the storage trie root from within the runtime during a read-only call.
Adds a `RuntimeHostVm::StorageRoot` variant that requires passing the state trie root in order to resume execution.
I've had to turn `GrandpaWarpSync::from_babe_fetch_epoch_query` into a loop in order to allow resuming execution instantly.
=> Allow getting storage root in read-only runtime call

bin/wasm-node/rust/src/runtime_service.rs
Fixes the few mistakes that revealed that the runtime service was forked off the JSON-RPC service.
=> Remove traces of JSON-RPC from runtime service module

bin/wasm-node/rust/src/network_service.rs
If we have less than `NUM_ATTEMPTS` peers, then the number of errors will not be equal to `NUM_ATTEMPTS`.
=> Remove some bad networking debug_assert!s

bin/wasm-node/javascript/package.json
Broken after https://github.com/paritytech/smoldot/pull/645
Don't ask me why no warning is printed when this is wrong.
=> Fix broken browser override

bin/wasm-node/javascript/src/index.d.ts, bin/wasm-node/javascript/src/index.js, bin/wasm-node/javascript/src/index.test-d.ts
Call this in order to destroy the smoldot client.
=> Add a terminate() function to the Wasm client

src/chain/chain_information/babe_fetch_epoch.rs, src/sync/grandpa_warp_sync.rs
This is a prerequisite for https://github.com/paritytech/smoldot/issues/653.
=> `babe_fetch_epoch` returns a prototype in the `Finished(Err(_))` variant as well.

bin/wasm-node/javascript/src/bindings-smoldot-js.js, bin/wasm-node/javascript/src/bindings-wasi.js, bin/wasm-node/javascript/src/compat-browser.js, bin/wasm-node/javascript/src/compat-nodejs.js, bin/wasm-node/javascript/src/index.js, bin/wasm-node/javascript/src/worker.js, bin/wasm-node/rust/src/ffi.rs
Close #644 
Once smoldot has panicked, it is important to not call any of its functions ever again, as the state of the memory might be corrupted. See [this comment](https://github.com/paritytech/smoldot/blob/547ede25683f6c621e0fdaa87489cb94c62e3ca2/bin/wasm-node/rust/src/ffi/bindings.rs#L51).
For this reason, there currently exists a complicated system that detects throwing and prevents any further call.
Now that we use a `Worker`, we can use a much easier strategy: simply make the worker throw whenever a panic happens. This instantly terminates the worker.
The error is then detected by the code outside the worker and can be reported on the API level.
=> Clean up error handling in Wasm node

bin/wasm-node/javascript/src/index.d.ts, bin/wasm-node/javascript/src/index.js, bin/wasm-node/javascript/src/index.test-d.ts, bin/wasm-node/javascript/src/worker.js, bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/ffi/bindings.rs
cc #221 
Before this PR, you're expected to pass a parachain spec (simply called `chain_spec`), relay chain spec, and database.
There's a problem with that: the database shouldn't apply to the parachain but to the relay chain.
This PR renames the `relay_chain_spec` field to `parachain_spec`.
If you passed for example `{ chain_spec: tick, relay_chain_spec: rococo }` you now have to pass `{ chain_spec: rococo, parachain: tick }`.
This makes the database apply to the relay chain, as intended.
=> Change relay_chain_spec field to parachain_spec

bin/wasm-node/javascript/src/bindings-smoldot-js.js, bin/wasm-node/javascript/src/bindings-wasi.js, bin/wasm-node/javascript/src/index.js, bin/wasm-node/javascript/src/worker.js
Replaces a lot of `let` with `const`, and uses camelCase instead of snake_case.
One exception is the configuration passed to `start`, as this would be a breaking change.
=> Make JS code a bit more idiomatic

bin/wasm-node/rust/src/sync_service.rs
Rob confirmed that it was correct :raised_hands:
=> Remove TODO when calling `ParachainHost_persisted_validation_data`

bin/wasm-node/javascript/package-lock.json, bin/wasm-node/javascript/package.json, bin/wasm-node/javascript/src/index.test-d.ts
- Removes unneeded tsd library - dtslint bundles its assertions
- Add explicit test for return type of the package
- Add explicit test that terminate() returns void
- No need to fully qualify type names
=> Improve typescript typings test coverage

src/database/full_sqlite/open.rs
`sled` would normally do that, but since we've switched to `sqlite` it has to be done manually.
=> Use fs::create_dir_all before opening DB

.gitignore, bin/wasm-node/javascript/src/bindings-smoldot-js.js, bin/wasm-node/javascript/src/bindings-wasi.js
Alter imports of 'randombytes' and 'performance-now' packages that was causing the 'is not a function' issue when importing smoldot. 
Fixes #703
=> Alter imports of 'randombytes' and 'performance-now' packages 

src/network/protocol/grandpa_warp_sync.rs, src/sync/grandpa_warp_sync.rs
By removing this backwards compatibility hack, we filter out old nodes that don't include the latest changes in Substrate.
=> Remove backwards-compatibility hack with is_finished

bin/wasm-node/javascript/src/bindings-wasi.js
Fixes a mistake introduced in #674
=> Fix println! no longer working in wasm-node

src/network/protocol/grandpa.rs
Use unsigned pre-commits in compact commit message (see [grandpa crate](https://github.com/paritytech/finality-grandpa/blob/master/src/lib.rs#L318)) and add authority set id to CatchUp message (see [substrate](https://github.com/paritytech/substrate/blob/master/client/finality-grandpa/src/communication/gossip.rs#L398)).
=> Fix GRANDPA commit and catchup message

bin/wasm-node/rust/src/network_service.rs, src/finality/grandpa/warp_sync.rs, src/network/protocol/grandpa_warp_sync.rs
Three changes:
- Better logging of warp sync responses.
- In the `ChainInformation` produced by GrandPa warp sync, we were fetching the authorities from the last header. However, since the latest changes in Substrate, the last header is no longer necessarily a new session. We now properly use `self.authorities_list`.
- Use `nom::all_consuming` to parse the protocol message. Older Substrate nodes don't include the `is_finished` boolean, but because we weren't using `all_consuming`, smoldot was misinterpreting the first byte of the next fragment as being a boolean, and the data behind as not part of the response.
=> Some bugfixes and tweaks to GrandPa warp sync

bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/json_rpc_service.rs
- Send `rpc.as_bytes().len()` instead of `rpc.len()`. It doesn't actually make a difference, because `len()` returns the length in bytes of the string, but it makes it explicitly correct.
- Don't send back `"null"` but properly wrap it in a response. This is an actual bugfix.
=> Fix "null" being sent back as a JSON-RPC response

bin/wasm-node/rust/src/json_rpc_service.rs, src/json_rpc/methods.rs
Properly handles situations where the incoming JSON-RPC request doesn't match what we expect.
=> Clean up erroneous JSON-RPC request handling

src/libp2p/connection/established.rs, src/network/service.rs
See https://github.com/paritytech/substrate/pull/8578
Should be reverted after the Substrate PR has been merged and deployed.
=> Increase allowed warp sync size to 128MiB

src/util/leb128.rs
Right now, if the maximum allowed size of a response is 128MiB (which is the case after https://github.com/paritytech/smoldot/pull/750), we will immediately allocate a 128MiB buffer.
This makes us use large amounts of memory for nothing.
This PR changes this. We only allocate enough for the size of the response announced by the remote.
=> Use less memory when receiving responses

src/sync/grandpa_warp_sync.rs
Empty fragments no longer means end of the proof.
=> Remove obsolete block of code from GP warp sync

src/chain/blocks_tree/finality.rs, src/finality/justification/decode.rs, src/finality/justification/verify.rs, src/network/protocol/grandpa_warp_sync.rs
The Beefy protocol is going to add new kinds of justifications. This PR pre-emptively renames `Justification` to `GrandpaJustification`.
I've been considering this rename for a long time now, but until the Substrate changes landed I wasn't sure whether justifications had a format implicitly derived from the chain configuration, or had some metadata indicating their protocol attached to them. It seems like we're going for the latter.
=> Rename Justification -> GrandpaJustification

.github/workflows/ci.yml, .github/workflows/deploy.yml, README.md, bin/wasm-node/javascript/prepare.js
De-duplicates the pinned Rust version.
Should be more automatic and assumes that the user has `rustup` installed.
=> Better management of pinned Rust version

bin/wasm-node/javascript/src/index.d.ts, bin/wasm-node/javascript/src/index.test-d.ts
* I added an accompanying typings test testing using smoldot with none of the optional options or parameters. 
* I made the exported types tests more explicit using the longer `ExpectType` comment for consistency.
=> Make chain_index parameter optional for json_rpc_callback

Cargo.lock, bin/full-node/Cargo.toml, bin/full-node/src/cli.rs, bin/full-node/src/main.rs
The `app_dirs` library is deprecated in favour of `directories`.
This PR modifies the path where the database is stored.
=> Replace app_dirs with directories

bin/wasm-node/javascript/src/bindings-smoldot-js.js, bin/wasm-node/javascript/src/index.d.ts, bin/wasm-node/javascript/src/index.js, bin/wasm-node/javascript/src/index.test-d.ts, bin/wasm-node/javascript/src/worker.js, bin/wasm-node/javascript/test/demo.js, bin/wasm-node/javascript/test/test.js
Exposes `cancel_all` to the JavaScript public API of the client.
Also tweaks `demo.js` to allow multiple clients to connect to the node.
The `send_json_rpc` function now takes three parameters.
The second parameter must always be zero for now, and will be used when smoldot supports multiple chains.
The third parameter is a "user data". The value of that third parameter must be a number, but its meaning is not interpreted by smoldot. The same value is later passed back as the third parameter of `json_rpc_callback` when the response to the request comes back.
Similarly, if the request passed in `send_json_rpc` is a subscription, all notifications will also be reported with that same third parameter.
A new method has been added: `cancel_all`. When called, all requests and subscriptions whose …
=> Add cancel_all to the JS public API

src/libp2p/peer_id.rs
After https://github.com/libp2p/specs/pull/316, support for RSA is no longer mandatory in the libp2p specifications.
=> Remove obsolete TODOs regarding RSA

src/chain/blocks_tree/best_block.rs, src/chain/fork_tree.rs, src/executor/host.rs
Two changes:
- One bugfix in the logic of choosing which fork is the best.
- Adds the missing runtime host function for getting the log max level.
=> Fix Westend after runtime upgrade

bin/wasm-node/rust/src/sync_service.rs, src/sync/all.rs, src/sync/optimistic.rs
Print the hash of the blocks that are verified, successfully or not.
=> Better debugging of blocks verified

src/database/full_sqlite.rs
Fix #766
As documented, the `babe_finalized_epoch` key in the `meta` table is missing if the chain doesn't use Babe or if the finalized block is 0.
However, we were using `UPDATE` to actually set its value once needed. If the key is missing, it would therefore never be inserted.
=> Fix `babe_finalized_epoch` meta key never being inserted

bin/wasm-node/rust/src/sync_service.rs
Important in situations such as right now where all blocks on top of the warp sync target are bad.
=> Report a new best block after GrandPa warp sync has succeeded

bin/wasm-node/rust/src/sync_service.rs, src/sync/all.rs, src/sync/grandpa_warp_sync.rs
Fixes the `todo!()` and implements it correctly.
I could test that it works thanks to Rococo whose bootnodes disconnect us.
=> Implement remove_source when GrandPa warp syncing

bin/kusama.json
We have spawned two new "connect" nodes with a TLS certificate in front, for when within a web page.
=> Add kusama-connect and polkadot-connect nodes

bin/wasm-node/rust/src/json_rpc_service.rs, bin/wasm-node/rust/src/lib.rs, bin/wasm-node/rust/src/network_service.rs, bin/wasm-node/rust/src/runtime_service.rs, bin/wasm-node/rust/src/sync_service.rs, src/sync/all.rs, src/sync/all_forks.rs, src/sync/all_forks/pending_blocks.rs, src/sync/all_forks/sources.rs, src/sync/grandpa_warp_sync.rs, src/sync/optimistic.rs
This PR performs a lot of progress towards https://github.com/paritytech/smoldot/issues/731
- All the methods on `NetworkService` that apply on the network as a whole and query things about a block are now moved to `SyncService`, as the `SyncService` is the piece of code that tracks which peer has which block.
- Adds `AllSync::knows_block` and `AllSync::source_knows_block` methods.
- Tweak the similar methods in `sources.rs` to assume that sources always know about all blocks that are part of the finalized chain if their best block is superior to the desired block.
=> Work towards properly querying nodes that know about desired block

bin/wasm-node/rust/src/sync_service.rs, src/sync/all.rs, src/sync/grandpa_warp_sync.rs
Instead of immediately verifying fragments when a GrandPa warp sync response arrives, the user now has to call `process_one` in order to verify a fragment.
This gives the possibility to benchmark and log individual fragments verification.
=> Move fragment verification to sync::all::ProcessOne

src/chain/chain_information.rs
Right now if both the Aura and Babe configurations fail to load, `MultipleConsensusAlgorithms` is returned.
This isn't great.
This PR would now return an `AuraConfigLoad` error, which has the advantage of containing the underlying problem.
=> Don't return MultipleConsensusAlgorithms if an error happened

bin/wasm-node/javascript/src/index.d.ts, bin/wasm-node/javascript/src/index.js, bin/wasm-node/javascript/src/index.test-d.ts, bin/wasm-node/javascript/src/worker.js, bin/wasm-node/javascript/test/demo.js, bin/wasm-node/javascript/test/test.js, bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/ffi/bindings.rs
cc @raoulmillais @wirednkod
This PR revamps the public JavaScript API:
- All the `snake_case` methods and fields now use `camelCase`, since that's what is idiomatic in JavaScript. `chain_spec` has been renamed to `chainSpecs` (with an `s`) because of the next point.
- Instead of passing one chain spec for the relay chain (and one for the parachain), you can now pass an array of chain specs (of arbitrary length). When you call `sendJsonRpc`, you should pass the index, within that array, of the chain that is concerned. This index is also passed back in return in the JSON-RPC callback.
See the changes to `demo.rs` to know how to propagate these changes to substrate-connect.
I'll publish 0.2.0 afterwards.
=> Revamp the public JavaScript API

Cargo.lock
Because of https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-hpqh-2wqx-7qp5
=> Update to cranelift-codegen v0.73.1

bin/wasm-node/rust/src/json_rpc_service.rs, bin/wasm-node/rust/src/sync_service.rs, src/chain/blocks_tree.rs, src/sync/all.rs, src/sync/all_forks.rs, src/sync/optimistic.rs
Necessary work for https://github.com/paritytech/smoldot/pull/845
Note that the code isn't fully implemented for parachains, as it's kind of complicated. One would need to download the runtime code of all blocks of all forks, which has little chance of succeeding flawlessly.
=> Implement SyncService::subscribe_all

src/sync/grandpa_warp_sync.rs
Some clean up after https://github.com/paritytech/smoldot/pull/646
=> Fix unused variables in GP warp sync

bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/sync_service.rs
Since https://github.com/paritytech/smoldot/pull/845 is going to take longer than expected, here are two back-ported changes:
- Don't actually start a timer if we want to delay 0ms.
- Clear all `subscribe_all` notifications in the sync service after a warp sync. This is a bugfix.
=> Backport two changes from #845

bin/wasm-node/rust/src/json_rpc_service.rs, bin/wasm-node/rust/src/runtime_service.rs
The problem right now is:
When the sync service finishes warp syncing, it returns `true` for `is_near_head_of_chain()`. The runtime service then picks up the warp-synced block and downloads the runtime code. It is only after the runtime code has been downloaded that the JSON-RPC layer is made aware of the new block.
While the runtime code is being downloaded, calling `system_health` would return `isSyncing: false`, even though the JSON-RPC layer isn't aware yet of any block that is actually near of the head of the chain.
This PR makes the call to `is_near_head_of_chain()` go through the runtime service instead.
=> Fix isSyncing returning false too early

Cargo.lock, bin/full-node/Cargo.toml, bin/full-node/src/network_service.rs, src/libp2p.rs, src/libp2p/async_rw_with_buffers.rs
Moves this module in `src` under the `std` feature flag, for code reuse purposes.
=> Move `with_buffers` module to `libp2p`

bin/wasm-node/rust/src/network_service.rs, src/network/service.rs
Can't merge now as it seems to trigger some kind of infinite loop
=> Enable discovery on the Wasm light client

src/chain/blocks_tree.rs, src/chain/blocks_tree/finality.rs, src/chain/fork_tree.rs
Also renames `ForkTree::iter` to `iter_unordered`, for clarity.
=> Add `NonFinalizedTree::finality_checkpoints`

src/libp2p/connection/established.rs
The code will presently panic if notifications are interleaved between yamux frames.
This PR fixes it.
=> Fix panic in networking regarding receiving notifications

bin/full-node/src/network_service.rs, bin/full-node/src/sync_service.rs, bin/wasm-node/rust/src/runtime_service.rs, bin/wasm-node/rust/src/sync_service.rs, src/sync/all.rs, src/sync/optimistic.rs
The full node would now use the same syncing code as the wasm node, allowing further clean ups, in particular in `optimistic.rs`.
=> Make full node use the "all" syncing strategy

bin/wasm-node/rust/src/lib.rs, bin/wasm-node/rust/src/sync_service.rs, src/chain/blocks_tree.rs, src/chain/chain_information.rs, src/chain_spec.rs, src/database/finalized_serialize.rs, src/database/full_sqlite.rs, src/sync/all.rs, src/sync/all_forks.rs, src/sync/grandpa_warp_sync.rs, src/sync/optimistic.rs
Adds new `ValidChainInformation` and `ValidChainInformationRef` types in `chain_information`.
These represent chain information whose coherence has been checked.
The consequence of this change to the logic of the code is that GrandPa warp sync and loading from a database now verify the coherence of the information rather than blindly assuming that it is correct (which would have caused the node to later panic if it turned out to not be true).
=> Add a ValidChainInformation type

bin/wasm-node/javascript/src/bindings-smoldot-js.js, bin/wasm-node/javascript/src/index.d.ts, bin/wasm-node/javascript/src/index.js, bin/wasm-node/javascript/src/index.test-d.ts, bin/wasm-node/javascript/src/worker.js, bin/wasm-node/javascript/test/demo.js
Fix #921 
Adds `forbidTcp`, `forbidWs` and `forbidWss` options to the configuration of smoldot, to ask to disable certain connection types.
I called the options `forbid*` instead of `allow*` because in JavaScript it can be confusing/error-prone to distinguish between `undefined`, `null` and `false`. Having options that default to `false` when they're missing seems like a good idea.
Also, importantly fixes some erroneous `return 1`s that weren't writing back any error message.
=> Allow enabling/disabling connection types

bin/wasm-node/javascript/prepare.js
cc https://github.com/paritytech/smoldot/issues/941
After this PR, the released versions would have debug assertions enabled.
Right now it's more important to make sure that everything is working fine than running quickly.
=> Default to `debug` build profile for wasm node

src/transactions/validate.rs
Backported change from https://github.com/paritytech/smoldot/pull/845
It turns out that we actually need to make a call to `Core_initialize_block` beforehand, and that the transaction validation function can modify the storage.
=> Fix transactions::validate to actually work

bin/wasm-node/javascript/package.json, bin/wasm-node/javascript/prepare.js
cc https://github.com/paritytech/smoldot/issues/941
"Reverts" https://github.com/paritytech/smoldot/pull/942, switching back to release for published packages. The generated package is too big to be realistically used.
=> Allow passing --debug or --release to prepare.js

src/transactions/validate.rs
Here's what Substrate actually does: https://github.com/paritytech/substrate/blob/d6c33e7ec313f9bd5e319dc0a5a3ace5543f9617/client/service/src/client/client.rs#L1207
Consequently, the smoldot code is confirmed to be correct.
=> Remove TODO in validate.rs about initialize_block

src/transactions/validate.rs
https://github.com/paritytech/smoldot/pull/966 was wrong.
The parameters of `Core_initialize_block` should, for some reason, use the block to request against as a parent.
=> Fix parameters to Core_initialize_block again

bin/wasm-node/rust/src/json_rpc_service.rs
This warning is maybe questionable in the absolute, but it is right now a major pain point when `state_getMetadata` returns an error.
=> Show warning if state_getMetadata returns error

bin/full-node/src/sync_service.rs, bin/wasm-node/rust/src/runtime_service.rs, bin/wasm-node/rust/src/transactions_service.rs, src/author/build.rs, src/author/runtime.rs, src/author/runtime/tests.rs, src/chain/blocks_tree/verify.rs, src/executor/host.rs, src/executor/runtime_host.rs, src/sync/all.rs, src/sync/optimistic.rs, src/transactions/validate.rs, src/verify/execute_block.rs, src/verify/header_body.rs
Fix #1010 
This turned out to be slightly trickier than expected, as the keys returned by `inject_keys` now need to be ordered, while this wasn't the case before.
=> Implement ext_storage_clear_prefix_version_2

bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/json_rpc_service.rs, bin/wasm-node/rust/src/lib.rs
This PR is a continuation of https://github.com/paritytech/smoldot/pull/994
https://github.com/paritytech/smoldot/pull/994 considerably changed the general structure of the JSON-RPC stuff: a separate JSON-RPC service is now spawned for each "API user" as opposed to one per chain.
This PR performs some clean ups.
Fix https://github.com/paritytech/smoldot/issues/998
=> Refactor JSON-RPC service

bin/wasm-node/rust/src/lib.rs
PolkadotJS seems a bit greedy, so let's increase these values.
=> Bump number of allowed parallel JSON-RPC requests

bin/full-node/src/sync_service.rs, bin/wasm-node/rust/src/sync_service.rs, src/sync/all.rs, src/sync/all_forks.rs, src/sync/all_forks/pending_blocks.rs
This PR modifies the public API of the `AllSync` state machine to mimic the one of `AllForks`.
This was previously using an API based on returning the diff between two state changes. This turned out to be way too complicated to use.
This PR doesn't update `optimistic.rs` to have a similar API. As a consequence, this PR breaks the full node, which will now panic on startup.
An issue should be opened about updating `optimistic.rs` after this PR is merged.
=> Simplify all.rs

src/executor/runtime_host.rs, src/header/aura.rs, src/header/babe.rs, src/header/grandpa.rs, src/libp2p/connection/multistream_select.rs
Thanks to the stabilization of `impl<T, const N: usize> AsRef<[T]> for [T; N]`, these structs are no longer necessary.
=> Remove weird `One` structs

.github/workflows/deploy.yml
Hopefully fix the deploy CI failure: https://github.com/paritytech/smoldot/runs/3269769250
=> Publish NPM packet as public

bin/full-node/src/network_service.rs, bin/wasm-node/rust/src/network_service.rs, src/libp2p.rs, src/libp2p/collection.rs, src/libp2p/connection/established.rs, src/libp2p/peers.rs, src/libp2p/read_write.rs, src/network/service.rs
Attempt to simplify the logic of the network code by accepting a `&mut ReadWrite` as parameter everywhere, rather than splitting that logic between the function parameter and the return value.
Opening as draft because it panics right now.
=> Change network functions to accept &mut ReadWrite

src/network/service.rs
Fixes the "lower level bug" mentioned in https://github.com/paritytech/smoldot/pull/1123, which turned out to not be a lower level bug.
=> Fix lack of notifications

bin/wasm-node/javascript/demo/demo.js, bin/wasm-node/javascript/src/health.js, bin/wasm-node/javascript/src/index.d.ts
Apparently, importing `randombytes` from the health checker causes issues with some JS thing somewhere, so for the sake of making things move we'll remove this import.
Consequently, the API of the health checker needs to change:
- You no longer need to pass the `sendJsonRpc` function to the `start()` method, but instead pass it to a new `setSendJsonRpc()` method. Call `setSendJsonRpc()` right after initializing the health checker.
- You **must** now use `sendJsonRpc` on the health checker, which modifies it and propagates it to the callback that you passed to `setSendJsonRpc`. Do **not** call `sendJsonRpc` directly on the smoldot chain.
The rest stays the same.
**I also would like to remind that the health checker is documented** as comments to the `healthChecker` function.
I modified …
=> Remove randomness from health checker

src/network/service.rs
Substrate nodes only accept transactions and GrandPa substreams after the block announces substream has been opened. With the recent networking clean ups, we opened all substreams at once and all tx+gp substreams were refused.
This PR correctly opens tx and gp only after block announces substreams.
=> Fix finality not working anymore

bin/wasm-node/rust/src/runtime_service.rs, src/trie.rs, src/trie/prefix_proof.rs, src/trie/proof_node_decode.rs, src/trie/proof_verify.rs
Code clean up and better error reporting
=> Split decoding proof node from analyzing proof

src/libp2p/connection/established.rs
This ignores a panic in established.rs. The higher level API needs adjustments to fix this properly.
=> Silence a state mismatch in established.rs

bin/wasm-node/javascript/package.json
The tests seem to time out quite often on CI, so let's increase the timeout.
=> Increase JS tests timeout to 2 minutes

src/libp2p/connection/established.rs
Since `yamux` doesn't support reading data without discard it, we bypass this by queuing events.
=> Fix debug assertions with frame size mismatch

bin/wasm-node/rust/src/transactions_service.rs, src/transactions/light_pool.rs, src/transactions/pool.rs
These methods are a bit too dangerous.
=> Remove clear_and_reset methods from tx pools

src/network/service.rs
Having many mutexes is a bit too complicated.
This PR refactors them in two mutexes: one around `read_write`, and one for everything else.
=> Refactor the mutexes in service.rs

src/libp2p/collection.rs, src/libp2p/connection/established.rs, src/libp2p/connection/yamux.rs, src/libp2p/peers.rs
At the moment, collection.rs's API identifies substreams by `(ConnectionId, notif protocol)` and enforces that only a single substream is open per connection per protocol.
However the implementation of `peers.rs` already enforces this, making the check in collection.rs redundant.
After this PR, collection.rs now accepts multiple substreams per connection per protocol.
This also fixes a race condition regarding `in_notification_accept` in collection.rs that could be ambiguous, and adds `in_notification_reject`, which wasn't possible to do properly before.
=> Refactor collection.rs to identify notif substreams by id

bin/wasm-node/rust/src/sync_service.rs
Before this PR, answering `system_health` and `system_peers` can take several seconds because the sync service is stuck waiting for a networking response.
=> Run fetching para heads in parallel from service

bin/wasm-node/rust/src/ffi.rs, bin/wasm-node/rust/src/ffi/timers.rs
No longer call `setTimeout` for every single `Delay` that we create.
=> Optimize timers in wasm node

src/author/runtime.rs, src/chain/blocks_tree/verify.rs, src/executor/runtime_host.rs, src/sync/optimistic.rs, src/transactions/validate.rs, src/verify/execute_block.rs, src/verify/header_body.rs
Before this PR, the full node syncing is stuck at block 4876134 because block 4876135 does a lot of `NextKey` requests, which have a crazy `O(n)` complexity (`n` being the size of the storage diff, which increases over time during execution of block 4876135).
This slows down the rest of the syncing quite a bit, but it makes block 4876135 sync almost instantaneously while before it would be stuck for hours.
=> Use a BTreeMap for the storage diffs

src/executor/allocator.rs
There have been changes regarding the maximum allowed size of an allocation. While we're at it, I just completely backported the allocator.
Close https://github.com/paritytech/smoldot/issues/1120
=> Backport Substrate's allocator

bin/wasm-node/rust/src/network_service.rs, bin/wasm-node/rust/src/sync_service.rs, src/libp2p/peers.rs, src/network/service.rs
This reverts commit 65d5ddac4c0305fee031cf738bc3d432f8963c4f.
There are connectivity issues that first need to be solved.
=> Revert "Properly return only the peers belonging to the chain (#1318)"

bin/full-node/src/run/sync_service.rs, bin/wasm-node/rust/src/sync_service.rs, src/sync/all.rs, src/sync/all_forks.rs, src/sync/all_forks/pending_blocks.rs, src/sync/optimistic.rs, src/sync/optimistic/verification_queue.rs
Close https://github.com/paritytech/smoldot/issues/306
After this PR, neither `all_forks` nor `optimistic` enforce one request per peer. Instead, it is the `sync_service` that does that by calling a new `source_num_ongoing_requests` method.
=> Properly select requests to start

bin/wasm-node/rust/src/lib.rs
Important for `rococo_v1_8` to not be printed as `rococov18`
=> Allow more ASCII characters in chain name

src/libp2p/peers.rs, src/network/service.rs
cc https://github.com/paritytech/smoldot/issues/1340
=> Add a way to "reset" the rejected desired substreams

bin/wasm-node/javascript/src/health.js, bin/wasm-node/rust/src/json_rpc_service.rs
Right now, the following scenario happens every time a chain is added:
- The Grandpa warp sync is performed, and a new best block is reported through the JSON-RPC layer.
- The health checker detects this, realizes that `isSyncing` has become `false`, and substrate-connect tells PolkadotJS that we're now connected.
- In the meanwhile, smoldot started downloading the runtime code of the block we warp synced to. After the download is complete, it potentially detects a change in the runtime spec and reports it to PolkadotJS.
This, unfortunately, seems to confuse PolkadotJS for an unclear reason. I think that PolkadotJS simply isn't very much tested against runtime upgrades.
In order to solve this problem, we now report `isSyncing` equal to `true` for as long as the runtime code of the block …
=> Don't report `isSyncing: false` until after the runtime has changed

bin/wasm-node/rust/src/network_service.rs
Introduces a hack to avoid passing `is_unreachable: true` when it should be `false`.
cc https://github.com/paritytech/smoldot/issues/1531
=> Pass false for is_unreachable on Wasm

bin/wasm-node/javascript/README.md, bin/wasm-node/rust/src/ffi/bindings.rs, src/json_rpc.rs
The pub-sub system isn't actually an extension to the specification. It just makes use of the fact that the listening side of the connection can send notifications to the dialing side.
=> Clarify JSON-RPC pub-sub system

src/executor/host.rs
Need to sync a chain before merging, to make sure no mistake was made.
=> Don't use parity_scale_codec in the crypto recover host functions

src/chain/blocks_tree.rs, src/chain/blocks_tree/finality.rs, src/chain/blocks_tree/verify.rs
This removes the `O(n)` complexity in the `NonFinalizedTree`
=> Add a blocks_by_hash field in NonFinalizedTree

bin/full-node/src/run/network_service.rs, bin/light-base/src/network_service.rs, src/network/service.rs
Right now the `now` parameter is passed to the function, but since this function can sleep, the `now` will no longer be up-to-date.
=> Fix timeout too short in the StartConnect

bin/wasm-node/javascript/src/compat-browser.js, bin/wasm-node/javascript/src/compat-nodejs.js, bin/wasm-node/javascript/src/index.d.ts, bin/wasm-node/javascript/src/index.js, bin/wasm-node/javascript/src/index.test-d.ts
As I was trying to understand why there is a test that's not working on the PR that tries to [upgrade `smoldot-light` on `substrate-connect`](https://github.com/paritytech/substrate-connect/pull/555), I've noticed 2 issues on `smoldot-light`:
- The type definitions exported on the `index.d.ts` file don't actually match what's being exported. This must have been the case for quite some time now, since [substrate-connect is abusing `any` in order to use `smoldot-light`](https://github.com/paritytech/substrate-connect/blob/master/projects/extension/src/background/ConnectionManager.ts#L219), which pretty much defeats the purpose of the typings file. The first commit addresses that.
- The second commit improves the behavior of `client.terminate`, because the current behavior causes weird …
=> smoldot light improvements

.github/workflows/ci.yml, .github/workflows/deploy.yml, src/chain_spec/light_sync_state.rs, src/chain_spec/structs.rs
Note that this pins Rust versions only in the situations where the Rust compiler output is important.
In particular, we don't pin any version for the `cache-fill` jobs, as filling the cache is secondary. We also don't pin the version for the audits check.
=> Pin Rust versions on CI

src/sync.rs, src/sync/all.rs, src/sync/warp_sync.rs
Removes most of the `Grandpa` prefixes, but not all. The warp sync state machine is no longer specific to Grandpa, but still emits requests that are specific to Grandpa.
=> Rename grandpa_warp_sync to warp_sync

.github/workflows/ci-post-workflow.yml
This reverts commit 34c7ded3100ba83ac60efc1e15e2c19473aa9fb1.
This broke the action.
=> Revert "Bump actions/github-script from 3.1.0 to 5 (#1740)"

.github/workflows/ci.yml
This is a follow-up to https://github.com/paritytech/smoldot/pull/1729
Without this PR, the CI is broken at the moment.
=> Update path to artifacts after build profile transition

src/informant.rs
We will now print for example `150 kiB` instead of `150.2 kiB`.
The precision still stays when there's less than 3 digits, for example `15.2 kiB` or `1.5 kiB`
=> Better precision for BytesDisplay

bin/light-base/src/lib.rs, bin/light-base/src/sync_service.rs, bin/light-base/src/sync_service/standalone.rs, src/database/finalized_serialize.rs
This scopes the usage of `finalized_serialize` to `lib.rs`, and also unlocks the way for https://github.com/paritytech/smoldot/issues/1769 which will require knowing the finalized block from `lib.rs`.
=> sync_service now returns a ValidChainInformation instead of String

src/executor/host.rs, src/executor/vm.rs, src/executor/vm/interpreter.rs, src/executor/vm/jit.rs
This PR fixes the current mess with `heap_pages`.
I now have a better understanding of what heap pages are for.
It also adds a new feature: the memory of the heap is not completely allocated upfront, but lazily when the allocator allocates from it.
In other words, if your heap pages value is for example 10, we start with 0 (and check that 10 would fit) and dynamically increase the actual allocated memory. 10 is only the limit given to the allocator after which it returns an error, but doesn't correspond to an actual amount of allocated memory anymore.
=> Allocate Wasm memory lazily

bin/full-node/src/cli.rs
I actually prefer the current form, but the `--help` option has `s`es as well, so let's go for consistency.
=> Adjust grammar of CLI option

bin/wasm-node/javascript/package-lock.json, bin/wasm-node/javascript/package.json, bin/wasm-node/javascript/prepare.js, bin/wasm-node/javascript/src/worker.js
See comment.
Unfortunately, we now depend on a new library, `pako`, which is itself ~200kiB, meaning that we don't actually gain much.
However, this solves the problem of the Mozilla extension store having a maximum allowed size of 4 MiB on individual files.
=> Compress the .wasm before base64-encoding it

.github/cargo-deny.toml, Cargo.lock, Cargo.toml, bin/light-base/Cargo.toml, src/identity/keystore.rs, src/libp2p/collection.rs, src/libp2p/connection/established.rs, src/libp2p/connection/yamux.rs, src/libp2p/peers.rs, src/network/service.rs, src/util.rs
Cryptographers don't seem to be fans of `ahash`.
=> Replace ahash with siphasher

.github/dependabot.yml, .github/workflows/deps-update.yml
Dependabot clearly doesn't work properly. Doing `cargo update` now shows tons of updates that the bot hasn't opened PRs for.
=> Do the dependencies management through GH actions

bin/wasm-node/rust/src/alloc.rs
So that we don't use the default implementations we do the slowest possible thing.
=> Overwrite all the functions of GlobalAlloc

bin/wasm-node/javascript/src/index.d.ts, bin/wasm-node/javascript/src/index.js, bin/wasm-node/javascript/test/misc.js
This is important in order to prevent clients from clogging the server with tons of very large requests.
=> Reject JSON-RPC requests that are too long

Cargo.toml
Reduces the debug wasm size from 95 MiB to 45.8 MiB, and the full node size from 159.9 MiB to 132.2 MiB.
=> Use debug = 1 for the dev profile

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service/parachain.rs
So far my attitude has been "the notifications subscriber can just maintain their own tree of blocks", but it turns out that this is really complicated and annoying to do. Instead, the pruned blocks are also sent by the background task.
=> Report pruned blocks in runtime service notifications

src/chain_spec/structs.rs
cc https://github.com/paritytech/smoldot/issues/1844
This PR makes us compatible with both old and new chain specs. This is possible because the field is currently unused and private.
After a new version of smoldot is released, the chain specs can be updated, and then later we can remove the hexadecimal.
=> Become compatible with new codeSubstitutes

bin/wasm-node/javascript/src/client.ts, bin/wasm-node/javascript/src/worker/messages.ts, bin/wasm-node/javascript/src/worker/worker.ts
The worker no longer returns a confirmation about a chain removal.
=> Remove the chainRemoved confirmation

bin/full-node/src/run/consensus_service.rs, bin/light-base/src/runtime_service.rs, src/author/runtime/tests.rs, src/chain/chain_information/aura_config.rs, src/chain/chain_information/babe_genesis_config.rs, src/chain/chain_information/grandpa_genesis_config.rs, src/executor/host.rs, src/executor/read_only_runtime_host.rs, src/executor/runtime_host.rs, src/sync/all.rs, src/sync/warp_sync.rs, src/verify/header_body.rs
cc https://github.com/paritytech/smoldot/pull/1838
The idea is that there's no need to prevent the runtime from compiling if it uses host functions. The problem only comes when these functions are called, in which case we trap.
This is helpful in situations where, for example, the runtime uses a new offchain worker function, but we don't care since we don't run offchain workers.
The values I've put are:
- `false` for things that touches the genesis runtime, as it's useful to detect problems there.
- `false` but with a `TODO: make configurable` for GrandPa warp syncing, with the intention to switch to `true` in the light client.
- `false` but with a `TODO` for the implementation of `ext_misc_runtime_version_version_1`.
- `true` in the light client.
=> Add an option to HostVmPrototype::new to allow unresolved imports

bin/wasm-node/javascript/src/worker/spawn-browser-overwrite.js
Tested with WebPack 5 on Firefox and Chrome. Firefox doesn't seem to display the name anywhere.
=> Add a name to the worker when in the browser

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service.rs
Right now a storage query is done by just asking 3 random peers. This PR changes this to instead ask peers that are presumed to know about the block in question. This requires passing the block number to the `storage_query` function.
=> Better select peers for storage queries

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/light-base/src/sync_service.rs, bin/light-base/src/transactions_service.rs
Same as https://github.com/paritytech/smoldot/pull/1928 but for `block_query`.
As usual, the most tricky part of the code to update were the legacy JSON-RPC functions in `state_chain.rs`.
=> Better peers selection in SyncService::block_query

src/chain/chain_information.rs, src/finality/grandpa/warp_sync.rs, src/sync/warp_sync.rs
Right now, if we do a warp sync proof and the node returns "well, I have nothing", we print an error. This PR changes this so that we accept the proof instead.
While this could lead to nodes pretending to have nothing even though they have things, it is already the case today that nodes can return fewer fragments than they actually have. While this would be annoying, this isn't really an attack as it would only change the moment when we switch to a slower syncing technique.
Fix https://github.com/paritytech/smoldot/issues/1952
cc https://github.com/paritytech/smoldot/issues/722
=> Accept empty proofs if finished: true

src/chain_spec.rs, src/chain_spec/structs.rs
cc https://github.com/paritytech/smoldot/issues/1955
This PR adds support for chain specs with a `forkId` field, because they exist in the wild now and we need to be able to parse them.
The purpose of the `forkId` is to eventually replace `protocolId`, but at the moment Substrate/Polkadot nodes only support `protocolId` when it comes to released versions, and support both when it comes to the master branch.
Another smoldot PR later should add support for `forkId` once Substrate/Polkadot have released a version that uses it.
=> Support chain specs with `forkId`

bin/full-node/src/run/network_service.rs, bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/light-base/src/network_service.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service.rs, bin/light-base/src/sync_service/parachain.rs, bin/light-base/src/sync_service/standalone.rs, bin/light-base/src/transactions_service.rs, src/json_rpc/methods.rs, src/network/service.rs
At the moment, sending an individual request to a peer always has a fixed timeout, after which the request fails.
Sending a "group request" (e.g. downloading a block body, without indicating who to download it from) always has 3 serial attempts after which the "group request" fails.
In practice, this isn't great.
Some requests are bigger than others and some are more urgent than other, and because there is a cap on the bandwidth of each peer and on the number of allowed parallel requests we should have some way to prioritize some requests over others.
This PR changes the API of all the network primitives to make it possible to specify a total number of requests, a maximum number of parallel requests, and a timeout for each individual request.
This PR thus also implements the …
=> Give proper requests count and timeout parameters to every network request

src/transactions/light_pool.rs, src/transactions/light_pool/tests.rs
cc https://github.com/paritytech/smoldot/issues/1966 https://github.com/paritytech/smoldot/issues/1433
#1966 shows a state mismatch within the pool. The code that this PR adds solves this state mismatch. Unfortunately I can't figure out how to reproduce the issue with a test.
=> Maybe fix transactions pool bug

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/lib.rs, bin/light-base/src/network_service.rs, src/network/service.rs
There's a small problem before this PR: a user can add a chain with an empty list of bootnodes, then add another chain with a non-empty list of bootnodes. Because the networking service is created only the first time, the bootnodes of that other chain will never be added, and the networking of the second chain will not have any peer.
=> Change the way bootnodes are passed to networking

bin/full-node/src/run/network_service.rs, bin/light-base/src/network_service.rs, src/libp2p/peers.rs, src/network/service.rs
More or less as a follow-up to https://github.com/paritytech/smoldot/pull/1976, we no longer pass an initial list of bootnodes to the networking. Instead, you're supposed to call `discover` after initialization.
If there's ever a need to non-asynchronously add bootnodes, we could in the future add `discover_mut` that does the same as `discover` but accepts a `&mut self`.
=> Remove initial bootnodes configuration from networking

src/chain/blocks_tree/verify.rs, src/chain/chain_information.rs, src/chain/chain_information/babe_fetch_epoch.rs, src/sync/warp_sync.rs, src/verify/babe.rs
It turns out there is some fiasco regarding `start_slot_number`.
Currently it is an `Option` and the documentation mentions that it must be none iff `epoch_index` is 0.
This is however only true for future epochs. If the current epoch is epoch 0, then its starting slot can be known and must be known.
This PR modifies the check for the validity of chain information to allow passing a slot number for epoch 0 if it is the current epoch. This fixes a problem during warp syncing to a block within epoch 0.
Since the `blocks_tree` module would always leave `start_slot_number` equal to None for epoch 0 when syncing from scratch, it would now lead to an invalid `ChainInformation` when serializing the state when within epoch 0. This has been updated too.
Additionally, when fetching the Babe epoch …
=> Make start_slot_number mandatory for past epochs

bin/wasm-node/rust/src/lib.rs, bin/wasm-node/rust/src/timers.rs
The PR https://github.com/paritytech/smoldot/pull/2005, which is wrong, shows that this bound is missing.
=> Force 'static bound in start_timer_wrap

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/lib.rs
Refactor the JSON-RPC service initialization to fix the problem outlined [here](https://github.com/paritytech/smoldot/issues/1961#issuecomment-1032988876).
Fix #1961
Fix #1935
More precisely, this PR splits the JSON-RPC service initialization in two: first we create some kind of channel-like, then later we finish initialization. Thanks to this, the JSON-RPC service itself supports sending requests immediately even before it is fully initialized. Right now it's `lib.rs` that does this, and does it poorly.
=> Refactor JSON-RPC service initialization

Cargo.lock, bin/wasm-node/javascript/package-lock.json, bin/wasm-node/javascript/package.json, bin/wasm-node/rust/Cargo.toml
I want to release https://github.com/paritytech/smoldot/pull/2030
Major version bump is done because of https://github.com/paritytech/smoldot/pull/2024
There's been no API change otherwise.
=> Publish v0.6.0

src/executor/host.rs, src/executor/runtime_host.rs, src/header.rs
This was done in https://github.com/paritytech/substrate/pull/10080
=> Remove support for the changes trie

src/libp2p/multiaddr.rs
The current `Debug` implementation is quite annoying to read and brings nothing over the regular multiaddr string representation.
=> Make fmt::Debug for Multiaddr behave as Display

src/verify/header_only.rs
After https://github.com/paritytech/smoldot/pull/2034
=> Remove obsolete comment about changes trie

bin/full-node/src/run/consensus_service.rs, bin/light-base/src/runtime_service.rs, src/author/runtime/tests.rs, src/chain/chain_information/aura_config.rs, src/chain/chain_information/babe_genesis_config.rs, src/chain/chain_information/grandpa_genesis_config.rs, src/executor/host.rs, src/executor/read_only_runtime_host.rs, src/executor/runtime_host.rs, src/sync/warp_sync.rs, src/verify/header_body.rs
Doesn't change anything, but ensures that parameters are named.
=> Give a configuration struct to HostVmPrototype::new

bin/light-base/src/network_service.rs
Brings them to the same format as the rest of the logs of the wasm node, plus adds the chain name when relevant.
=> Improve networking logs of wasm node

src/executor/host.rs
Normally the input data isn't part of the heap but below. In smoldot we make it part of the heap (cc #132). The problem is that this munches on the available memory. To solve this, we hackily add one page to the available memory. However it turns out that one extra page sometimes isn't enough.
=> Increase size for input data

bin/full-node/src/run/consensus_service.rs, src/executor/runtime_host.rs, src/executor/storage_diff.rs
Close https://github.com/paritytech/smoldot/issues/1305
Also renames `diff_iter()` to `diff_iter_unordered()` because the ordering is now broken. This clarifies that no ordering is guaranteed.
Opening as draft because it seems that this might actually slow down syncing. Need to do some precise measurements.
=> Optimize storage diff by having both a hashmap and btree

.github/workflows/ci.yml
I assumed @tomaka  didn't like [`cargo-nextest`](https://nexte.st/index.html) so not suggesting it here.
Here you go, 1sec instead of 2 min
=> Use cached cargo-install

bin/light-base/src/transactions_service.rs, src/transactions/light_pool.rs
Fix #2044
Fix #2047
It's a bit hard to name this PR other than "work on the transactions pool", because it does a bunch of things.
We now properly keep in memory the validation status of a transaction against blocks that are finalized.
We also now properly check the longevity of transactions, after which they are revalidated.
The transactions pool is still in a unfinished state because it's so complicated, but this is definitely a step in the right direction.
=> Work on light transactions pool

bin/light-base/src/json_rpc_service/chain_head.rs, src/json_rpc/methods.rs
Continuation of https://github.com/paritytech/smoldot/pull/2075
To be honest I have no idea what I'm doing with these `#[serde(borrow)]`. Apparently removing them fixes the problem.
=> Fix lifetime error with chainHead_unstable_followEvent

src/executor/vm.rs, src/executor/vm/interpreter.rs, src/executor/vm/jit.rs
Removes an `Option`, making the code cleaner.
=> Make having a memory in VM mandatory

bin/wasm-node/javascript/src/client.ts
Minor change that makes more sense to me
=> Report crashes in one call to console.error instead of two

src/author/build.rs, src/author/runtime.rs, src/author/runtime/tests.rs, src/verify/inherents.rs
Close https://github.com/paritytech/smoldot/issues/2096
What the comment says: we no longer pass the Aura/Babe slot number to the runtime when authoring blocks, because they're unused anyway. Authoring blocks using older runtime versions is intentionally not supported.
Verifying the inherents of blocks isn't implemented in smoldot yet, and will be covered by https://github.com/paritytech/smoldot/pull/2073
=> Remove from InherentData the Aura/Babe slot number

bin/light-base/src/sync_service/standalone.rs
When investigating https://github.com/paritytech/smoldot/issues/2088 I realized that we were missing this critical info.
=> Log the block's parent in block announces

bin/light-base/src/sync_service/parachain.rs
Fix #2088 
See #2088 for context.
What this PR fixes is that we no longer notify about a new parachain block if the same parachain block was already in another relay chain fork.
=> Don't notify the same parahead twice

bin/full-node/src/run.rs
It creates a cooler-looking effect.
=> Run the informant every 100 ms instead of every second

bin/light-base/src/sync_service/parachain.rs, src/sync/all.rs, src/sync/all_forks.rs, src/sync/all_forks/disjoint.rs, src/sync/all_forks/pending_blocks.rs, src/sync/all_forks/sources.rs
I don't know how to title this PR more appropriately than "generic improvements to the code".
This PR basically finishes the original vision of the `pending_blocks.rs` module by adding a `unnecessary_unverified_blocks` function.
For context, the data structure in `pending_blocks.rs` tracks blocks that we know exist but can't be verified yet (because they're not a direct child of a block that has been verified, or because haven't downloaded their header yet, or in the case of the full node because we only have their header and not their body).
This newly-added `unnecessary_unverified_blocks` function returns a list of unverified blocks that aren't strictly necessary to make the syncing progress. These blocks are blocks that are known to be on a bad fork, and blocks that are somewhere …
=> Improvements to all_forks syncing

Cargo.lock, Cargo.toml, src/executor/host.rs
Closes #1968
Note this PR implements `ecdsa_sign` and introduces `ecdsa_verify` function, which are both out of the scope of the issue above.
=> implement ecdsa sign, verify, sign_prehashed and verify_prehashed

bin/wasm-node/CHANGELOG.md
After this PR is merged, every noticeable PR that concerns the wasm node should update this CHANGELOG.
I'm not including changes such as https://github.com/paritytech/smoldot/pull/2073 because they only concern the full node.
We could consider adding a CI action that checks whether the CHANGELOG respects a certain format, but I haven't found anything great.
We could also consider adding a CI action that reminds you to add a CHANGELOG entry if you didn't (unless you explicitly say "this doesn't need a changelog entry"), but that also seems kind of complicated.
=> Introduce a CHANGELOG for the wasm node

bin/wasm-node/CHANGELOG.md, src/sync/all_forks/disjoint.rs
If a certain block is bad, all its descendants are meant to be marked as bad as well.
When you call `set_parent_hash`, and the parent is bad, the immediate child is set as bad. This PR also sets the entire chain of descendants as bad.
=> Make set_parent_hash mark entire chain as bad

src/sync/all.rs, src/sync/all_forks.rs
Continuation of https://github.com/paritytech/smoldot/pull/2123 and https://github.com/paritytech/smoldot/issues/1572
Instead of having `FinishAncestrySearch::add_block` immediately insert the block, we now instead return a new `AddBlock` enum that indicates whether the block has already been inserted before, and that lets you actually do the block insertion.
The diff is moderately large, but this PR should be easy to review commit by commit.
It still doesn't finish this whole "user data saga". The next steps will be to update `block_announce` and `add_source`, as they also manipulate blocks. I didn't want to bloat this single PR too much.
=> Refactor all forks a bit

Cargo.lock, bin/full-node/Cargo.toml, bin/full-node/src/run/network_service.rs
New function added in Rust 1.59.
There's no policy about minimum Rust version in smoldot at the moment. We don't have to merge this now but can wait a bit if necessary.
=> Use new std::thread::available_parallelism function

bin/light-base/src/lib.rs
=> Print warning if list of bootnodes is empty

Cargo.toml
Hello,
There might be a performance regression due to enabling lto without limiting the number of code generation units (codegen-units = 1).
References:
https://github.com/rust-lang/rust/issues/47745
https://doc.rust-lang.org/rustc/codegen-options/index.html#codegen-units
=> limit codegen-units to get the maximum optimization

bin/wasm-node/CHANGELOG.md, src/header.rs
Close https://github.com/paritytech/smoldot/issues/2139
I wanted to add a unit test, but we have no good way to obtain a SCALE-encoded header from a Substrate node.
Since the code is just copy-pasted from the one of the Beefy and Polkadot log items, it should work.
=> Add support for the "fron" log item

bin/full-node/src/run/consensus_service.rs, bin/full-node/src/run/network_service.rs, src/network/protocol/block_announces.rs, src/network/service.rs, src/sync/all.rs, src/sync/all_forks.rs, src/sync/optimistic.rs
This PR implements announcing blocks to other peers when in full mode.
In other words, if node A is connected to B, and B is connected C, when A announces a block to B, B will now announce it to C.
After this PR, it is now possible to launch two smoldot full nodes and have them produce a chain.
The CLI flags I use for that are:
> ./full-node run --chain ./bin/substrate-node-template.json --tmp --listen-addr /ip4/127.0.0.1/tcp/30333 --libp2p-key 0x0000000000000000000000000000000000000000000000000000000000000000 --keystore-memory //Alice --jaeger 127.0.0.1:6831
And:
> ./full-node run --chain ./bin/substrate-node-template.json --tmp --additional-bootnode /ip4/127.0.0.1/tcp/30333/p2p/12D3KooWDpJ7As7BWAwRMfu1VU2WCqNjvq387JEYKDBj4kx6nXTN --jaeger 127.0.0.1:6831 --json-rpc-address 127.0.0.1:0 …
=> Implement block announces in full node

bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/client.ts, bin/wasm-node/javascript/src/worker/bindings.ts, bin/wasm-node/javascript/src/worker/instance.ts, bin/wasm-node/javascript/src/worker/messages.ts, bin/wasm-node/javascript/src/worker/worker.ts, bin/wasm-node/rust/src/bindings.rs, bin/wasm-node/rust/src/cpu_rate_limiter.rs, bin/wasm-node/rust/src/init.rs, bin/wasm-node/rust/src/lib.rs
Adding an option to limit the amount of CPU consumed by smoldot.
Warp syncing a long chain such as Kusama can use a lot of CPU for up to 10-15 seconds, and we'd rather not have a web page or the substrate-connect extension use up an entire CPU for this long, as it tends to cause systems to freeze.
After this change is merged and published, I'd cap the CPU to 50% in substrate-connect.
=> Add ClientOptions.cpuRateLimit

bin/wasm-node/javascript/src/client.ts, bin/wasm-node/javascript/src/worker/messages.ts, bin/wasm-node/javascript/src/worker/worker.ts
Very insubstantial change with the objective of removing an `as` in TypeScript
=> Pass a string in chainAddedErr to remove an as

src/chain/blocks_tree.rs, src/sync/all.rs, src/sync/all_forks.rs
Continuation of https://github.com/paritytech/smoldot/pull/2142 and https://github.com/paritytech/smoldot/issues/1572
This is the last step of the modifications to `all_forks.rs`
This now stores a "user data" for pending blocks in `all_forks.rs` as well, and adjusts all the APIs.
I haven't touched any of the API of `all.rs`. Instead I've made it so that `all.rs` stores a `None` in the `AllForksSync` when the block is still pending, and replaces it with a `Some` when it no longer is.
=> Add a user_data for pending blocks in all_forks.rs

bin/full-node/src/run.rs, bin/full-node/src/run/consensus_service.rs, bin/full-node/src/run/network_service.rs, bin/light-base/src/network_service.rs, bin/light-base/src/sync_service/parachain.rs, bin/light-base/src/sync_service/standalone.rs, src/network/protocol/block_announces.rs, src/network/service.rs
At the moment the decoded block announces struct contains at the same time `header` (decoded) and `scale_encoded_header` (encoded)
The reason why there are two is because the block announces format concatenates the header with the other fields, meaning that it is not possible to decode block announces without decoding the header. In other words, if a block announces has been successfully decoded, then the header is necessarily decodable successfully as well.
However, this fact should be seen as a quirk in the block announces format. It would be better if you could decode the announce without decoding the header, and it's not completely impossible that we do this in the long future.
This PR removes `header` and commits to the fact that `scale_encoded_header` might be undecodable. It is …
=> Fix hack in the block announces format

bin/light-base/src/network_service.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service/parachain.rs, bin/light-base/src/sync_service/standalone.rs, bin/wasm-node/CHANGELOG.md
All the logs that look a bit "system-y" (which are all the debug and trace logs) now show errors through the `Debug` trait rather than `Display`
This fits the vibe of the log line more, and also provides additional information.
The `Display` trait is still used for warning and error logs that the user is expected to react to.
=> Logs errors as Debug and not Display

bin/wasm-node/CHANGELOG.md, src/sync/all_forks.rs
Fixes a bug introduced in https://github.com/paritytech/smoldot/pull/2114
I don't know why I had added this call to `remove_sources_known_block` after a block has been successfully verified. Not only it is obviously wrong, but in #2114 I tried to not change the behavior and added this call that explicitly changes the behavior.
Unfortunately the lack of testing didn't help, but the problem got caught by https://github.com/paritytech/substrate-connect/runs/5590927994?check_suite_focus=true
=> Don't remove source knows block after verification

bin/rococo.json
The demo broke after https://github.com/paritytech/smoldot/pull/2175 because Rococo's ID didn't match the value in the parachain anymore
=> Fix Rococo's chain ID

bin/light-base/src/sync_service/standalone.rs
Avoids reporting the finalized block twice, and clarifies the use of two variables.
=> Some tweaks to finality block reports in the sync_service

bin/light-base/src/sync_service/parachain.rs, bin/wasm-node/CHANGELOG.md
Fix #2088 again
Fix #2147 as well
This is a fix of https://github.com/paritytech/smoldot/pull/2106, which was the previous attempt at fixing #2088 
What https://github.com/paritytech/smoldot/pull/2106 didn't do is check whether the block to report is equal to the finalized block.
What happens is:
- When the parachain sync service initializes, it starts to fetch the parahead corresponding the latest relay chain finalized block and to fetch the parahead corresponding to each relay chain non-finalized block
- The fetch of the relay chain finalized block succeeds, and we report this block. We not only reports it as new block but also as finalized.
- The fetch of one of the relay chain non-finalized blocks succeeds, and the code that this PR modifies runs. But because the code before this PR …
=> Fix #2088 again

Cargo.lock, Cargo.toml
This is an oversight, and might reduce the Wasm binary size.
=> Add default-features=false to parity-scale-codec

bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/worker/bindings-smoldot-light.ts, bin/wasm-node/rust/src/bindings.rs
Yet another surprise factor from JavaScript:
- https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value
- https://nodejs.org/api/timers.html#settimeoutcallback-delay-args
=> Cap the maximum value passed to setTimeout

bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service/parachain.rs, src/chain/async_tree.rs
In https://github.com/paritytech/smoldot/pull/2180 we're now creating a temporary `AsyncTree` that is dropped immediately after.
This is a bit wasteful, so this PR makes the capacity to reserve explicit. After https://github.com/paritytech/smoldot/pull/2180 is merged, I'll update this PR to pass `blocks_capacity: 0` at that location.
=> Add async_tree::Config::blocks_capacity

bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/demo/demo.js, bin/wasm-node/rust/src/cpu_rate_limiter.rs
Correctly implements https://github.com/paritytech/smoldot/pull/2151
The code currently does `u32::max_value().checked_sub(rate_limit)`. This is wrong, it should be `checked_div`.
I remember that when I was testing https://github.com/paritytech/smoldot/pull/2151 I was doing `u32::max_value() / rate_limit`, and then at the last second before opening the PR I replaced this with the `checked_` function in order to handle the situation where `rate_limit` is 0.
In addition to fixing this mistake, I've also changed the code to use floating points instead of integers.
Right now the precision is actually very low: because we round the division to the nearest integer, the possible values for the CPU bound can only be 100%, 50%, 25%, 12.5%, etc. Using floating points fixes this.
=> Correctly implement the cpuRateLimit feature

bin/light-base/src/json_rpc_service/state_chain.rs, bin/light-base/src/runtime_service.rs
The function doesn't need to take `&mut self`.
Also changes the error type. The error right now is only used to be turned into a string and sent back as a JSON-RPC error in case the runtime is invalid.
=> Tweak runtime_service::RuntimeLock::specification

bin/light-base/src/runtime_service.rs, bin/wasm-node/CHANGELOG.md
This is https://github.com/paritytech/smoldot/pull/2201 again
This time I've made sure that `when_known` was indeed notified before every time we do `lock.tree = ...`.
=> Properly fix the regression again

bin/full-node/src/cli.rs, bin/full-node/src/run.rs, bin/light-base/src/lib.rs, bin/wasm-node/CHANGELOG.md, src/chain_spec.rs
Close https://github.com/paritytech/smoldot/issues/2204
We no longer panic when the chain spec contains an invalid bootnode address.
As I've commented in the code, it is not possible to be sure that a bootnode address is actually invalid. We can only be sure that smoldot cannot parse it, but that's not the same as saying that it's invalid.
For this reason, invalid bootnode addresses are simply ignored in the light client.
=> Do not panic when passed an invalid bootnode address

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service/parachain.rs, bin/light-base/src/transactions_service.rs, bin/wasm-node/CHANGELOG.md
Fix https://github.com/paritytech/smoldot/issues/1920
This PR tweaks the calls to `RuntimeService::subscribe_all` to pass `usize::max_value()` for the maximum number of pinned blocks in situations where it is appropriate.
As a second minor change, this PR also adjusts all the buffer sizes to 32 in these situations.
The runtime service has a mechanism of "pinned blocks".
When the runtime service reports a new block, this block stays pinned in the memory of the runtime service and must later be unpinned. While a block is pinned, one can start runtime calls against this block.
The same logic of pinned blocks exists in the publicly-exposed JSON-RPC API. When a JSON-RPC client subscribes to blocks, these blocks stay pinned to guarantee that the client can access information about them, and …
=> Ignore the maximum number of pinned blocks when irrelevant

bin/light-base/src/json_rpc_service.rs
In situations where there are many JSON-RPC requests queued up, the JSON-RPC service will currently process them all in a row without giving the chance to other tasks to do some work.
This PR changes that by yielding between each request.
Note that since there's a maximum number of requests that can be queued up, and that while the node is busy no new request can be queued up (new requests are queued up by pulling from a queue, which can't happen if we don't yield), this is not a way to DoS the node.
What this PR does is merely make sure that the tasks are properly interleaved and that the node can't "freeze" for long periods of time.
=> Yield between each request in the JSON-RPC service

bin/light-base/src/network_service.rs, bin/light-base/src/sync_service/standalone.rs, bin/wasm-node/CHANGELOG.md
Close https://github.com/paritytech/smoldot/issues/2157
Changes are very similar to https://github.com/paritytech/smoldot/pull/2143
=> Make light clients gossip block announces to each other

.github/workflows/ci-post-workflow.yml
Reverts paritytech/smoldot#2227
The updates to this action breaks the workflow.
=> Revert "Bump actions/github-script from 3.1.0 to 6.0.0"

src/trie/calculate_root.rs, src/trie/node_value.rs
This is purely a mistake. All the documentation already says "Merkle value".
=> Rename wrongly-named function

bin/light-base/src/lib.rs, bin/light-base/src/runtime_service.rs, bin/wasm-node/CHANGELOG.md, src/author/runtime/tests.rs, src/chain_spec.rs, src/executor/host.rs, src/executor/runtime_host.rs, src/header.rs, src/lib.rs, src/trie.rs, src/trie/calculate_root.rs, src/trie/node_value.rs, src/trie/prefix_proof.rs, src/trie/proof_node_decode.rs, src/trie/proof_verify.rs
cc https://github.com/paritytech/smoldot/issues/1967
The first version of trie is called version 0. In version 1 of the trie, values that are longer than 32 bytes are hashed. Additionally, the header of each trie element has some additional bit patterns that indicate whether the value is hashed or not.
In order to know whether to use v0 or v1 of the trie, the runtime spec (found in the runtime) has an additional field called `state_version` (which was already parsed by smoldot since https://github.com/paritytech/smoldot/pull/1971 but ignored) indicating the version.
For this reason, it is no longer appropriate to have a standalone `calculate_genesis_block_header` function. Calculating the genesis block header requires knowing information from the genesis runtime, and building the genesis …
=> Implement trie version 1

bin/full-node/src/run/consensus_service.rs, bin/full-node/src/run/network_service.rs, bin/light-base/src/network_service.rs, bin/light-base/src/sync_service.rs, bin/light-base/src/sync_service/standalone.rs, src/libp2p/peers.rs, src/network/service.rs
Fix https://github.com/paritytech/smoldot/issues/2295
After https://github.com/paritytech/smoldot/pull/2264, we now panic if starting a request on a peer we're not connected to because this is an invalid usage of the API.
The reason why this wouldn't panic before is because there was always a chance of a race condition where a connection started being closed in parallel of the request being started.
We simply do the check for connectivity in the network service, as it is now possible to do so.
=> Make sure we're connected before starting requests

src/network/service.rs
Before https://github.com/paritytech/smoldot/pull/2264, we were maintaining an additional redundant list of connections in `service.rs` in order to avoid having to lock a mutex.
After the big refactor, this redundant list is no longer needed as we can directly access the list in the underlying data structure.
=> Remove redundant field in service.rs

src/chain/chain_information.rs
The TODO refers to something that is already done. See lines 379-381 and 395-399.
=> Remove obsolete TODO in chain_information

src/header.rs, src/util.rs
Fixes a TODO in `header.rs`
Can be reviewed commit by commit
=> Decode the block number directly into a `u64` into of going through a `usize`

src/libp2p/connection/noise.rs
This is similar to https://github.com/paritytech/smoldot/pull/2321, but since it's only a `debug_assert!` it's not a big deal.
=> Fix a debug assertion in Noise handshake when expected_len == 0

src/libp2p/collection.rs, src/libp2p/connection/established.rs
When sending an outgoing ping, we're supposed to send a random payload. Before this PR, this payload was hardcoded to `[0xff; 32]`. This fixes it.
=> Use proper randomness for outgoing pings

bin/wasm-node/CHANGELOG.md, src/libp2p/connection/noise.rs
The value in `expected_len` is read from an incoming networking packet. The networking packet is invalid if `expected_len < 16`, however it is unwise to do `expected_len - 16` as a malicious peer might send an invalid value on purpose.
Rust only detects underflow errors in debug mode. However, in release mode this will lead to a very high value being passed to `resize`, which will lead to an allocation error.
This bug is technically a vulnerability, as anyone can crash a smoldot light client if it connects to their node. However, since we're not widely used at the moment and that an attacker has nothing to gain except being a nuisance, I'm going to assume that nobody is going to exploit this and skip the non-disclosure period.
=> Fix a panic if Noise frame length is too low

src/network/protocol/identify.rs, src/network/service.rs
Removes usage of `Cow` in favor of slices and owned data.
=> Make API of protocol/identify less weird

src/executor/host.rs
This warning started appearing with Rust 1.61 I believe
=> Fix warning in host.rs

.github/workflows/ci.yml
The caching still doesn't work, this time because of the Rust compiler changing version every day.
=> Pin the nightly version in fuzzing-binaries-compile

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/wasm-node/CHANGELOG.md, src/json_rpc/methods.rs
cc https://github.com/paritytech/substrate-connect/issues/1096
=> Add support for state_call JSON-RPC function

src/network/service.rs
This was true because it was possible to call the two mentioned methods simultaneously, which is no longer possible.
=> Remove obsolete comment in service.rs

bin/wasm-node/CHANGELOG.md, src/libp2p/peers.rs
Fix https://github.com/paritytech/smoldot/issues/2361
This PR solves a tricky problem in `peers.rs`.
A connection can be in three phases: handshaking, established, or shutting down (and, later, completely shut down, but that doesn't count as a phase because when the connection is shut down it no longer exists).
Once a connection starts its shutdown phase, it is forbidden to start new requests on this connection, but incoming notifications can still arrive.
This is not a problem in `connection.rs` because we simply indicate when a connection starts shutting down, and the upper layers of the code are aware of the fact that they shouldn't start any new request but can still receiving incoming notifications.
But in `peers.rs` this is problematic, because `peers.rs` groups together multiple …
=> Add fake out requests system in peers.rs

src/libp2p/multiaddr.rs
cc @mxinden if you're interested
cc https://github.com/paritytech/smoldot/issues/1712
The payload of `/certhash` isn't documented in https://github.com/libp2p/specs/pull/412.
I suspect that ultimately people will want to make `/certhash` super generic and future-proof and over-engineered and all (in case in the vague future it might eventually be used for something else, even though we all know that this will likely never happen), but for now I went with a fixed 32 bytes payload that is hexadecimal-encoded without the `0x` prefix. The certificate hash is put as hexadecimal in the SDP packet, so an hexadecimal payload will make it a bit easier to debug if things work.
This is all marked as `experimental-` until we finish implementing it, so that there's no possible confusion with versions …
=> Add experimental WebRTC support to multiaddr

.github/workflows/ci.yml, .github/workflows/deploy.yml, bin/wasm-node/javascript/prepare.js
I've encountered a very annoying bug with incremental compilation on Rust 1.60 where you get very weird compilation errors that go away if you do a `cargo clean`. Upgrading to Rust 1.61 seems to fix it.
=> Update Rust to v1.61

bin/light-base/src/runtime_service.rs, bin/wasm-node/CHANGELOG.md
Fixes a panic introduced in https://github.com/paritytech/smoldot/pull/2373
Imagine the following situation:
Block A has two children: block B and block C. The latest finalized block is currently block A. All three blocks are pinned.
Now, imagine that block B gets finalized. Block A, B, and C all stay pinned. The number of pinned blocks remaining is decreased by 1.
When the user then unpins block C, we check `height(block_C) <= height(current_finalized_block)`, which returns `true`, and we add 1 to the number of pinned blocks remaining.
When the user then unpins block A, the same happens, and we add 1 again to the number of pinned blocks remaining.
This leads to an overflow when that number of pinned blocks is `usize::max_value()`.
This PR fixes this problem by tracking in `pinned_blocks` …
=> Fix panic with unpinning pruned blocks

bin/full-node/src/run.rs
In the full node, whenever we receive a block announce, we update the value of the `network_known_best` variable that contains the number of the best block seen on the network.
When we connect to a peer, this peer announces what its best block is.
This PR makes it so we also update the value of this variable whenever we connect to a peer.
=> Use block in handshake to initialize network_known_best

bin/light-base/src/lib.rs, bin/wasm-node/CHANGELOG.md
At a chain initialization, we provide a chain spec and, generally, an existing database. The chain spec can contain a checkpoint where we start syncing from.
Before this PR, the database always took precedence. This means that if database contains block 10 but the chain spec contains block 50000, we'll start syncing at block 10.
After this PR, the database is ignored if its block is below the checkpoint's.
This is especially important in situations where some sudo operation happened on a chain which breaks the warp syncing, like it happened on Rococo a week ago. Basically, smoldot is incapable of syncing over the blocks that force-change the list of validators. Before this PR, even if we ship a more recent checkpoint to bypass this issue, users would still use their database and be stuck …
=> Only use database if it's more recent than checkpoint

bin/full-node/src/run/consensus_service.rs, bin/full-node/src/run/network_service.rs, bin/light-base/src/network_service.rs, bin/light-base/src/sync_service/standalone.rs, bin/wasm-node/CHANGELOG.md, src/chain/blocks_tree/finality.rs, src/network/service.rs, src/sync/all.rs, src/sync/all_forks.rs, src/sync/all_forks/pending_blocks.rs, src/sync/all_forks/sources.rs
At the moment, when a chain is initialized, you will see messages saying "error while verifying grandpa commit message: commit targets a block not in the chain".
For context, a "Grandpa commit" is simply a proof of the finality of a block. It contains votes made by the validators.
What happens is: right after we have finished warp syncing to the current finalized block, a peer sends us a proof of finality. But the proof of finality targets a block that we haven't downloaded yet (as we've just finished warp syncing), and thus can't be verified.
In this context, the correct thing to do is instead to store the proof of finality and verify it later. This is what this PR does.
This however causes an issue, as sources could just send us hundreds of proofs of finality concerning unknown blocks. …
=> Properly save justifications and GrandPa commits for later

src/libp2p/collection/multi_stream.rs, src/libp2p/collection/single_stream.rs
Fixes the two `_ => todo!()` blocks.
I initially left them as `_ => todo!()` because I thought that these were only invalid states, and so didn't really need much caring.
However it turns out I forgot to handle the `(StartRequest, ShutdownWaitingAck)` combination (which, before this PR would panic, and after this PR does nothing), so it's a good thing that they are now explicitly laid out.
While this fixes a potential panic, I've never actually seen this panic happen and it might not actually be possible for it to happen, so I don't think it's worth mentioning in the CHANGELOG.
=> Fix missing match blocks in collection.rs

src/libp2p/multiaddr.rs
Removes one `Vec` allocation by directly returning the two iterators that we merge into one.
=> Optimize multiaddr::as_bytes a bit

bin/fuzz/Cargo.lock, bin/fuzz/Cargo.toml, bin/fuzz/fuzz_targets/fork-tree.rs
Close https://github.com/paritytech/smoldot/issues/1822
The fork tree has a history of having a lot of bugs that have been fixed over time.
In order to have a reasonably good confidence that there's no panic anymore, this PR adds a fuzzer.
The fuzzer randomly generates operations amongst all the possible mutable functions that the fork tree lets you perform, then applies them.
As of the opening of this PR, it panics because of https://github.com/paritytech/smoldot/pull/2423, but if I manually apply the fix in #2423 then the panics disappear.
=> Adding a fork tree fuzzing code

bin/fuzz/fuzz_targets/protocol-storage-call-proof-response-decode.rs, src/network/protocol/storage_call_proof.rs, src/network/service.rs
Fix https://github.com/paritytech/smoldot/issues/2413
This fixes a bug introduced in https://github.com/paritytech/smoldot/pull/2406
It turns out that decoding call proofs or storage proofs is not exactly the same, as one "tag" byte diverges between the two.
No changelog entry is added, since this fixes a bug that was never in a released version.
=> Fix call proof responses not decoded properly

bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/README.md, bin/wasm-node/javascript/src/worker/spawn-browser-overwrite.js, bin/wasm-node/javascript/src/worker/spawn.js
Deno throws an exception if we call `new Worker` without `type: "module"`.
See the comments for more information.
cc @harrysolovay
=> Pass `type: "module"` to `new Worker()`

src/libp2p/collection.rs
This PR replaces the multiple boolean flags with an enum.
This enum clarifies which state is valid or not.
This PR also fixes some debug_assert!s panicking because there was an ambiguity as to the meaning of `shutting_down`, especially because there's another flag named `start_shutdown_called`.
Some parts of the code set it to true even if the shutdown was initiated locally, while other parts of the code assume it means "shutdown initiated remotely".
=> Improve connection state flags in collection.rs

src/header.rs
The DigestItem type in substrate has a other type:
```rust
pub enum DigestItemRef<'a> {
///...
/// Any 'non-system' digest item, opaque to the native code.
Other(&'a [u8]),
///...
}
```
This will be used for some chain based on substrate, and if use this digestitem, the smoldot will failed to sync blocks from it.
This PR fix this problem by add this type to DigestItem.
=> Add support for digest item other type

Cargo.lock, bin/light-base/src/lib.rs, bin/wasm-node/javascript/src/worker/bindings-smoldot-light.ts, bin/wasm-node/rust/Cargo.toml, bin/wasm-node/rust/src/bindings.rs, bin/wasm-node/rust/src/platform.rs
As promised, this PR refactors `platform.rs`.
Before this PR, we were allocating objects on the heap then turning the heap pointer into a `u32`. When the JS would call methods, we would convert the `u32` back into a heap pointer. This is a bit risky.
This PR completely removes this and tracks the networking state in two maps, one of connections and one of streams.
It also implements multi-stream connections, and adds a function that was missing in the bindings: `connection_stream_close`.
=> Refactor platform.rs

bin/light-base/src/json_rpc_service/state_chain.rs, bin/wasm-node/CHANGELOG.md
In the case of a relay chain, we simply cannot sync if the block headers are in a format that can't be decoded.
However, in the case of a parachain, it is actually possible to follow the chain without decoding headers.
In that situation, the JSON-RPC functions shouldn't panic.
=> No longer panic in the old subscription JSON-RPC functions if block can't be decoded

bin/light-base/src/network_service.rs, src/libp2p/collection.rs, src/libp2p/connection/established/substream.rs
At the moment, if a blocks request fails we print a warning log message saying that the peer is likely incompatible.
We do this even when it doesn't make sense (such as `EmptyResponse`, which simply indicates that the remote doesn't know the requested block), and we don't print it in some situations where it should make sense (for example protocol not supported).
This PR tweaks the condition under which we print the log message.
=> Adjust when log message about block request error is printed

bin/wasm-node/javascript/src/client.ts
As explained in the comment, `enableCurrentTask` adds a small overhead but provides additional useful information in crash reports. This PR enables it iff logging is enabled.
=> Tweak whether enableCurrentTask is enabled

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/light-base/src/json_rpc_service/state_chain/sub_utils.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service.rs, bin/light-base/src/sync_service/parachain.rs, bin/light-base/src/transactions_service.rs, bin/wasm-node/CHANGELOG.md, src/chain/async_tree.rs
This PR fixes a hole in the notifications sent by the syncing service and runtime service.
The problem is as follows:
- Let's say that that there's a new best relay chain block R1 containing parachain block P1. We report P1 as the new best parachain block.
- Then there's a new best relay chain block R2 containing parachain block P2. We report P2 as the new best parachain block.
- Then there's a new best relay chain block R3 containing parachain block P1.
Normally, we should report P1 as the new best parachain block.
However, it is at the moment not possible to do so. The only way to report a change in the best chain is either when a new block arrives or when a block gets finalized.
This PR therefore introduces a new event `BestBlockUpdated`, which gets generated specifically in this kind …
=> Add BestBlockChanged notif in sync and runtime services

bin/light-base/src/json_rpc_service/state_chain.rs, bin/wasm-node/CHANGELOG.md
Subscribing to `chain_subscribeAllHeads` opens a channel of notifications with the runtime service.
If this channel gets too full (i.e. more than 32 notifications in queue), the channel is force-closed.
This typically happens if the finalized block jumps more than 32 blocks at once, or if there are 32 new blocks in a short amount of time, because in that situation we will report one notification per finalized block or per new block.
In theory, the finalized block isn't supposed to jump more than 32 blocks at once and we're not supposed to get 32 new blocks at once. But this tends to happen for example if we lose Internet connectivity for a while then gain it back.
Unfortunately, when the channel is closed, `chain_subscribeAllHeads` will not reopen a new one, and no new block will ever be …
=> Fix chain_subscribeAllHeads not recreating the channel if it dies

src/executor/host.rs
This TODO makes it look like we don't verify signatures. However that's not true, and it's a bit more subtle. See the diff for an explanation.
=> Fix some TODO in ext_crypto_finish_batch_verify_version_1

bin/wasm-node/javascript/README.md
Fixes one mistake, as the `start` function isn't `async`.
=> Update the README of the NPM package

bin/light-base/src/network_service.rs, bin/wasm-node/CHANGELOG.md
People keep mentioning this warning about no peers, but there's actually nothing that can be done anyway, and thus no point in printing the warning.
=> Silence NoPeers discovery errors

bin/wasm-node/javascript/demo/demo.js
- Fixes the error codes provided when closing a connection. 400 is actually invalid. https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close#parameters
- Provide a better error message if the chain spec of the relay chain of a parachain can't be found.
=> Some fixes to the demo

bin/fuzz/fuzz_targets/grandpa-justification-parse.rs, bin/fuzz/fuzz_targets/protocol-grandpa-warp-sync-response-decode.rs, src/chain/blocks_tree/finality.rs, src/finality/grandpa/warp_sync.rs, src/finality/justification/decode.rs, src/finality/justification/verify.rs, src/network/protocol/grandpa.rs, src/network/protocol/grandpa_warp_sync.rs, src/network/service.rs, src/sync/all.rs, src/sync/warp_sync.rs
Fourth point of https://github.com/paritytech/smoldot/issues/2478
Properly parses justifications depending on the number of bytes in the block number.
=> Use block_number_bytes when decoding justifications

bin/wasm-node/javascript/src/client.ts, bin/wasm-node/javascript/test/misc.js
The idea behind this limit is to avoid crashing the client by sending a very large request that leads to out of memory.
Choosing a precise limit is a bit tricky, because there are for example some legitimate very large transactions.
This PR increases that limit and prints a warning.
=> Show error if request is too large

bin/wasm-node/javascript/package-lock.json, bin/wasm-node/javascript/package.json, bin/wasm-node/javascript/prepare.mjs, bin/wasm-node/javascript/src/instance/raw-instance.ts, bin/wasm-node/javascript/src/tiny-inflate/LICENSE, bin/wasm-node/javascript/src/tiny-inflate/README.md, bin/wasm-node/javascript/src/tiny-inflate/index.js
cc https://github.com/paritytech/smoldot/issues/2427 https://github.com/paritytech/smoldot/issues/1802
Removes the `pako` library and uses `tiny-inflate` instead.
The objective of this PR is to remove a dependency, again with the idea of publishing to Deno at some point.
For this reason, the code of `tiny-inflate` (MIT) is directly embedded in the source tree. It is only 376 lines of code.
The `tiny-inflate` claims to be 30% to 50% slower than `pako`.
However, some quick benchmarking on my machine has shown the opposite.
With `pako`, I get 86ms to 88ms for base64 decoding + inflating.
With `tiny-inflate`, I get 78ms to 79ms instead.
The difference might be explained by the fact that I now use "raw" deflate, without any zlib header, as it's the only thing that `tiny-inflate` supports.
=> Use tiny_inflate instead of pako

bin/full-node/src/run.rs, bin/full-node/src/run/consensus_service.rs, bin/full-node/src/run/network_service.rs, bin/light-base/src/lib.rs, bin/light-base/src/network_service.rs, bin/light-base/src/sync_service.rs, bin/light-base/src/sync_service/standalone.rs, bin/wasm-node/CHANGELOG.md, src/chain_spec.rs, src/chain_spec/structs.rs
cc https://github.com/paritytech/smoldot/issues/2478
The change is rather straight forward: we add a new optional `blockNumberBytes` field in the chain specs format and pass its value around. The value defaults to 4 if it's missing.
=> Add a `blockNumberBytes` field in chain specs

bin/wasm-node/javascript/src/index-browser.ts, bin/wasm-node/javascript/src/index-nodejs.ts, bin/wasm-node/javascript/src/instance/buffer.ts, bin/wasm-node/javascript/src/instance/raw-instance.ts
It turns out that the cause of https://github.com/paritytech/smoldot/issues/2523 was a bug in the base64 decoding code.
This PR replaces this code with something that seems to work.
=> Fix base64 decoding function

src/trie.rs
Removes the `Trie` data structure that was basically a wrapper around `BTreeMap<Vec<u8>, Vec<u8>>`.
In practice, you never store the entire trie as just a `BTreeMap<Vec<u8>, Vec<u8>>`.
The `trie` module instead provides many utilities to calculate trie-related stuff.
=> Remove `Trie` data structure

.github/workflows/deploy.yml
~~This PR is a work in progress. I'm pushing commits and seeing how the CI behaves.~~ Done
Close https://github.com/paritytech/smoldot/issues/2427
This new CI action grabs the package version from `package.json`, checks if a `light-js-deno-vX.Y.Z` tag exists. If not, creates a commit with the build artifacts for Deno and tags it.
=> Automatically publish Deno versions from CI

bin/wasm-node/javascript/src/index-browser.ts, bin/wasm-node/javascript/src/index-deno.ts, bin/wasm-node/javascript/src/index-nodejs.ts, bin/wasm-node/javascript/src/instance/bindings-smoldot-light.ts
cc https://github.com/paritytech/smoldot/issues/1712
Adjusts the JS code that binds the `index-*` files to the Wasm VM that runs smoldot.
It now supports multi-stream connections.
=> Adjust JS API to support multi-stream connections

src/network/kademlia.rs, src/network/protocol.rs, src/network/protocol/kademlia.rs, src/network/service.rs
It's part of the protocol that the node uses, so let's move these functions to `protocol`.
=> Move Kademlia protocol functions to protocol module

README.md
The audience of our README might include less technical people, so I've moved the building steps to the bottom.
Additionally, less emphasis is put on the full node compared to before. We've thoroughly advertised the light client, and so seeing references to the full node is slightly confusing.
Can be reviewed commit by commit.
=> Various tweaks to the README

src/trie/trie_structure/tests.rs
After https://github.com/paritytech/smoldot/pull/2550, I looked around and saw this test. We only run it 16 times, and my machine takes 1ms to run all 16 times. So I increased the number of times, as it seems like a good idea.
=> Run the trie structure test more

src/util/leb128.rs, src/util/protobuf.rs
We now use a 64bits version of `nom_leb128` when decoding protobuf.
This ensures that 32bits targets (such as wasm, importantly) can parse u64 numbers encoded in protobuf messages.
=> Use nom_leb128_u64 when decoding protobuf numbers

bin/light-base/src/runtime_service.rs, src/chain_spec.rs, src/executor.rs, src/executor/host.rs, src/executor/host/embedded_runtime_spec.rs, src/executor/host/embedded_runtime_version.rs, src/executor/read_only_runtime_host.rs, src/executor/runtime_host.rs, src/transactions/validate.rs
Fix https://github.com/paritytech/smoldot/issues/1107
Rather than execute an expensive runtime call, it is possible to get this information from a custom Wasm section.
The objective of this PR isn't really the speed boost brought by reading the Wasm module, but the fact that we now have a `runtime_version() -> &CoreVersion` method on `HostVmPrototype`.
In other words, there is now a low-cost guaranteed way of knowing the version of a runtime.
This makes various other changes that require knowing the runtime version easier.
=> Backport runtime spec embedded in Wasm module

src/executor.rs, src/executor/host.rs, src/executor/host/embedded_runtime_version.rs
Fix https://github.com/paritytech/smoldot/issues/1107
This is an amendment to https://github.com/paritytech/smoldot/pull/2556
After asking on Element why the `apis` field was empty when obtaining the runtime version from the custom section, it has been pointed out that for some reason they're in a separate section named `runtime_apis`.
The APIs decoded from the `runtime_apis` section must then be inserted into the struct that was decoded from the `runtime_version` section.
It's very weird, and the person I talked to (@pepyakin) seems to agree that this is weird.
=> Also parse `runtime_apis` custom section

src/transactions/validate.rs
Should be merged after https://github.com/paritytech/smoldot/pull/2558
When I was doing https://github.com/paritytech/smoldot/pull/2556, I noticed that the `apis` field was now empty. The code that this PR modifies uses the `apis` field to determine how to perform the call. Therefore, in order to not break it, I was bypassing the cache and querying the version the old fashioned way.
Now that the `apis` field is now correct filled (https://github.com/paritytech/smoldot/pull/2558), we can use its value.
=> Use the cached runtime_version() when validating a transaction

bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/tsconfig-cjs.json, bin/wasm-node/javascript/tsconfig-mjs.json
Close https://github.com/paritytech/smoldot/issues/2564
=> Generate code for the ES6 target

src/libp2p/collection.rs, src/libp2p/collection/multi_stream.rs, src/libp2p/collection/single_stream.rs, src/network/service.rs
Ages ago, I added a dummy field called `fallback_protocol_names` that lets you specify a list of alternative protocol names that would be negotiated if the main one isn't supported by the remote.
Substrate has a similar feature, and it's very useful in order to do protocol upgrades. (e.g. https://github.com/paritytech/smoldot/pull/2116)
Unfortunately this has never been implemented.
Instead of leaving this dummy feature here, this PR just removes it. It can always be added back properly in the future.
=> Remove unused fallback protocol names system

bin/full-node/src/run/consensus_service.rs, src/sync/all.rs, src/sync/optimistic.rs
This is the continuation of something that I've started to do but haven't finished.
We now report the need to compile a runtime up to the highest level, so that the consensus service can measure how long it takes to compile a runtime.
=> Report RuntimeCompilation to the top-most level

src/sync/all.rs, src/sync/all_forks.rs
The `all_forks` syncing supports banned blocks, but we always pass an empty list at the moment.
I think that banned blocks should be implemented from the sync service instead.
=> Remove banned_blocks stub in all_forks

bin/wasm-node/CHANGELOG.md, src/sync/all.rs, src/sync/warp_sync.rs
Close https://github.com/paritytech/smoldot/issues/933
It currently only works for GrandPa+Babe.
This PR changes it to support Aura.
It is done simply by querying Aura-related parameters instead of Babe-related parameters.
=> Implement Aura+Grandpa warp syncing

bin/full-node/src/run/consensus_service.rs, bin/light-base/src/lib.rs, bin/wasm-node/CHANGELOG.md, src/chain_spec.rs, src/chain_spec/structs.rs
cc https://github.com/paritytech/smoldot/issues/2584
=> Print a warning in case of non-empty `badBlocks`

bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/demo/demo.mjs, bin/wasm-node/javascript/package-lock.json, bin/wasm-node/javascript/package.json, bin/wasm-node/javascript/src/index-browser.ts, bin/wasm-node/javascript/src/index-nodejs.ts, bin/wasm-node/javascript/tsconfig.json
Fix #2588 
The `websocket` package on NPM is just kind of fucked up, and it is impossible to make it work on both ModuleJS and CommonJS. This PR switches to `ws`, which works fine.
This was previously not possible because we were using the `websocket` library in the browser as well. This is no longer the case.
The biggest effort was updating the demo.
Additionally, I've made some tweaks to the `tsconfig.json` to disable some magic features. I removed them as a first attempt at understanding the issue. They turned out to be unrelated, but they're better left disabled anyway.
=> Replace `websocket` dependency with `ws`

src/libp2p/collection.rs
This is an overlook when implementing multi-stream connections.
They should be considered as immediately fully established.
Note that the logic of the upper layers already considers them as fully established, it's just the value we store in `collections.rs` that is wrong.
=> Fix multi-stream connections considered as handshaking

bin/wasm-node/javascript/src/index-nodejs.ts
Fix https://github.com/paritytech/smoldot/issues/2601
According to the w3c spec, handling error events is completely unnecessary as a `close` event will be generated anyway. The browser code is fine.
However, for some reason NodeJS seems to just stop the program if you emit an `error` event and that there's no event handler.
Why the previous WebSocket library never encountered this, I don't know to be honest, and I don't have the motivation to dig it up.
=> Properly set WebSocket.onerror in NodeJS

bin/wasm-node/CHANGELOG.md
I forgot to add a changelog entry to https://github.com/paritytech/smoldot/pull/2604
=> Fix missing entry in v0.6.29 changelog

src/libp2p/peers.rs, src/network/service.rs
Ongoing clean up work of the networking.
This PR renames `Connected` to `HandshakeFinished`. `Connected` was supposed to mean "there now exists a new connection with the given peer". But in practice we will need to precisely track connections, so this is the wrong approach.
Additionally, I've added a `expected_peer_id` field. Ultimately this will be reported to the outermost API layer.
=> Rename Peers::Connected -> HandshakeFinished and add field

src/libp2p/peers.rs, src/network/service.rs
Close https://github.com/paritytech/smoldot/issues/2370
This PR removes weirdnesses in the implementation of `peers.rs` by improving its API. There is now a `StartShutdown` event similar to `collection.rs`, after which it is invalid to start requests. After this event has been generated, all open substreams will be closed.
See https://github.com/paritytech/smoldot/pull/2369 for more context.
I _think_ I've preserved the same behavior in `service.rs` as before this PR, but I'm not completely sure of that. One exception is that we now properly clean up k-buckets when a connection was still handshaking is shut down.
I will improve `service.rs` as a follow-up to this PR.
=> Fix flaws in the API of peers.rs

bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/client.ts, bin/wasm-node/javascript/src/instance/instance.ts
cc https://github.com/paritytech/smoldot/issues/2613
=> Fix circular dependency between JS modules

src/network/service.rs
This PR clarifies the role and content of the `kbuckets` variable.
The list of addresses is now stored separately from the k-buckets, but keeps track of the list of peers in the k-buckets of all chains.
=> Revisit kbuckets variable in service.rs

bin/wasm-node/CHANGELOG.md, src/libp2p/peers.rs, src/network/service.rs, src/network/service/addresses.rs
Fix https://github.com/paritytech/smoldot/issues/2568
This PR makes sure that, when we discover a peer that we're already connected to, we insert the addresses we're connected to or connecting to.
=> Make sure connected addresses are inserted when discovering

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service/parachain.rs, bin/light-base/src/transactions_service.rs, bin/wasm-node/CHANGELOG.md
Fix https://github.com/paritytech/smoldot/issues/2190
See https://github.com/paritytech/smoldot/issues/2190 for all the context.
=> Make pinned_block_runtime_lock return an error on obsolete subscription

src/sync/all.rs, src/sync/warp_sync.rs
Moves the configuration from `warp_sync` to `all`, the objective being that `warp_sync` should move towards being stable.
=> Make warp sync build parameters configurable

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/json_rpc_service/getters.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/light-base/src/json_rpc_service/state_chain/sub_utils.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service/parachain.rs, bin/light-base/src/transactions_service.rs
Adds a name parameter when subscribing to the runtime service.
These names have been useful in the past in order to debug things locally, but I've never actually left them in the source code.
I think it makes sense to leave them.
Should make debugging https://github.com/paritytech/smoldot/issues/2617 easier the next time it happens
=> Add names to runtime service subscriptions

src/libp2p/peers.rs, src/network/service.rs
This PR improves the consistency of the list of addresses of peers.
We now properly take into account only addresses of outgoing connections, and handle situations where we dial an address and find a different peer than what was expected.
=> Do another pass to fix the consistency of `addresses`

src/libp2p/peers.rs
Fix https://github.com/paritytech/smoldot/issues/2619
Because we now include also connections that are shutting down, it is possible that a connection that is shutting down still has its notifications substream open. This `debug_assert!` is thus not accurate.
=> Remove faulty debug_assert

bin/wasm-node/javascript/src/index-browser.ts, bin/wasm-node/javascript/src/index-deno.ts, bin/wasm-node/javascript/src/index-nodejs.ts, bin/wasm-node/javascript/src/instance/raw-instance.ts
This function name is now a bit long, but I think it's important to convey that input is trusted.
=> Rename base64DecodeAndZlibInflate -> trustedBase64DecodeAndZlibInflate

src/finality/grandpa/warp_sync.rs
This was purely an overlook or a mistake. Maybe the non-partial decoding method was missing at the time. Anyway, there's no reason to use partial decoding here.
=> Use full decoding instead of partial in warp_sync verification

bin/light-base/src/lib.rs
At the moment, it sounds like the chain specification contains a list of blocks, and some of these blocks are bad, implying that the chain specification has a problem.
This PR clarifies the meaning.
=> Clarify message concerning unsupported bad blocks

Cargo.lock, bin/full-node/Cargo.toml, bin/full-node/src/run/network_service.rs, bin/full-node/src/run/network_service/websocket.rs
Close https://github.com/paritytech/smoldot/issues/2649
Adds support for multiaddresses of the form `.../ws`.
Note that WebSocket secure aren't supported in this PR.
=> Implement outgoing WebSocket connections in the full node

bin/light-base/src/sync_service/standalone.rs, src/network/service.rs, src/sync/all.rs, src/sync/all_forks.rs
When a commit message is received from the network, we now store it for later verification, as intended.
This should also fix issues where the sync service was reporting the same block as finalized multiple times.
=> No longer verify commit messages immediately

src/chain/blocks_tree.rs, src/chain/blocks_tree/finality.rs, src/chain/blocks_tree/verify.rs
This PR makes all the finality-related operations in the `BlocksTree` O(1).
Before this PR, we sometimes needed to traverse the tree of blocks in order to find an information concerning finality.
After this PR, this information is now stored in each block whenever it is inserted.
In order to not sure too much information, the list of authorities has been put in an `Arc`, meaning that it can be duplicated between all blocks that use the same list relatively cheaply.
I must admit that GrandPa is quite complicated, and I've re-read what I've done multiple times, to be sure to not mix scheduling block, triggering block, not have an off-by-one problem with scheduled changes, etc.
=> Add per-block finality info in blocks_tree

bin/wasm-node/CHANGELOG.md, src/chain/blocks_tree/verify.rs, src/verify/header_only.rs
Fixes a hole in the blocks tree. Right now if a block schedules a change while a change is already schedules, we end up panicking. This PR fixes this by checking overlaps of scheduled changes during block verification.
=> Deny blocks that schedule a change while a change is already scheduled

src/trie/trie_structure.rs, src/trie/trie_structure/tests.rs
cc my remark in https://github.com/paritytech/smoldot/pull/2663
The `descendants` and `all_nodes_ordered` functions were misimplemented, meaning that `structure_equal` would return `true` even when the structures were not necessarily equal.
I've also added a test, and this test indeed fails before the bugfix is applied.
=> Properly iterate over the trie structure

src/trie/calculate_root.rs, src/trie/trie_structure.rs, src/trie/trie_structure/tests.rs
Before this PR, whenever we want to clear all the nodes with a prefix, we simply clear the entire Merkle root calculation cache.
After this PR, we only clear from the cache the entries that have the given prefix.
The idea is to speed up blocks verification (and authorship).
Tests need to be written before merging.
Furthermore, I've discovered that the `descendants` function in this module doesn't look right at all, which would make tests pass more than they should. This should be investigated beforehand as well.
=> Implement TrieStructure::remove_prefix

bin/wasm-node/CHANGELOG.md, src/chain/blocks_tree/verify.rs, src/verify/header_only.rs
After discussion with the specs team, it turns out that blocks are valid even if they schedule a change while a change is already scheduled. In that case, the new scheduling is simply ignored.
=> Don't fail blocks validation after all if double scheduling

.github/workflows/ci.yml, Cargo.lock, bin/light-base/Cargo.toml, bin/light-base/examples/basic.rs, bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/json_rpc_service/getters.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/light-base/src/json_rpc_service/state_chain/sub_utils.rs, bin/light-base/src/json_rpc_service/transactions.rs, bin/light-base/src/lib.rs, bin/light-base/src/network_service.rs, bin/light-base/src/platform.rs, bin/light-base/src/platform/async_std.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service.rs, bin/light-base/src/sync_service/parachain.rs, bin/light-base/src/sync_service/standalone.rs, bin/light-base/src/transactions_service.rs, bin/wasm-node/rust/Cargo.toml, bin/wasm-node/rust/src/init.rs, bin/wasm-node/rust/src/lib.rs, bin/wasm-node/rust/src/platform.rs
Close https://github.com/paritytech/smoldot/issues/2671
Close https://github.com/paritytech/smoldot/issues/2542
This PR does the following:
- Move parameters provided to `Client::new` to a `ClientConfig` struct.
- Swap the two template parameters of `Client`.
- Make the `smoldot-light-base` properly no-std-friendly.
- Move the `Platform` trait in a separate module.
- Add a `std` feature to `smoldot-light-base` enabled by default.
- Add an implementation of the `Platform` trait based on `async-std`, gated behind the `std` feature. (see remarks below)
- Rename `smoldot-light-base` to `smoldot-light`.
- Add a lot of documentation.
Can be reviewed commit by commit.
The objective of this PR is to turn this library into a properly usable library that can be embedded in other Rust applications. …
=> Turn `smoldot-light-base` into a properly usable library

bin/light-base/src/lib.rs
The current comparison with `Vec` might be confusing, because when you remove an element from a `Vec`, the indices (the `usize`s) shift as well. This isn't the case with `ChainId`s.
=> Minor changes to smoldot-light documentation

bin/wasm-node/CHANGELOG.md, src/json_rpc/methods.rs
This fixes the issue described in #2685 however it doesn't properly solve it in a clean manner. A perfect solution would be to somehow retrieve the prefix length from the current chain and use that as the offset for the account id byte array.
=> Make AccountId deserialization accept prefixes larger than 1 byte

bin/full-node/src/run/network_service.rs, bin/light-base/src/platform/async_std.rs, src/libp2p/websocket.rs
Right now, on the client side, we pass `Host: ...` in the HTTP headers.
While libp2p itself doesn't care about the value in the `Host` header, many nodes that use WebSocket have an HTTP reverse proxy in front of them. This reverse proxy does care about this value, and it is thus important to pass it properly.
=> Provide a Host in the WebSocket handshake

bin/light-base/src/platform/async_std.rs
We can prove at compile time that these blocks are unreachable by using an empty match block.
=> Small tweak to unreachable code

bin/light-base/src/runtime_service.rs
https://github.com/paritytech/smoldot/pull/2658 removed the code that sometimes erroneously sent a `Notification::Finalized` about a block that was already finalized. As such, we can remove the hack in `runtime_service` that checks for this.
=> Remove hack that checks for duplicate finality

bin/light-base/src/platform/async_std.rs
When reading or writing returns `Poll::Ready`, it is important that we try reading/writing again until `Pending` is returned, so that the `Context` is properly registered.
=> Properly poll the socket in a loop

bin/light-base/src/sync_service/parachain.rs, bin/wasm-node/CHANGELOG.md
Calling `relay_chain_sync.subscribe_all(...).await` might take a long time (as it waits for the runtime of the chain to have been downloaded), during which messages coming from the public API of the sync service just pile up and aren't answered.
This PR fixes this by answering messages while we wait for the subscription to happen.
The consequence is that a parachain initialization now finishes quickly, while before it was waiting for its relay chain initialization to finish.
It also means that we now properly clean up parachains if we remove them, even if their relay chain never downloads its runtime. Before, the clean up didn't happen because the clean up never happens before initialization is complete.
I'm not really happy with the code duplication here, and would perform a refactoring …
=> Process incoming foreground messages while subscribing

src/trie/trie_structure/tests.rs
Adds some tests regarding the code added in https://github.com/paritytech/smoldot/pull/2663
I wanted to maybe figure out why https://github.com/paritytech/smoldot/pull/2666 was failing, but didn't manage to find a failing case.
=> Add some tests for remove_prefix

bin/light-base/examples/basic.rs, bin/light-base/src/lib.rs, bin/wasm-node/rust/src/init.rs, bin/wasm-node/rust/src/lib.rs
Adding a chain can fail. If adding a chain fails, we need to report the reason for the failure to the user.
Unfortunately, it is rather difficult to pass a string from Rust to JavaScript. The best way to do so is for the JavaScript to call a Rust function that returns a pointer to said string.
And that's exactly what we do if chain initialization fails. If adding a chain fails, we still insert a chain but insert it in "erroneous" mode. When a chain is in erroneous mode, the error message is kept in memory and can be retrieved by the JavaScript. Once retrieved, the JavaScript calls another function that cleans up the chain.
Before this PR, this system was done in the `light-base` library.
Unfortunately, this leads to a rather weird API for the client. It is much more idiomatic if …
=> Move erronous chain system to wasm-node code

bin/wasm-node/CHANGELOG.md, src/libp2p/collection/multi_stream.rs, src/libp2p/collection/single_stream.rs, src/libp2p/connection/established.rs, src/libp2p/connection/established/single_stream.rs, src/libp2p/connection/yamux.rs
This PR is a general clean-up of the single stream connection code. It fixes many small issues, and also handles the shutdown phase more properly.
We now properly handle incoming GoAway frames, and have the possibility to send some.
Can be reviewed commit by commit.
I understand that this code is generally extremely complicated, but I don't really have a good solution for this. Networking code *is* extremely complicated, both in terms of logic and implementation.
Maybe a solution is tests, such as https://github.com/paritytech/smoldot/pull/2323, but at the moment the code isn't even robust enough to have tests.
=> General clean-up of the single stream connections code

bin/light-base/src/network_service.rs, bin/wasm-node/CHANGELOG.md, src/libp2p/peers.rs, src/network/service.rs
Fix #2680 
The code in `network_service` was wrong and was attempting to send a transaction to every peer we have a connection with, instead of every peer we have opened a transactions notifications substream with.
=> Only send transactions to peers with open substream

Cargo.lock, Cargo.toml, bin/full-node/Cargo.toml, bin/light-base/Cargo.toml, bin/wasm-node/rust/Cargo.toml
Releasing a new version of `smoldot-light` after the latest API changes.
I believe that the current API is now not bad and stable-ish for now. Changes to the `Platform` trait might happen again, but not in the very short term.
=> Bump smoldot to 0.4.0 and smoldot-light to 0.2.0

Cargo.lock, Cargo.toml, src/libp2p/multiaddr.rs
Update for https://github.com/multiformats/multiaddr/pull/130 and https://github.com/multiformats/multiaddr/pull/131
Even though I disagree with these protocols, I guess the way forward is to conform.
=> Update the experimental multiaddr WebRTC support

bin/fuzz/fuzz_targets/network-connection-encrypted.rs, bin/fuzz/fuzz_targets/network-connection-raw.rs, bin/wasm-node/CHANGELOG.md, src/libp2p/collection.rs, src/libp2p/collection/multi_stream.rs, src/libp2p/collection/single_stream.rs, src/libp2p/connection/established.rs, src/libp2p/connection/established/multi_stream.rs, src/libp2p/connection/established/single_stream.rs, src/libp2p/connection/yamux.rs, src/libp2p/peers.rs, src/network/service.rs
In order to avoid DoS attacks, it is important to prevent remotes from opening an unlimited number of substreams.
=> Add a limit to the number of inbound substreams

bin/light-base/src/sync_service/parachain.rs
This PR refactors the parachains service to make it easier to read and understand.
No change to the logic has been performed.
Can be reviewed commit by commit. I've intentionally done `rustfmt`almost at the end in order to not pollute the diff.
=> Refactor parachains service

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/wasm-node/CHANGELOG.md
Fix https://github.com/paritytech/smoldot/issues/2468
This PR does two things:
- Split `runtime_call` in half, where the first half is now a separate function named `runtime_lock`.
- Make `state_get_runtime_version` use this new `runtime_lock` function.
This is better so that we don't repeat a lot of code, and also fixes a few potential panics.
=> Rewrite `state_get_runtime_version` to use shared code

bin/light-base/src/sync_service/parachain.rs
Checks that the logic of the `async_tree` code is correct and that it finalized blocks one after the other.
=> Add debug_assert! in parachain code

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/lib.rs, bin/wasm-node/CHANGELOG.md, src/json_rpc/methods.rs
cc https://github.com/paritytech/smoldot/issues/2456
See the issue description for more context.
=> Add a chainHead_unstable_finalizedDatabase JSON-RPC method

bin/light-base/src/network_service/tasks.rs, bin/light-base/src/platform.rs, bin/wasm-node/javascript/src/instance/bindings-smoldot-light.ts, bin/wasm-node/javascript/src/instance/bindings.ts, bin/wasm-node/rust/src/bindings.rs, bin/wasm-node/rust/src/platform.rs, src/libp2p/collection.rs, src/libp2p/collection/multi_stream.rs, src/libp2p/connection/noise.rs, src/libp2p/peers.rs, src/network/service.rs
cc https://github.com/paritytech/smoldot/issues/2754
In terms of API, this removes the necessity to pass a `PeerId` when creating a "multi-stream connection". The inner implementation now performs the substream opening and Noise negotiation internally.
=> Perform the multi-stream connections handshake inside smoldot

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/wasm-node/CHANGELOG.md
Fix https://github.com/paritytech/smoldot/issues/2763
This PR gives a proper error type to the `state_trie_root_hash` function (which retrieves the state trie root hash of a block from the network), and makes `runtime_lock` properly propagates the error instead of unwrapping.
=> Remove unwrap() in runtime_lock

Cargo.lock, bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/package-lock.json, bin/wasm-node/javascript/package.json, bin/wasm-node/rust/Cargo.toml
I've taken the liberty to change the order of the sections in the CHANGELOG by order of importance: first "added", then "changed", then "fixed". Because of merge conflicts I ended up putting them in an awkward order.
=> Publish v0.6.34

src/libp2p/connection/yamux.rs
Fixes a TODO in the Yamux code.
This change has absolutely no influence, as `StreamReset` events are simply ignored by the higher level code, but in principle higher level code could use it.
=> Make Yamux return an event on stream reset

bin/wasm-node/javascript/demo/demo-deno.ts
I had to look at the source code of Deno because the doc is [non-existent](https://deno.land/api@v1.25.4?s=Deno.HttpConn#method_nextRequest_0).
When `null` is returned, it means the connection can no longer serve requests, and so if we `continue` we just get an infinite loop.
=> Fix Deno demo

bin/light-base/src/runtime_service.rs, bin/wasm-node/CHANGELOG.md
Fix https://github.com/paritytech/smoldot/issues/2467
We now clean up old runtimes when it makes sense, rather than after a download where it doesn't make sense.
=> Clean-up runtimes management in runtime_service

bin/light-base/src/lib.rs, bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/client.ts, bin/wasm-node/javascript/src/instance/bindings-smoldot-light.ts, bin/wasm-node/javascript/src/instance/bindings.ts, bin/wasm-node/javascript/src/instance/instance.ts, bin/wasm-node/javascript/src/instance/raw-instance.ts, bin/wasm-node/rust/src/bindings.rs, bin/wasm-node/rust/src/init.rs, bin/wasm-node/rust/src/lib.rs
Close https://github.com/paritytech/smoldot/issues/2456
This PR removes the `Chain.databaseContent` function from the public API. Users are supposed to use the `chainHead_unstable_finalizedDatabase` JSON-RPC function that was added in https://github.com/paritytech/smoldot/pull/2749 instead.
This is an API breaking change. Since https://github.com/paritytech/smoldot/pull/2778 has been merged and is a breaking change, let's do other breaking changes at the same time.
=> Remove Chain.databaseContent function

bin/wasm-node/CHANGELOG.md
I expected this change to `rpc_methods` to land in a minor version, but it ended up landing in a major version. Thus the sentence in the CHANGELOG is now incorrect. This PR removes it.
=> Remove weird sentence from CHANGELOG

src/network/protocol/block_request.rs
Substrate can in principle send requests with `0` maximum blocks. This is meant to mean "no limit".
I've discovered this mismatch while investigating https://github.com/paritytech/smoldot/issues/2833, however this is not the same issue as https://github.com/paritytech/smoldot/issues/2833.
=> Interpret 0 maximum block as no maximum

src/libp2p/connection/yamux.rs
At the moment, if we receive a header with `fin: true` and `length: 0`, we do a state transition to `Incoming::DataFrame`. Then, when we loop again, we will generate a `StreamClosed` event. This is all correct.
Unfortunately, the loop condition is `while !data.is_empty()`, meaning that if no more data comes we will never generate the `StreamClosed` event.
I've changed it to `loop`.
Additionally, I've cleaned up the handling of `DataFrame` and `Window` headers, so that it is a bit more elegant.
This PR also fixes an API inconsistency: right now a substream can be considered as dead even before we have generated the `StreamClosed` event for it. Since we now transition the substream to "dead" right before generating the event, there's no weirdness anymore.
=> Fix Yamux not picking up events if no data is coming

bin/wasm-node/CHANGELOG.md, src/libp2p/collection/multi_stream.rs, src/libp2p/collection/single_stream.rs, src/libp2p/connection/established/single_stream.rs, src/libp2p/connection/established/substream.rs, src/libp2p/read_write.rs
Fix #2831 
The problem turned out to be very stupid:
Calling `close_write()` is just a shortcut for `outgoing_buffer = None`.
So you're supposed to call `close_write()` when you have nothing more to write.
The problem is that we're calling `write_from_vec_deque(data)`, which transfers data from `data` to `outgoing_buffer`. Then we realize that `data` is empty (because it's been entirely copied to `outgoing_buffer`), and call `close_write()`. This sets `outgoing_buffer` to `None` and thus erases the data that we've just copied.
Instead, we now call `close_write` at the next iteration (when the data will have been extracted out), which is what you're supposed to do.
Additionally, as a safety measure, I've replaced `close_write` with `close_write_if_empty`. I think that `close_write` is too …
=> Fix close_write() being called too eagerly

.github/workflows/deploy.yml
It seems that the checkout action does a ton of dark magic which is useful when later you want to `git push` again.
See https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
=> Remove persist-credentials: false when checking out

.github/workflows/deploy.yml
https://github.com/paritytech/smoldot/pull/2855 wasn't actually working because the `actions/checkout` configures only the local git repository.
This PR does it hopefully better.
=> Stay in the same repository in docs-publish to benefit from the actions/checkout

.github/workflows/deploy.yml
cc https://github.com/paritytech/smoldot/issues/2856
It's amazing. The CI tests everything during a PR except a single line (`git push`, for obvious reasons), yet this single line causes tons of problems.
=> Fix directory where git push is run

src/libp2p/connection/established/single_stream.rs, src/libp2p/connection/yamux.rs
At the moment, when a substream is closed gracefully, the code in `established::single_stream` just assumes that the substream state machine will return zero or one event then shut down.
While this is true in practice, this is a pretty big breach of abstraction layers. The state machine could in principle decide to return two events. Nothing in the API prevents it from doing so. And if it does, before this PR the second event would be ignored.
This PR splits the dead substreams handling of the yamux code in two: first we iterate over dead substreams, then only we remove them. Thanks to this, we can choose to not remove a dead substream for now, and instead continue processing it at the next iteration. In the example above, this would make it possible for the dead substream to send its …
=> Properly process dead substreams

bin/light-base/src/network_service.rs, src/libp2p/peers.rs, src/network/service.rs
Doesn't warrant a CHANGELOG entry because this relates to the full node only.
=> Fix panic when sending block announces to disconnected peers

.github/workflows/ci.yml
It turns out that it wasn't installed, completely skewing the results.
I've also removed `cmake`, which was still there from before we switched to our own protobuf codec, thereby fixing a TODO.
=> Add wasm-opt when checking wasm node size diff

.github/workflows/ci.yml, .github/workflows/deploy.yml, bin/light-base/src/lib.rs, bin/light-base/src/util.rs, bin/wasm-node/javascript/prepare.mjs, src/executor/vm/jit.rs, src/libp2p/async_std_connection/with_buffers.rs, src/network/service.rs, src/sync/optimistic/verification_queue.rs
https://github.com/paritytech/smoldot/pull/2881 currently fails CI because it uses a function that wasn't stable yet in Rust 1.61.
While I could bypass the issue, it makes sense to just update the Rust version.
=> Update Rust version to v1.64

bin/wasm-node/javascript/prepare.mjs
When building the Wasm file to embed in the browser, and `--release` is provided, we try to run `wasm-opt` on it.
If `--debug` is provided, we don't do it.
Because we used to do it with `--debug` as well, there exists a fallback if `wasm-opt` isn't installed that will simply not run `wasm-opt`.
This PR removes this fallback, so that the release build fails if `wasm-opt` isn't installed. `--debug` will still work even if it's not installed.
=> Fail if wasm-opt isn't installed when passing `--release`

src/executor/host.rs, src/executor/read_only_runtime_host.rs, src/executor/runtime_host.rs
Instead of turning things immediately into a string, we instead put the values provided to the host function into the `LogEmit` struct, and do the formatting and turning into string later.
This unlocks a potential future change where the API user can format the runtime logs the way they want.
=> Reduce the allocations when emitting logs

bin/light-base/src/network_service/tasks.rs, src/libp2p/collection/multi_stream.rs, src/libp2p/connection/established/multi_stream.rs
Right now the state machine of a multi-stream (i.e. WebRTC) connection has a function returning a list of substreams that have data ready to be written out.
The objective of this function is simply to allow optimizing the code that effectively reads/writes, in order to not try to read/write for nothing.
However this function is currently not properly implemented.
One way to easily implement it better would be to iterate over all substreams and check which ones are ready. But this is pointless, because the code that effectively reads/writes can already do that by trying to read each one one by one.
The best way to implement this function would require a lot of changes in the lower level substream code, which are quite complicated and I don't have the motivation to make right now.
This PR …
=> Remove concept of ready substreams from multi_stream code

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/network_service.rs, bin/light-base/src/network_service/tasks.rs, bin/light-base/src/sync_service.rs, bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/index-browser.ts, src/libp2p/collection/multi_stream.rs, src/libp2p/connection/established/multi_stream.rs, src/network/protocol/storage_call_proof.rs, src/network/service.rs, src/util/protobuf.rs
cc https://github.com/libp2p/specs/pull/412
cc https://github.com/paritytech/smoldot/issues/1712
This PR finishes implementing the WebRTC spec by adding the last remaining item: the messages framing.
Implementing this messages framing while minimizing the amount of data copies is rather challenging.
Instead of going for the complicated solution, I went for the more easy solution of having an intermediate read buffer where data is first copied.
Going for the simple solution decreases the chances of bugs and increases the ease of debugging, so it's preferable at the moment.
In the future, once WebRTC is fully working, we can rewrite this messages framing code in a more optimized way.
=> Implement WebRTC messages framing

src/libp2p/peers.rs
The `Peers` state machine has two functions: `unfulfilled_desired_outbound_substreams` and `fulfilled_undesired_outbound_substreams`. They return a list of peer-substreams tuples.
These two functions are called very frequently (every time something happens on the networking), they are `O(n)` (they iterate over every single substream of every single peer), and most of the time they return nothing.
This PR adds two new fields to the `peers` state machine with the same names as these functions.
The functions now simply return the content of the field, and the field is updated pro-actively whenever something else changes.
=> Add two caches to the `peers` state machine

bin/wasm-node/javascript/src/index-browser.ts
In the `dataChannel.onmessage` callback, we expect the data to be an `ArrayBuffer`.
However, in order for that to be the case, one has to set the value of `binarytype`. See https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/binaryType.
The documentation says that the default is `blob`. The fact that Chrome is providing me with an `ArrayBuffer` seems to be a bug: https://bugs.chromium.org/p/webrtc/issues/detail?id=2276
=> Fix WebRTC for Firefox

src/libp2p/peers.rs
Right now the `derive_more` library just prints the value of `notifications_protocol_index` (an integer) when displaying this error, which is kind of crappy.
=> Missing custom Display implementation on error

bin/wasm-node/javascript/src/index-browser.ts
The comment concerning `m=application` at the bottom says that we tweak the local offer. This isn't true anymore, but I think it's a good idea to make sure that the local offer does contain a UDP + data channel entry.
Tested on Firefox and Chrome. Firefox somehow doesn't work anymore (ugh) but this PR doesn't actually modify any behavior, so it can't be related.
=> Verify that SDP offer contains UDP

bin/light-base/src/json_rpc_service.rs
cc https://github.com/paritytech/smoldot/issues/2804
Most legacy JSON-RPC functions can't be implemented properly by smoldot.
The situation kind of sucks, as the new JSON-RPC functions aren't stable and aren't implemented in Substrate yet.
However, the fact that the replacement isn't ready yet doesn't remove the fact that the old ones don't work properly. Therefore I think it's appropriate to print this warning.
The main reason why I'd like to print this warning is to raise awareness to anyone reading the logs of the fact that things might not work properly, and that it's not necessarily smoldot's fault but usually the API's fault.
=> Print a warning if a legacy JSON-RPC function is used

bin/light-base/src/network_service/tasks.rs, bin/light-base/src/platform.rs, src/libp2p/collection.rs, src/libp2p/collection/multi_stream.rs, src/libp2p/connection/established/multi_stream.rs
WebRTC has a few assumptions, most notably the fact that the reading and writing side of substreams must never close (in other words: the browser can't control the individual closing of the reading and writing, so the code within smoldot expects them to remain always open).
Since this is a property of WebRTC specifically and not of multi-stream connections in general, I've opted to keeping an API that allows closing the reading/writing and simply documenting that this is not allowed.
An alternative could have been for the internals of smoldot to accept in its API that the reading/writing was closed, and if that actually happens consider this as a protocol violation and reset the substream. I've however opted to not do that because of the "external" nature of multi-stream connections. The …
=> Make a few WebRTC-related assumptions more explicit

.github/workflows/ci.yml
Our spellcheck CI job has started failing yesterday because compiling `clang-sys` can't find LLVM installed on the system.
I was curious why this suddenly happened. Unfortunately, we were caching the compiled version of `cargo-spellcheck`, and suddenly the cache expired, which means that we're now compiling it whereas we weren't compiling it before. I don't really have the motivation to find the CI run where we initially compiled it in order to compare it with the failing CI run, and even if I found it the logs are probably expired now.
A quick investigation of the cargo-spellcheck and clang-sys packages don't reveal anything abnormal.
=> Install clang before the spellcheck

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/json_rpc_service/getters.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/light-base/src/lib.rs, bin/wasm-node/CHANGELOG.md
Close https://github.com/paritytech/smoldot/issues/476
=> Add the genesis hash to the database

bin/light-base/src/network_service/tasks.rs, bin/light-base/src/platform.rs, bin/light-base/src/platform/async_std.rs, bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/index-browser.ts, bin/wasm-node/javascript/src/index-deno.ts, bin/wasm-node/javascript/src/index-nodejs.ts, bin/wasm-node/javascript/src/instance/bindings-smoldot-light.ts, bin/wasm-node/javascript/src/instance/bindings.ts, bin/wasm-node/rust/src/bindings.rs, bin/wasm-node/rust/src/platform.rs, src/libp2p/collection/single_stream.rs
At the moment, the `read_buffer` function of the `Platform` trait (representing how the light client binds to the environment) returns either `Some` in normal situations or `None` if the connection has been either closed or reset.
This PR turns this `Option` into an enum with three variants: `Open`, `Closed`, and `Reset`.
This lets the code properly differentiate between these two latter situations.
Additionally, I've renamed "closed" to "reset" in the entire Wasm<->JS code (all the functions and variables), for clarity. While the `Platform` trait lets you report that the reading side is closed but the writing side still open, the JS code can't represent that state. Instead, it's either "connection open" or "connection reset".
This PR fixes …
=> Clarify platform reading API

bin/light-base/src/platform.rs, bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/index-browser.ts, bin/wasm-node/javascript/src/instance/bindings-smoldot-light.ts, bin/wasm-node/rust/src/bindings.rs
Fix https://github.com/paritytech/smoldot/issues/2900
In order to open outbound substreams on a WebRTC connection, the mechanism that the API of smoldot uses is as follows: one function to ask the implementation to open a substream, and one callback that is later called in order to notify that a substream has been fully opened.
The API of smoldot doesn't provide a way to report that opening an outbound substream has failed. This is because this isn't really supposed to happen. If you have a connection, opening a substream is purely a "local side change": you allocate an ID, then send a message. It should maybe not even be asynchronous, but that's off-topic here.
The problem here is that this mental model doesn't really fit what the browser does. In particular, the browser does nothing …
=> Properly handle data channel opening failures

bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/index-deno.ts
Fix https://github.com/paritytech/smoldot/issues/2937
=> Fix panic on Deno when WebSocket abruptly closes

bin/light-base/src/sync_service.rs, bin/wasm-node/CHANGELOG.md, src/trie/prefix_proof.rs, src/trie/proof_verify.rs
Fix https://github.com/paritytech/smoldot/issues/2946
The behavior of `prefix_proof` is currently buggy. When a node isn't found in the proof that the remote sent us, we simply discard it instead of adding it to the list of keys to query at the next iteration.
The consequence is that `state_getKeysPaged` was wrong most the time.
In order to fix this, I had to reorganize the entire function.
There's still an issue because we're asking for too much data, which leads the remote to shutdown the connection, so queries still occasionally fail. But this other issue is not the fault of the `prefix_proof` module, and this PR is only about fixing `prefix_proof`.
=> Fix prefix_proof misbehavior

bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/index-browser.ts
Seeing the small discussion in the WebRTC implementation PR, I realized that smoldot doesn't actually say what is in the spec now. This PR changes it.
=> Set the ufrag/pwd according to the spec

bin/light-base/src/network_service.rs, bin/light-base/src/sync_service/standalone.rs, src/network/protocol/grandpa_warp_sync.rs, src/network/service.rs, src/sync/warp_sync.rs
We no longer copy the fragments when decoding a response sent by a peer, but return the message as a whole. This avoids copies.
Unfortunately, we have to do `to_vec()` at some point, so this doesn't actually save anything. However this is still progress towards a final zero-cost version.
=> Make Grandpa warp sync protocol code more zero cost

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/sync_service/parachain.rs, bin/wasm-node/CHANGELOG.md, src/chain/chain_information/build.rs, src/executor/host.rs, src/executor/read_only_runtime_host.rs, src/executor/runtime_host.rs, src/transactions/validate.rs, src/verify/header_body.rs
cc @xlc 
After looking at https://github.com/paritytech/smoldot/pull/2952, I thought that the approach in this PR is a better idea.
As shown in the changes to `runtime_host.rs` and `read_only_runtime_host.rs`, you now have a new variant called `SignatureVerification` that allows you to overwrite the verification if you so desire.
As I was implemented this PR, I noticed that the implementation of `ext_crypto_ecdsa_verify` loads the message from the first parameter, which is actually the signature. Oops. This is fixed at the same time.
=> Make signature verification customizable in the host module

src/libp2p/connection/noise.rs, src/network/protocol/block_request.rs, src/network/protocol/kademlia.rs, src/network/protocol/state_request.rs, src/network/protocol/storage_call_proof.rs, src/util/protobuf.rs
Whether a field is required or optional when decoding protobuf can be a bit tricky. I wrote a small paragraph about this and made it mandatory to specify `#[required]` instead of it being the default.
=> Make it mandatory to specify `#[required]`

bin/full-node/src/run/consensus_service.rs, bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/sync_service/parachain.rs, bin/light-base/src/transactions_service.rs, src/author/build.rs, src/author/runtime.rs, src/author/runtime/tests.rs, src/chain/blocks_tree/verify.rs, src/chain/chain_information/build.rs, src/chain_spec.rs, src/executor/read_only_runtime_host.rs, src/executor/runtime_host.rs, src/sync/all.rs, src/sync/optimistic.rs, src/sync/warp_sync.rs, src/transactions/validate.rs, src/verify/header_body.rs
When the executor wants to obtain the value at a certain storage location, it provides us with a `StorageGet` object. This object has a `key()` function that returns the key to query.
Currently, this function returns an `impl Iterator<Item = impl AsRef<[u8]>>`, and the actual key consists in the concatenation of all the elements returned by the iterator.
In order to be more convenient to use, there's also a `key_as_vec()` function that returns a `Vec<u8>` with the key.
This iterator thing is a micro-optimization that only comes useful at a single place where we return a list of bytes instead of collecting them into a `Vec`.
However, the iterator is actually never really usable, and every use of this API uses `key_as_vec()`, which completely kills the point of this micro-optimization.
It's …
=> Remove key_as_vec() functions

bin/wasm-node/javascript/src/index-browser.ts
Fixes two problems:
- `error.toString()` returns `[object Event]`
- Because `+` has higher precedence than `?:`, JS was seeing `("..." + error) ? (" " + error.toString()) : ""`, leading to ` [object  Event]` being printed
=> Fix error message on WebRTC failure

src/network/protocol/state_request.rs, src/network/service.rs, src/util/protobuf.rs
At the moment, the state_request protocol code in smoldot uses the "no proof" version of the protocol. This turns out to be completely useless in practice. The "no proof" version is supposed to be used only if the node you query is trusted, which is in practice never the case.
This PR changes that to use the "with proof" version of the protocol, and adds proper documentation to it.
=> Change the state_request protocol to use the proof version

bin/light-base/src/sync_service/parachain.rs, bin/wasm-node/CHANGELOG.md
When we subscribe to parachain blocks, the subscription confirmation contains the list of all blocks that already exist. This list of blocks needs to be ordered from parent to child, and the field is actually named `non_finalized_blocks_ancestry_order` ("ancestry order") in order for everyone to get the memo.
Unfortunately, the author of the parachains code (me) didn't get the memo, and the parachain blocks aren't properly ordered.
This leads to a panic in `runtime_service.rs` because it assumes that the ordering is correct.
=> Fix wrong order of parachain blocks at initialization

.github/workflows/ci.yml, .github/workflows/deploy.yml, bin/full-node/src/cli.rs, bin/full-node/src/run/network_service.rs, bin/light-base/src/network_service.rs, bin/light-base/src/platform.rs, bin/light-base/src/platform/async_std.rs, bin/light-base/src/runtime_service.rs, bin/wasm-node/javascript/prepare.mjs, bin/wasm-node/rust/src/platform.rs
Updates to Rust 1.65. As usual, the CI will fail because the official Rust Docker image generally takes a day or two to be updated when a new Rust version comes out.
This PR introduces GATs in the `Platform` trait.
At the moment, if you call `Platform::next_substream` or `Platform::next_substream`, you obtain a `Future` that is completely disconnected from the object representing the connection or the stream. This means that you can for example drop the connection or stream object while the `Future` is still alive, or you can call this function multiple times with the same connection/stream.
Using GATs allows us to bind the `Future` to the object it refers to, and thus removes these annoying corner cases. This should also make the trait implementation much easier to write, but I'm not …
=> Update to Rust v1.65 and use its new features

bin/light-base/src/platform.rs, bin/wasm-node/rust/src/platform.rs
Fix https://github.com/paritytech/smoldot/issues/2970
The browser can reset a WebRTC connection at any time. When that happens, smoldot only switches the connection state to "reset", and it's only later that the connection task will query the state and see that it's reset.
However, in the meanwhile, the connection task can try to open a new substream. This PR clarifies the behavior when that happens: trying to open a new substream should simply be ignored.
=> Don't call connection_stream_open if WebRTC connection has been reset

.github/workflows/ci.yml
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> Switch CI to NodeJS v16

bin/full-node/src/run/network_service.rs, bin/light-base/src/network_service.rs, src/network/service.rs
Basic refactor to make the code less annoying to read.
We take 5 similar enum variants and merge them into one.
=> Split the service request responses enum into two

bin/light-base/src/database.rs, bin/light-base/src/json_rpc_service/chain_head.rs, bin/light-base/src/lib.rs
=> Extract database encoding/decoding to a separate module

src/libp2p/collection.rs, src/libp2p/collection/multi_stream.rs, src/libp2p/peers.rs, src/network/service.rs
They're unused in practice, but there's no reason to not allow ingoing multi-stream connections in the underlying state machine.
cc https://github.com/paritytech/smoldot/issues/2802
=> Add functions for incoming multi-stream connections

bin/wasm-node/CHANGELOG.md, src/libp2p/connection/established/substream.rs, src/libp2p/connection/multistream_select.rs, src/libp2p/connection/single_stream_handshake.rs
cc https://github.com/paritytech/smoldot/issues/2983
This PR removes some extra networking round-trips caused by multistream-select.
The way multistream-select works is: we tell the remote that we would like to use a specific protocol, and then the remote answers either yes or no. No is only ever returned if the remote doesn't support the protocol at all, which isn't supposed to happen unless we're talking to a buggy node or to a libp2p-compatible-but-not-Substrate node.
Before this PR, we wait for the remote to send back yes or no. After this PR, we don't wait and simply start sending the protocol-specific data immediately after the request for a protocol, and assume that the remote is going to answer yes.
The negotiation is still properly finished afterwards, so if it turns out that the …
=> Remove some multistream-select round-trips

bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/client.ts, bin/wasm-node/javascript/src/index-browser.ts
Let's wait a bit to see if there's an answer [to this comment](https://github.com/libp2p/specs/pull/412#issuecomment-1305454720) before merging this.
=> Enable WebRTC by default

bin/full-node/src/run.rs, bin/light-base/src/lib.rs, src/author/runtime/tests.rs, src/chain_spec.rs
The "chain information building process" is done in two steps: fetching all the info, then validating that the values are coherent together.
In the past, the `chain_spec` module used to do only the first step, leaving the second step to the API user of this module. Then I've changed the implementation to produce a `ValidChainInformation` and turn it back into an (not-validated) `ChainInformation`.
This PR changes the return type to `ValidChainInformation`, and thus the API user doesn't need to handle that.
=> Return a ValidChainInformation when building the chain spec info

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/json_rpc_service/state_chain.rs, bin/wasm-node/CHANGELOG.md, src/json_rpc/payment_info.rs
Fix https://github.com/paritytech/smoldot/issues/2974
cc https://github.com/paritytech/smoldot/issues/949
This PR modifies `runtime_call` to support an "API version constraint". This constraint is then verified.
A `runtime_call_no_api_check` function has also been added as an escape hatch for the `state_call` JSON-RPC function.
It also updates the `payment_info` module to account for https://github.com/paritytech/substrate/pull/12633
=> Check runtime API versions in the JSON-RPC layer

bin/light-base/src/json_rpc_service.rs, bin/light-base/src/platform.rs, bin/light-base/src/platform/async_std.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service/standalone.rs, bin/light-base/src/util.rs, bin/wasm-node/CHANGELOG.md, bin/wasm-node/javascript/src/client.ts, bin/wasm-node/javascript/src/index-browser.ts, bin/wasm-node/javascript/src/index-deno.ts, bin/wasm-node/javascript/src/index-nodejs.ts, bin/wasm-node/javascript/src/instance/bindings.ts, bin/wasm-node/javascript/src/instance/instance.ts, bin/wasm-node/javascript/src/instance/raw-instance.ts, bin/wasm-node/rust/src/bindings.rs, bin/wasm-node/rust/src/init.rs, bin/wasm-node/rust/src/lib.rs, bin/wasm-node/rust/src/platform.rs
Close https://github.com/paritytech/smoldot/issues/2996
This PR does many things:
- Remove the `crate::util::yield_twice` function in favor of a platform-specific function `TPlat::yield_after_cpu_intensive`. This way, the implementation of the yielding, which is a bit hacky due to the requirements of the Wasm node, is specific to the Wasm node.
- Refactor the `nextJsonRpcResponse` function and the `jsonRpcResponsesNonEmptyCallback` callback. Right now, when we wait for a JSON-RPC response to come, we wait for smoldot to notify that it has a response available. But because this notification is done through a callback, we can't immediately query the content of the response, so instead we use `setTimeout(..., 0)` to register a task that queries the content of the response and then notify the …
=> Refactor the execution to avoid setTimeout

src/libp2p/collection.rs, src/network/service.rs, src/network/service/notifications.rs, src/network/service/requests_responses.rs
Extracts everything related to request-responses in a module, and everything related to notifications in another module.
This considerably cleans up the code of `service.rs`.
No logic has been altered.
=> Clean up service.rs by extracting code to child modules

bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service.rs, bin/wasm-node/CHANGELOG.md, src/network/protocol/storage_call_proof.rs, src/network/service/requests_responses.rs
Fix https://github.com/paritytech/smoldot/issues/2975
Backports https://github.com/paritytech/substrate/pull/8046
See also https://github.com/paritytech/substrate/pull/12732
=> Backport changes about the light client protocol

bin/light-base/src/network_service.rs, bin/light-base/src/runtime_service.rs, bin/light-base/src/sync_service.rs, bin/light-base/src/sync_service/standalone.rs, src/network/protocol/storage_call_proof.rs, src/network/service/requests_responses.rs, src/sync/all.rs, src/sync/warp_sync.rs, src/trie/prefix_proof.rs, src/trie/proof_decode.rs
This PR modifies the way Merkle proofs are passed around in the source code.
Before this PR, the networking code turns the networking response into a `Vec<Vec<u8>>`, which is then passed around smoldot. The inner `Vec<u8>` are still encoded, which means that the networking code decodes the proof a bit but not completely, which is kind of weird.
After this PR, the networking code returns the completely undecoded proof, and the decoding is now entirely done in the `proof_decode` module.
This should make everything easier to understand.
=> Modify Merkle proofs to be a single Vec

bin/light-base/src/network_service/tasks.rs, src/network/service.rs
Close https://github.com/paritytech/smoldot/issues/1531
cc https://github.com/paritytech/smoldot/issues/2746
This PR renames `is_unreachable` to `is_bad_address`.
It is generally not possible to know whether an address is definitely unreachable or not. The only situation where we can affirm that an address is definitely unreachable is if our implementation doesn't support a certain protocol that it uses.
This matches what the browser node already does anyway.
=> Clarify meaning of is_unreachable

src/trie/proof_decode.rs
Fix https://github.com/paritytech/smoldot/issues/3032
=> Make empty Merkle proofs valid

src/trie.rs, src/trie/proof_encode.rs, src/trie/trie_structure.rs
I went for an API where the user provides already-existing node values in order to encode the proof. I went for this, as the main point of building a proof is to extract information from the trie, and when doing that you normally already know node values.
I also think that this API is very easy to understand compared to other APIs that I could have gone for.
=> Implement encoding Merkle proofs

src/trie/proof_decode.rs
No CHANGELOG entry, as https://github.com/paritytech/smoldot/pull/3034 hasn't been released yet.
=> Fix trie_node_info when the proof is empty

bin/light-base/src/sync_service/standalone.rs, bin/wasm-node/CHANGELOG.md, src/sync/all.rs, src/sync/warp_sync.rs
Fix https://github.com/paritytech/smoldot/issues/3015
We now properly report the block of the fragments which we've downloaded, as opposed to the block whose chain information we have.
=> Fix wrong Grandpa warp sync block being reported

src/trie/proof_encode.rs
Right now, if we put in the proof builder a node whose value is of length < 32, it gets put in the proof twice: once within its parent, and once separately.
This PR fixes it by skipping nodes that are too small and that aren't the root.
=> Properly inline nodes that are too small when building a proof

bin/wasm-node/CHANGELOG.md, src/trie/proof_decode.rs
Right now, we either hash each proof entry or take its inline value if it is too small.
This isn't correct, for two reasons:
- The root node is always hashed, meaning that right now if the root node of a proof is < 32 bytes, its hash won't be found in our array.
- Nodes that are < 32 bytes should be inlined. There's no situation where a node whose length is < 32 bytes has its own proof entry.
Consequently, we don't care about inline values and just hash the node entries.
We also check whether hashed nodes shouldn't have been inlined, although this is very secondary.
=> Fix Merkle proof whose trie root node is inferior to 32 bytes being considered as invalid

bin/full-node/src/run/network_service.rs
The wrong check was being done, because the `can_send_block_announces` function didn't exist until recently.
=> Fix wrong check in network_service

src/network/service/notifications.rs
Provides more clarity about the problem if `queue_notification` panics.
=> Add debug_assertions whenever calling queue_notification

.github/workflows/ci.yml, README.md
Closes: https://github.com/paritytech/smoldot/issues/3097
Is that okay @tomaka?
=> Inform users about the new repo
