paritytech/smoldot

.github/dependabot.yml

Add back dependabot

---

Cargo.lock
Cargo.toml
bin/full-node/main.rs

Use atty instead of isatty

---

Cargo.lock
Cargo.toml
src/chain_spec/light_sync_state.rs
src/chain_spec/structs.rs

Fixes the parsing of the Kusama and Westend chain specs.

Fix chain specs parsing and remove impl_serde

---

src/verify/execute_block.rs

It happens for Kusama, so let's fix this TODO.
The reason why I put a `TODO` here in the first place is I considered redefining locally the error types. That seems however very overkill.

Properly report execution errors

---

src/chain/blocks_tree.rs
src/chain/chain_information/babe.rs
src/verify/babe.rs

Change BabeGenesisConfiguration to have public fields instead of getters

---

Cargo.lock
Cargo.toml

These two dependencies are unused.

Remove async-tls and webpki

---

src/executor/externals.rs

Syncing Polkadot panics at the moment because this function isn't implemented.

Implement ext_crypto_secp256k1_ecdsa_recover_compressed_version_1

---

bin/wasm-node/rust/src/lib.rs

Use the light sync state in the light client

---

bin/wasm-node/rust/src/lib.rs
src/json_rpc/methods.rs

This finally makes the PolkadotJS UI work somehow.

Some RPC work

---

bin/json-rpc-test/main.rs
bin/wasm-node/rust/src/ffi.rs
bin/wasm-node/rust/src/lib.rs
src/json_rpc/methods.rs

This are as many changes as can be done before having to implement storage proofs requests.

More work on light JSON-RPC server 

---

.github/workflows/ci.yml

Remove dependency between CI steps

---

src/chain/blocks_tree.rs
src/chain/blocks_tree/finality.rs
src/chain/chain_information.rs
src/database/finalized_serialize/defs.rs
src/database/full_sled.rs
src/database/full_sled/open.rs
src/verify/header_only.rs

Add a new finality engine called Outsourced

---

bin/wasm-node/rust/src/network_service.rs
src/network/protocol.rs
src/network/service.rs

Implement storage proof requests

---

bin/full-node/src/main.rs
bin/full-node/src/sync_service.rs
src/chain/blocks_tree/verify.rs
src/chain/sync/optimistic.rs

Print a warning in logs instead of crashing.

Make sync problems more graceful

---

src/finality/justification/verify.rs

Check that justifications don't contain duplicate signatures, and that there are at least 2/3rds of the authorities.
These checks are actually quite critical, and it was clearly a flaw to not have them.

Better justification verification

---

src/network/libp2p.rs

cc @rakanalh 
Untested, but should work.

Add libp2p::Network::queue_notification

---

bin/full-node/src/main.rs
bin/full-node/src/network_service.rs
bin/full-node/src/network_service/with_buffers.rs
src/chain/blocks_tree.rs
src/chain/sync/optimistic.rs
src/network/connection/established.rs
src/network/connection/yamux.rs
src/network/libp2p.rs

I'm intentionally keeping legitimate warnings, but fixing the others.

Fix many warnings

---

src/libp2p.rs

I asked Jeff, and it's not a problem

Remove a TODO in libp2p.rs

---

src/network/protocol/block_announces.rs
src/network/service.rs

After this PR, we now also open a Grandpa notifications substream.
Will be necessary in order to listen to Grandpa messages.

Add Grandpa gossiping stub

---

src/finality/justification/decode.rs
src/network/protocol.rs
src/network/protocol/grandpa.rs
src/network/service.rs

Adds the definitions of all the Grandpa notifications messages.

Add definitions of GrandPa notifications

---

src/finality/justification/verify.rs

The threshold of number of signatures required was one by off.
Thanks to @andresilva

Fix a justification verification error

---

src/libp2p.rs
src/libp2p/peerset.rs
src/network/service.rs

cc #288 
I've clarified how the implementation is supposed to work, and made the appropriate changes.
It's still not fully finished, but it's considerable progress.

Considerably clean up src/libp2p.rs

---

bin/wasm-node/rust/src/lib.rs

Proper error reporting in storage_query

---

bin/wasm-node/javascript/package.json

Normally the CI is supposed to auto-publish new versions, but it doesn't work, so I'm publishing it manually.

smoldot v0.1.1 on npm

---

bin/wasm-node/javascript/.npmignore

I just accidentally published a Westend database on npm :see_no_evil:

Do not publish demo database

---

src/trie/proof_verify.rs

Fix #382 
A trie node value contains the Merkle value of its children. A Merkle value is either a hash, or, if it is smaller than 32 bytes, the node value itself.
In the case where it is a hash, the unhashed value is found in the Merkle proof.
If it is not a hash, the current code expects the child to be found as a separate entry in the Merkle proof. However this isn't the case. The unhashed value must be used directly to continue iterating down the trie.
cc @raoulmillais

Fix proof verification when trie nodes < 32 bytes

---

bin/full-node/src/network_service.rs
bin/wasm-node/rust/src/network_service.rs

Don't create dummy timers anymore

---

src/chain/sync/optimistic.rs

Fix optimistic sync stalling

---

bin/wasm-node/rust/src/lib.rs

Pass back the correct runtime specs

---

src/chain/chain_information.rs
src/chain/chain_information/babe_fetch_epoch.rs

Closes https://github.com/paritytech/smoldot/issues/330

Rename babe_current_epoch to babe_fetch_epoch and allow fetching either the current babe epoch or the next one.

---

bin/wasm-node/javascript/index.js
bin/wasm-node/rust/src/ffi/bindings.rs

Interesting safety property that I didn't think about.

Enfore proper panic safety in the JS

---

bin/wasm-node/rust/src/lib.rs
bin/wasm-node/rust/src/network_service.rs

If the connection was back-pressured, or if the reading side was closed, `websocket.read_buffer()` would be ready all the time, leading to a spin loop. This fixes it.
Also removes the usage of `futures::select!` in favour of `future::select`, which has the advantage of being rustfmt-friendly.

Clarify futures wake-ups and processing

---

bin/wasm-node/rust/src/json_rpc_service.rs
bin/wasm-node/rust/src/network_service.rs

Moves the logic from the JSON-RPC service to the network service.

Add NetworkService::storage_query

---

src/chain/sync/grandpa_warp_sync.rs
src/finality/grandpa/warp_sync.rs

We don't necessarily start the warp syncing at the genesis.

genesis_chain_information -> start_chain_information

---

bin/full-node/src/sync_service.rs
bin/wasm-node/rust/src/json_rpc_service.rs
src/author/build.rs
src/author/runtime.rs
src/author/runtime/tests.rs
src/chain/blocks_tree/verify.rs
src/chain/chain_information/aura_config.rs
src/chain/chain_information/babe_config.rs
src/chain/chain_information/babe_fetch_epoch.rs
src/chain/sync/grandpa_warp_sync.rs
src/chain/sync/optimistic.rs
src/executor.rs
src/executor/host.rs
src/executor/read_only_runtime_host.rs
src/executor/runtime_host.rs
src/executor/vm/interpreter.rs
src/finality/grandpa/chain_config.rs
src/metadata/query.rs
src/verify/execute_block.rs
src/verify/header_body.rs

Unfinished. Need to update everything.

Directly return pointers to the virtual machine's memory, instead of copying the memory

---

bin/wasm-node/rust/src/json_rpc_service.rs
src/author/runtime/tests.rs
src/chain/chain_information/aura_config.rs
src/chain/chain_information/babe_config.rs
src/chain/sync/grandpa_warp_sync.rs
src/chain/sync/optimistic.rs
src/executor.rs
src/executor/host.rs
src/executor/vm.rs
src/executor/vm/interpreter.rs
src/executor/vm/jit.rs
src/finality/grandpa/chain_config.rs
src/metadata/query.rs
src/verify/header_body.rs

cc @expenses I'm slightly touching Grandpa warp sync

Introduce a HeapPages struct

---

bin/wasm-node/rust/src/sync_service.rs

Start network requests before verifying blocks

---

bin/wasm-node/rust/src/json_rpc_service.rs
bin/wasm-node/rust/src/network_service.rs

Silence unimportant storage query warnings

---

src/json_rpc/websocket_server/tests.rs
src/libp2p/connection/noise.rs
src/libp2p/peerset.rs

Apparently Rust 1.50 has some changes in rustfmt, and the CI already picks the new version.

Update style for rustfmt 1.50.0

---

src/metadata.rs
src/metadata/events.rs

This is a revisited version of #321. I gave up with decoding events.

Add a module to allow retrieving events list

---

src/chain/sync/all_forks.rs
src/chain/sync/all_forks/pending_blocks.rs
src/chain/sync/all_forks/sources.rs

Continuing work towards a clean and well-documented code

Some work on all-forks syncing

---

bin/wasm-node/rust/src/json_rpc_service.rs

The `state_getKeysPaged` RPC function was implemented by returning the values from the genesis block, which is clearly incorrect.
This PR removes support for this RPC function and removes this field.
cc https://github.com/paritytech/smoldot/issues/523

Remove genesis_storage field from json-rpc service

---

bin/wasm-node/rust/src/json_rpc_service.rs
src/metadata/query.rs

Allow accessing the storage when generating metadata

---

bin/wasm-node/rust/src/json_rpc_service.rs
bin/wasm-node/rust/src/lib.rs
bin/wasm-node/rust/src/network_service.rs
bin/wasm-node/rust/src/sync_service.rs
bin/wasm-node/rust/src/transactions_service.rs
src/network/service.rs

cc @rakanalh 
Making you aware of the changes in the transactions service.

Fix missing changes regarding multiple chains

---

src/chain/sync/all.rs

Properly store the `SourceId` exposed on the external API within the "all forks" state machine.
This reduces the complexity from `O(n)` to `O(1)` when answering a request.

Small user data change in all syncing

---

bin/wasm-node/rust/src/sync_service.rs
src/chain/sync/all.rs
src/chain/sync/grandpa_warp_sync.rs

This is some work towards integrating GrandPa warp sync with the "all syncing system".
I've added some methods the GrandPa warp sync state machine.
After this PR, we now try to do one request towards each node, then freeze forever because nobody is able to serve us.
(on that topic: I don't actually know whether we should add some sort of timeout, and switch to optimistic syncing afterwards, or if just freezing forever is fine because we assume that GrandPa warp sync is widely available)
I'll wait for GrandPa warp sync to be available to finish the integration.

Integrate GrandPa warp sync in the all-syncing

---

bin/wasm-node/javascript/index.js
bin/wasm-node/javascript/package.json
bin/wasm-node/javascript/tcp-browser.js
bin/wasm-node/javascript/tcp-nodejs.js
bin/wasm-node/rust/src/ffi.rs
bin/wasm-node/rust/src/ffi/bindings.rs
bin/wasm-node/rust/src/network_service.rs

Fix #219 
Work in progress. I'm having issues on the JS side.

Allow raw TCP connections from NodeJS

---

bin/wasm-node/javascript/index.js

I'm utterly confused as to how the previous PR worked at all.

Update Polkadot chain specs and fix wasm-nodeTCP connections

---

bin/full-node/src/sync_service.rs

Hack around #520
Extracted from #521

Add hack around deadlock in sync_service

---

bin/full-node/src/network_service.rs
bin/wasm-node/rust/src/network_service.rs
src/network/service.rs

Add ChainNetwork::set_local_grandpa_state

---

src/chain/sync/all_forks.rs

Trying to find the problem with https://github.com/paritytech/smoldot/pull/567

Add an assert! to check unimplemented thing not happening

---

Cargo.lock
Cargo.toml

Version 0.9.2 has been yanked for accidentally breaking semver.

Use schnorrkel v0.10.0

---

bin/wasm-node/javascript/package.json

No specific reason to publish a version now, but we haven't published one in ages.

Publish v0.1.13

---

bin/wasm-node/rust/src/network_service.rs
src/trie/prefix_proof.rs

Properly return an error if a proof fails

---

src/sync.rs
src/sync/para.rs

This module provides the toolkit necessary to sync parachains.
cc #221

Add a `sync::para` module

---

bin/wasm-node/rust/src/runtime_service.rs

cc #221 
In the case of parachains, we want to call `ParachainHost_persisted_validation_data`, but the state of the relay chain block might have been pruned already. In that case, don't panic but return an error.
This is a partial fix for hack, and this general code is waiting to be properly finished.

Don't unwrap if runtime call fails because block is pruned

---

bin/wasm-node/rust/src/network_service.rs

Add a work-around for #615

---

bin/wasm-node/rust/src/lib.rs
bin/wasm-node/rust/src/runtime_service.rs
bin/wasm-node/rust/src/sync_service.rs

This is a cleaner version of #549 
Only adds the necessary code without making actual use of the code.
Making use of the code requires more changes when it comes to initializing everything and to the database system.

Add support for syncing parachains

---

bin/full-node/src/network_service.rs

Equivalent of https://github.com/paritytech/smoldot/pull/617 but for the full node.
cc #615

Work-around deadlock in networking

---

src/executor/runtime_host.rs

Fix #626
Currently under testing.

Implement reverting storage transactions

---

.github/cargo-deny.toml
Cargo.lock
Cargo.toml
bin/full-node/Cargo.toml

Removes the last git dependencies.

Update wasmi and ban git dependencies

---

bin/wasm-node/javascript/bindings-smoldot-js.js
bin/wasm-node/javascript/bindings-wasi.js
bin/wasm-node/javascript/index.js

Extract smoldot-related bindings in bindings-smoldot-js

---

src/trie/calculate_root.rs

Fixes https://github.com/paritytech/smoldot/issues/629

Optimise calculate_root cache invalidation

---

bin/wasm-node/javascript/package.json

To merge after https://github.com/paritytech/smoldot/pull/655

Publish v0.1.14

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
Cargo.toml
bin/wasm-node/javascript/prepare.js
bin/wasm-node/rust/src/ffi.rs

~~I didn't set `resolver = "2"` just yet, because it causes build errors.~~ EDIT: done

Set 1.51.0 as the minimum Rust version

---

bin/wasm-node/rust/src/lib.rs

I reorganized `start_services` in order to make parachains work.
The code has three known flaws:
- We match relay chains and parachains by the chain identifier. This means that for example the `relay_chain` field in the Tick chain spec must contain a string, and that the `id` field in the Rococo spec must contain the exact same string. This isn't the case upstream right now: Rococo's id is `rococo_v1`, while Tick contains just `rococo`.
- The database saving task is spawned for the first relay chain in the list of chains. I'm leaning towards removing database altogether in the future (in favour of GrandPa warp sync), which is why I'm not really dealing with this problem. If we're not removing databases, we instead have to modify the FFI between the JS and Rust.
- The JSON-RPC task is …

Rework lib.rs to integrate parachains

---

bin/full-node/src/sync_service.rs

Removes a few seconds during which the UI erroneously shows that we're at block 0.

Proper SyncState initialization

---

bin/wasm-node/javascript/src/index.js

It turns out that after https://github.com/paritytech/smoldot/pull/671, errors in the worker weren't even reported anymore.
This fixes it by screaming out when something bad happens.

More properly handle errors from the worker 

---

src/database/full_sqlite/open.rs

Remove mentions of encoding of numbers in SQLite schema

---

src/database/full_sqlite/open.rs

Fix comment of two tables inverted

---

src/sync/all.rs
src/sync/all_forks.rs

Relates to #366 
In order to make finality with with the `all_forks` strategy, we actually need two mechanisms: GrandPa commit messages and justifications.
Importantly, GrandPa commit messages alone aren't sufficient because nodes don't send them to nodes that aren't in the same authority set id. With only GrandPa commit messages, the finality of a node could get stuck if it loses Internet connectivity at the wrong moment.
This means that even if we implement listening for GrandPa commit messages (#366), we still need to implement justifications.
This is partly what this PR does.

Make all_forks ask for justifications when doing ancestry searches

---

src/sync/all.rs

Enable GrandPa warp sync by default

---

src/finality/grandpa/warp_sync.rs
src/sync/grandpa_warp_sync.rs

Adjusts for https://github.com/paritytech/substrate/pull/8514
The last fragment no longer always contains a change in the authorities.

Adjust the code for the latest changes in GrandPa warp sync

---

bin/wasm-node/rust/src/sync_service.rs
src/sync/all.rs

Close https://github.com/paritytech/smoldot/issues/705
Prints a log message and notifies the finalization notification channel when GrandPa warp sync is finished.

Notify when GrandPa warp sync is finished

---

src/libp2p.rs
src/libp2p/peerset.rs
src/network/service.rs

Allow adding more overlay networks at runtime in peerset

---

bin/tick.json
bin/track.json
bin/trick.json

Accidentally broken after https://github.com/paritytech/smoldot/pull/741
Relates to https://github.com/paritytech/smoldot/issues/683

Fix relay chain ID in the parachain specs

---

src/chain/chain_information.rs
src/header/grandpa.rs

Extracted these changes from #514

Properly parse headers with GP forced changes

---

bin/wasm-node/rust/src/json_rpc_service.rs
src/json_rpc/methods.rs

Tweaks the `define_methods!` macro to allow parameters to JSON-RPC requests to be references (e.g. `&str` instead of `String`).
Also removes an intermediate decoding into `serde_json::Value`.
The objective is to reduce the overhead and memory consumption of the node.

More zero-cost JSON-RPC requests parsing

---

src/sync/grandpa_warp_sync.rs

Closes https://github.com/paritytech/smoldot/issues/769.

Add a `remove_source` function to `InProgressGrandpaWarpSync`

---

bin/full-node/src/sync_service.rs
src/sync/all.rs
src/sync/optimistic.rs

Instead of having `process_one` immediately verify a block, it returns a `Verify` object with a `start` method.
This bring it in line with the `all_forks` syncing and fixes a todo in `all.rs`.

Refactor optimistic syncing to add a step before verifying a block

---

bin/wasm-node/javascript/package.json

To merge after https://github.com/paritytech/smoldot/pull/795

Publish v0.1.26

---

bin/wasm-node/javascript/package.json

To merge after https://github.com/paritytech/smoldot/pull/820

Publish 0.1.27

---

bin/wasm-node/javascript/package.json

Bumping to 0.2.0 because of the breaking changes of https://github.com/paritytech/smoldot/pull/835

Publish v0.2.0

---

src/executor/host/zstd/tests.rs

Let's hope that the tests actually pass.

Err, zstd tests were disabled

---

src/lib.rs
src/transactions.rs
src/transactions/validate.rs
src/util.rs

Close #11
This PR is basically #11 but better and up to date.
Will be needed for https://github.com/paritytech/smoldot/issues/480

Add code that validates a transaction

---

src/executor.rs
src/executor/host.rs

Update for this sneaky consensus change https://github.com/paritytech/substrate/pull/8892
Let's wait for a few days before merging just in case it gets reverted or something.

Propagate change to default heap pages

---

bin/wasm-node/rust/src/json_rpc_service.rs
bin/wasm-node/rust/src/runtime_service.rs
src/json_rpc/methods.rs

Fix https://github.com/paritytech/smoldot/issues/841

Fix getRuntimeVersion having bad parameters

---

bin/wasm-node/javascript/package.json

To be merged on top of https://github.com/paritytech/smoldot/pull/869

Publish v0.2.1

---

src/libp2p.rs
src/libp2p/connection/established.rs

Nodes aren't supposed to open a second incoming substream when there already is one, but in some rare cases they seem to do anyway.
This PR fixes a panic when that happens.

Fix panic on second incoming substream

---

bin/wasm-node/javascript/src/bindings-smoldot-js.js
bin/wasm-node/rust/src/ffi.rs
bin/wasm-node/rust/src/ffi/bindings.rs
bin/wasm-node/rust/src/network_service.rs

Fix https://github.com/paritytech/smoldot/issues/450

Improve error message when failing to reach important peers

---

bin/wasm-node/rust/src/sync_service.rs

Right now we try to find if the parachain occupies a core at block 0 of the relay chain, and print a warning when it obviously fails.
This removes the warning.

Remove warning in para-syncing when relay still warp syncing

---

src/chain/blocks_tree/best_block.rs
src/chain/blocks_tree/finality.rs
src/chain/blocks_tree/verify.rs

Clean-ups, but most importantly, fixes the code when Aura is used.
See commits one by one.

Various clean ups to the best block determination mechanism

---

src/chain/blocks_tree/finality.rs

Bug introduced in https://github.com/paritytech/smoldot/pull/900 (that wasn't caught during the code review :smirk: )

Fix issue in best block update after finalization

---

bin/wasm-node/rust/src/json_rpc_service.rs
bin/wasm-node/rust/src/sync_service.rs

(Almost) correctly implement system_peers

---

bin/wasm-node/rust/src/json_rpc_service.rs
src/json_rpc/methods.rs

cc https://github.com/paritytech/smoldot/issues/595

Move header_conv function to src

---

Cargo.lock
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

To merge after https://github.com/paritytech/smoldot/pull/923
https://github.com/paritytech/smoldot/pull/923 is important enough for a new release.

Publish v0.2.5

---

bin/wasm-node/rust/src/json_rpc_service.rs

As per comment, it is possible that paraheaders are in a format that can't be decoded.

Don't unwrap when decoding header in chain_getHeader

---

bin/wasm-node/rust/src/lib.rs
bin/wasm-node/rust/src/runtime_service.rs

Changes extracted from https://github.com/paritytech/smoldot/pull/845

Add RuntimeCallLock::storage_entry and block_scale_encoded_header

---

src/chain_spec/structs.rs

https://github.com/paritytech/substrate/pull/8898
cc https://github.com/paritytech/smoldot/issues/858

Add dummy `codeSubstitutes` to chain spec

---

Cargo.lock
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

To merge after https://github.com/paritytech/smoldot/pull/845

Publish v0.2.9

---

src/executor/runtime_host.rs
src/header.rs
src/header/aura.rs
src/header/babe.rs
src/header/grandpa.rs
src/libp2p/connection/multistream_select.rs
src/transactions/validate.rs
src/trie/trie_structure.rs

Shorten usage of the either crate

---

src/chain/fork_tree.rs

Fix bad links after pruning uncles in fork_tree

---

bin/full-node/src/network_service.rs
bin/wasm-node/rust/src/network_service.rs
src/libp2p.rs
src/network/protocol/block_announces.rs
src/network/protocol/grandpa.rs
src/network/service.rs

cc https://github.com/paritytech/smoldot/issues/980
Doesn't fix the actual problem, but at least we won't panic.

Don't unwrap in network service on decode error

---

Cargo.lock
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

Integrates https://github.com/paritytech/smoldot/pull/994

Publish v0.3.0

---

src/chain/blocks_tree/finality.rs
src/sync/all_forks.rs

Right now a lot of warnings are printed about invalid Grandpa commit messages.
The reason for this warning is that:
- Node A sends us a Grandpa commit.
- We successfully verify the commit, advance the finalized block, and discard the finalized block and below.
- Node B sends us the same Grandpa commit.
- Because the target of the commit is no longer in the tree of non-finalized blocks, the commit is considered invalid with a `FinalityVerifyError::UnknownTargetBlock` error.
This PR changes the code to:
- No longer return `UnknownTargetBlock` when the target block is inferior or equal to the block already finalized.
- No longer return an error from the `grandpa_commit_message` function when the target block is inferior or equal to the block already finalized, unless there's a mismatch …

Fix errors about invalid commit messages

---

Cargo.lock
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

Makes Westend sync again: https://github.com/paritytech/smoldot/pull/1011

Publish v0.3.1

---

bin/wasm-node/rust/src/json_rpc_service.rs
bin/wasm-node/rust/src/lib.rs

Don't hold the chain spec in the JSON-RPC service

---

bin/wasm-node/rust/src/json_rpc_service.rs
bin/wasm-node/rust/src/lib.rs

Rename json_rpc_service::start to JsonRpcService::new

---

src/executor/host.rs

Removed in https://github.com/paritytech/substrate/pull/7810. It took me ages to find that PR.

Remove the ext_misc_chain_id_version_1 host function

---

src/executor/host.rs

Reduce one indentation level in host.rs

---

bin/wasm-node/javascript/src/health.js
bin/wasm-node/javascript/src/index.d.ts
bin/wasm-node/javascript/src/index.js
bin/wasm-node/javascript/test/demo.js
bin/wasm-node/rust/src/json_rpc_service.rs

Close https://github.com/paritytech/smoldot/pull/1032

Add a health checker

---

bin/wasm-node/javascript/demo/demo.js

I've accidentally changed it to Polkadot in https://github.com/paritytech/smoldot/pull/985

Revert demo.js to Westend

---

src/network/service.rs

Decrease request timeouts

---

bin/wasm-node/javascript/src/health.js

Remove stray sentence from doc

Update health.js doc

---

Cargo.lock
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

To be merged after https://github.com/paritytech/smoldot/pull/1150

Publish v0.4.1

---

Cargo.lock
Cargo.toml
src/sync/optimistic.rs

cc https://github.com/paritytech/smoldot/issues/1061

Refactor API of optimistic sync

---

bin/full-node/src/sync_service.rs
bin/wasm-node/rust/src/sync_service.rs
src/sync/all.rs
src/sync/optimistic.rs

Fix https://github.com/paritytech/smoldot/issues/1061
The code is non-functional, but at least it compiles again.

Restore optimistic syncing in all.rs

---

src/libp2p/peers.rs

Prevent peers from opening more than one inbound notification substream at a time.

Prevent multiple inbound notification substreams per peer

---

src/network/service.rs

Instead of storing some kind of "action" enum in a variable, we store the event and clear the event afterwards.

Refactor strategy for handling futures cancellation in service.rs

---

src/sync/all.rs
src/sync/grandpa_warp_sync.rs

Fix https://github.com/paritytech/smoldot/issues/1241

Do not panic if storage queries fail during GP warp sync

---

bin/full-node/src/sync_service.rs
bin/wasm-node/rust/src/sync_service.rs
src/network/service.rs

Should be merged after https://github.com/paritytech/substrate/pull/9692

Backport changes to syncing

---

src/sync/grandpa_warp_sync.rs

Before this PR, if Grandpa warp syncing fails for all peers, then the syncing will simply stall and never un-stall until we connect to more peers.
It makes little to deliberately stall the syncing forever, so this PR changes this behavior to un-ban all peers and try again.

Try Grandpa warp sync again if all sources are banned

---

Cargo.lock
Cargo.toml

https://github.com/rust-lang/rust/issues/88581

Make master compile again

---

src/executor/host.rs

Fix https://github.com/paritytech/smoldot/issues/1091
Backports https://github.com/paritytech/substrate/pull/9391

Backport upgrade to libsecp256k1

---

src/chain_spec/structs.rs

cc https://github.com/paritytech/smoldot/issues/1110

Document code_subtitutes

---

.github/workflows/ci.yml
src/database/full_sqlite.rs
src/database/full_sqlite/open.rs

Make it run on 32bits platforms

---

bin/wasm-node/rust/src/sync_service.rs

Add parachains finality

---

bin/wasm-node/rust/src/runtime_service.rs
bin/wasm-node/rust/src/sync_service.rs
src/sync/download_tree.rs

cc https://github.com/paritytech/smoldot/issues/1377

Add RuntimeService::subscribe_all

---

src/keystore.rs
src/lib.rs

Add a keystore

---

Cargo.lock
bin/full-node/Cargo.toml
bin/full-node/src/cli.rs
bin/full-node/src/run.rs
bin/full-node/src/run/consensus_service.rs
bin/full-node/src/run/jaeger_service.rs
bin/full-node/src/run/network_service.rs
src/network/service.rs

Close https://github.com/paritytech/smoldot/pull/231
This time for good.

Add a jaeger service to the full node

---

bin/full-node/src/run/network_service.rs

Equivalent to https://github.com/paritytech/smoldot/pull/1614 but for the full node

Clamp number of connection simultaneous attempts in full node

---

src/transactions/light_pool.rs

Fix https://github.com/paritytech/smoldot/issues/1604
The function didn't consider the possibility that `new_best_block_hash` could be equal to the root of the tree.

Fix panic in LightPool::set_best_block

---

bin/wasm-node/rust/src/network_service.rs

cc https://github.com/paritytech/smoldot/issues/1531

Pass true for is_unreachable in case of bad address

---

Cargo.lock
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

To merge after https://github.com/paritytech/smoldot/pull/1634

Publish v0.5.2

---

bin/wasm-node/rust/src/runtime_service.rs

Fixes a legitimate problem, and also bypasses https://github.com/paritytech/smoldot/issues/1644 at the same time.

Do not panic in runtime service if bad block

---

bin/wasm-node/rust/src/sync_service/parachain.rs
src/chain/async_tree.rs

Fix https://github.com/paritytech/smoldot/issues/1642

Clean up parachain syncing code

---

bin/wasm-node/rust/src/ffi.rs
bin/wasm-node/rust/src/json_rpc_service.rs
bin/wasm-node/rust/src/lib.rs
bin/wasm-node/rust/src/network_service.rs
bin/wasm-node/rust/src/runtime_service.rs
bin/wasm-node/rust/src/sync_service.rs
bin/wasm-node/rust/src/sync_service/parachain.rs
bin/wasm-node/rust/src/sync_service/standalone.rs
bin/wasm-node/rust/src/transactions_service.rs

This is a step towards https://github.com/paritytech/smoldot/issues/1453

Parametrize the Wasm node over a TPlat abstraction

---

bin/wasm-node/rust/src/ffi.rs
bin/wasm-node/rust/src/lib.rs

cc https://github.com/paritytech/smoldot/issues/1453

Move spawning background tasks to ffi module

---

bin/wasm-node/rust/src/json_rpc_service.rs

Fix bug introduced in https://github.com/paritytech/smoldot/pull/1688

Fix Instant subtraction in wrong order

---

bin/wasm-node/rust/src/ffi.rs
bin/wasm-node/rust/src/json_rpc_service.rs
bin/wasm-node/rust/src/lib.rs

cc https://github.com/paritytech/smoldot/issues/1453

Move sending out the JSON-RPC responses to the ffi layer

---

bin/wasm-node/rust/src/ffi.rs
bin/wasm-node/rust/src/json_rpc_service.rs
bin/wasm-node/rust/src/lib.rs

cc https://github.com/paritytech/smoldot/issues/1453

Finish making emit_json_rpc_response private

---

bin/wasm-node/rust/src/ffi.rs
bin/wasm-node/rust/src/lib.rs

cc https://github.com/paritytech/smoldot/issues/1453

Move logger and panic hook initialization to ffi module

---

Cargo.lock
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

To merge after https://github.com/paritytech/smoldot/pull/1710

Publish v0.5.5

---

.github/workflows/ci-post-workflow.yml
.github/workflows/ci.yml
bin/light-base/src/lib.rs

Try running twiggy diff on CI

---

.github/workflows/cache-fill.yml

Close https://github.com/paritytech/smoldot/issues/1731

Add more cache filling GitHub actions

---

bin/light-base/src/lib.rs
bin/light-base/src/sync_service.rs
bin/light-base/src/sync_service/parachain.rs
bin/light-base/src/sync_service/standalone.rs
bin/wasm-node/javascript/src/bindings-smoldot-light.js
bin/wasm-node/javascript/src/index.d.ts
bin/wasm-node/javascript/src/index.js
bin/wasm-node/javascript/src/worker.js
bin/wasm-node/rust/src/bindings.rs
bin/wasm-node/rust/src/lib.rs

Fix https://github.com/paritytech/smoldot/issues/1565
This PR is complicated due to the asynchronous nature of the sync service.

Restore database in Wasm node

---

bin/light-base/src/runtime_service.rs
bin/light-base/src/sync_service.rs
bin/light-base/src/sync_service/parachain.rs
bin/light-base/src/sync_service/standalone.rs
bin/light-base/src/transactions_service.rs

cc https://github.com/paritytech/smoldot/issues/1738

Provide the finalized block runtime in SubscribeAll

---

bin/light-base/src/runtime_service.rs

Close https://github.com/paritytech/smoldot/issues/1644

Always start runtime_service in "unknown runtime" mode

---

bin/wasm-node/javascript/demo/demo.js
src/network/service.rs

Fix https://github.com/paritytech/smoldot/issues/1777

Fix debug assertion failures in networking when genesis root mismatch

---

bin/light-base/src/runtime_service.rs

Follow up from https://github.com/paritytech/smoldot/pull/1754

Remove the runtime service Arc replacement system

---

Cargo.lock
Cargo.toml
bin/full-node/Cargo.toml
bin/light-base/Cargo.toml
bin/wasm-node/rust/Cargo.toml

Revert to futures 0.3.17

---

bin/full-node/src/run/consensus_service.rs
bin/light-base/src/sync_service/parachain.rs
bin/light-base/src/sync_service/standalone.rs
src/json_rpc/websocket_server.rs
src/sync/all.rs
src/sync/all_forks.rs
src/sync/all_forks/pending_blocks.rs
src/sync/all_forks/sources.rs
src/sync/optimistic.rs
src/sync/warp_sync.rs

Replace many "user_data" functions with the Index trait

---

bin/light-base/Cargo.toml

https://rustsec.org/advisories/RUSTSEC-2021-0130

Force lru v0.7.1

---

bin/light-base/src/json_rpc_service.rs
src/json_rpc/methods.rs

Update format of chain_getBlock

---

Cargo.lock
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

One of objectives is to publish https://github.com/paritytech/smoldot/pull/1869 as soon as possible
cc https://github.com/paritytech/smoldot/issues/1844

Publish v0.5.13

---

bin/wasm-node/javascript/src/client.ts
bin/wasm-node/javascript/src/worker/worker.ts

I've always been scared of `switch` because of the `break` that is easy to miss, but with TS it is now safe.

Use switch for messages instead of if

---

bin/light-base/src/runtime_service.rs

Follow up to https://github.com/paritytech/smoldot/pull/1875

Don't panic in unpin_block if sender is closed

---

bin/wasm-node/javascript/src/client.ts

Remove this weird `__internal_smoldot_id` function from the `Chain` interface.
Considering that I haven't published a new version since `__internal_smoldot_id` has been added, this PR doesn't need a major version bump.

Use a WeakMap for chains tracking

---

bin/wasm-node/javascript/src/client.ts

Fix https://github.com/paritytech/smoldot/issues/1858

Update links to JSON-RPC APIs

---

bin/light-base/src/runtime_service.rs

As a follow-up to the previous PRs, we can now simplify the internals of `RuntimeCallLock`

Simplify RuntimeCallLock

---

bin/light-base/src/json_rpc_service.rs
bin/light-base/src/runtime_service.rs
bin/light-base/src/sync_service/parachain.rs
bin/light-base/src/transactions_service.rs

Next step in the general runtime-service/json-rpc-service refactoring.

Add RuntimeLock::specification and use it

---

bin/light-base/src/json_rpc_service.rs
src/json_rpc/methods.rs

Updates for https://github.com/paritytech/json-rpc-interface-spec/pull/7

Update chainHead_call to accept one single callParameters

---

bin/light-base/src/json_rpc_service.rs

Extract run() function as standalone in JSON-RPC service

---

bin/wasm-node/javascript/src/worker/connection.ts
src/libp2p/multiaddr.rs

cc https://github.com/paritytech/smoldot/issues/1940
Now accept dialing `/tls/ws` addresses.

Support /tls/ws multiaddresses in browser node

---

bin/light-base/src/json_rpc_service/state_chain.rs
src/executor.rs
src/json_rpc/methods.rs

cc https://github.com/paritytech/smoldot/issues/1967

Added state_version field to CoreVersion

---

src/executor/host.rs

cc https://github.com/paritytech/smoldot/issues/1967

Implement stubs for new host functions for new state version

---

bin/wasm-node/rust/src/timers.rs

Found out this bug when investigating https://github.com/paritytech/smoldot/pull/1976#issuecomment-1026675552

Bugfix in wasm-node timers

---

src/network/service.rs

When a notifications substream other than the block announces get shut down by the remote, immediately try to reopen it instead of just doing nothing.
This might help with https://github.com/paritytech/smoldot/issues/1966
cc @librelois

Try reopen substreams after they're closed

---

Cargo.lock
bin/full-node/Cargo.toml
bin/full-node/src/cli.rs
bin/full-node/src/main.rs

Close https://github.com/paritytech/smoldot/issues/1828

Transition from structopt to clap v3

---

Cargo.lock
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

To bring in https://github.com/paritytech/smoldot/pull/2012 and https://github.com/paritytech/smoldot/pull/2001

Publish v0.5.20

---

Cargo.lock
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

Bringing in https://github.com/paritytech/smoldot/pull/2019

Publish v0.5.21

---

src/author/build.rs
src/author/runtime.rs
src/author/runtime/tests.rs
src/verify.rs
src/verify/inherents.rs

Step towards https://github.com/paritytech/smoldot/issues/227

Extract inherents to separate module

---

bin/light-base/src/json_rpc_service.rs
bin/light-base/src/json_rpc_service/chain_head.rs
bin/light-base/src/json_rpc_service/getters.rs
bin/light-base/src/json_rpc_service/state_chain.rs
bin/light-base/src/json_rpc_service/transactions.rs
src/json_rpc/methods.rs
src/json_rpc/parse.rs

Fix https://github.com/paritytech/smoldot/issues/2074
Uses `Cow<'a, str>` everywhere instead of `&'a str`.

Work around serde_json deserialization issue

---

Cargo.lock
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

Main fix is https://github.com/paritytech/smoldot/pull/2075
Other notable change is https://github.com/paritytech/smoldot/pull/2067

Publish v0.6.3

---

Cargo.lock
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

For https://github.com/paritytech/smoldot/pull/2089

Publish v0.6.4

---

bin/full-node/src/run.rs
bin/full-node/src/run/consensus_service.rs
src/author/runtime/tests.rs
src/chain/async_tree.rs
src/chain_spec/structs.rs
src/database/full_sqlite/open.rs
src/executor/runtime_host.rs
src/executor/vm/interpreter.rs
src/executor/vm/jit.rs
src/identity/seed_phrase.rs
src/informant.rs
src/libp2p/multiaddr.rs
src/libp2p/multihash.rs
src/network/service.rs
src/sync/optimistic.rs
src/trie/calculate_root.rs
src/verify/header_body.rs

run `cargo clippy --fix`

---

src/chain/blocks_tree/finality.rs
src/chain/chain_information/aura_config.rs
src/chain/chain_information/babe_genesis_config.rs
src/chain/chain_information/grandpa_genesis_config.rs
src/executor.rs
src/executor/allocator.rs
src/executor/host.rs
src/finality/grandpa/commit/decode.rs
src/finality/grandpa/warp_sync.rs
src/finality/justification/decode.rs
src/json_rpc/requests_subscriptions.rs
src/libp2p/connection/multistream_select.rs
src/libp2p/connection/yamux.rs
src/libp2p/peers.rs
src/network/protocol/block_request.rs
src/network/service.rs
src/sync/all_forks/pending_blocks.rs

Refs #1623 
Context: fixed some clippy warnings while reading the code.

fix some clippy warnings

---

bin/light-base/src/lib.rs

Mention database in the initialization log message

---

src/chain/blocks_tree/verify.rs
src/verify.rs
src/verify/header_body.rs
src/verify/inherents.rs

Close https://github.com/paritytech/smoldot/issues/227
~~Opening as draft because not fully implemented.~~

Implement calling check_inherents

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
bin/light-base/src/transactions_service.rs
bin/wasm-node/javascript/prepare.js
src/header.rs

Updates all the hardcoded Rust versions to 1.59

Update to Rust 1.59

---

bin/light-base/src/sync_service/standalone.rs

One of the main consequence of issues right now is that the GrandPa warp syncing never finishes, for example because we have no connectivity to any peer or because we fail to decode some data structure or something.
This PR prints a warning every 15 seconds in order to remind users of the fact that smoldot is still trying to do something.

Print warning when GrandPa warp syncing takes a long time

---

src/sync/all.rs
src/sync/all_forks.rs

cc https://github.com/paritytech/smoldot/issues/1572

Give more access to user datas of blocks in all_forks.rs

---

.github/workflows/ci.yml

It uses https://github.com/actions-rs/install action.
Closes #255

add cargo-spellcheck GH action

---

src/libp2p/collection.rs
src/libp2p/peers.rs
src/network/service.rs

I have bundled 5 networking bug fixes in 5 commits in this single PR.
These bugfixes have made me realize that some implementation details need to be changed quite a bit to adjust to the new design, which I'll do in further PRs.

Fix a couple of panics in new networking

---

src/libp2p/collection.rs

I mostly removed `outgoing_requests` and renamed `outgoing_requests_by_connection` to `outgoing_requests`.
The rest of the changes are documentation and removing the TODOs.

Clean up collection.rs data structures

---

src/libp2p/collection.rs
src/libp2p/peers.rs

Replaces a `BTreeMap` with a `BTreeSet`. The value that was in the `BTreeMap` is now queried from the underlying layer.
I've also added a TODO because this change made me realize a problem with the code that would be off-topic for this PR.

Don't store in peers.rs whether connections are established

---

bin/full-node/src/run/consensus_service.rs
src/executor/storage_diff.rs

Removes a few calls to `to_vec()` by passing a different trait implementation to `range()`.

Optimize range() usage in storage_diff and consensus service

---

README.md

This small text was written when the demo only connected to Westend.

Update README content regarding Wasm demo

---

src/sync/optimistic.rs

Fixes the first panic of https://github.com/paritytech/smoldot/issues/2362
When we disconnect from a so-called "source" (i.e. a peer), `remove_source` returns the list of all on-going requests so that the API user knows that these requests no longer exist in the syncing state machine.
However, before this PR `remove_source` didn't return the requests whose outcome no longer interests us. This leads to a state mismatch.
Later, when the request gets answered, this triggers a panic because the state machine doesn't expect the request to be there.
This was marked by a TODO, and this PR fixes this TODO.

Fix OptimisticSync::remove_source not removing obsolete requests

---

bin/full-node/src/run/consensus_service.rs
bin/light-base/src/sync_service/standalone.rs
src/sync/all.rs

The word "disjoint" is hard to understand.

Rename "Disjoint" to "StoredForLater"

---

bin/wasm-node/CHANGELOG.md

Add missing CHANGELOG entry for #2425

---

bin/wasm-node/javascript/demo/demo.js

This PR refactors the demo so that we don't have to keep adding `} else if {` statements for every chain.

Refactor the demo

---

bin/light-base/src/transactions_service.rs
src/transactions/light_pool.rs
src/transactions/light_pool/tests.rs

Use a proper struct for transactions removed from light pool

---

bin/full-node/src/run/network_service.rs
bin/fuzz/fuzz_targets/protocol-block-announces-handshake-decode.rs
bin/fuzz/fuzz_targets/protocol-blocks-request-decode.rs
bin/light-base/src/network_service.rs
src/network/protocol/block_announces.rs
src/network/protocol/block_request.rs
src/network/service.rs

First bullet point of https://github.com/paritytech/smoldot/issues/2478

Provide a block number size parameter to the networking service

---

bin/light-base/src/lib.rs
bin/light-base/src/sync_service.rs
bin/light-base/src/sync_service/parachain.rs
src/sync/para.rs

cc https://github.com/paritytech/smoldot/issues/2478
I forgot this point in https://github.com/paritytech/smoldot/issues/2478, but here is the PR.

Use block_number_bytes when parsing parachain data

---

src/network/service.rs

cc https://github.com/paritytech/smoldot/issues/2478#issuecomment-1185276815
Fixes a remaining hardcoded block number.

Fix block number bytes when decoding warp sync responses

---

.config/smoldot.dic
README.md

cc https://github.com/paritytech/smoldot/issues/2427

Mention Deno in the README

---

bin/wasm-node/javascript/src/client.ts

Updates a comment after https://github.com/paritytech/smoldot/pull/2502

Update outdated docs on large JSON-RPC request

---

bin/full-node/src/run/network_service.rs
bin/light-base/src/network_service.rs
src/network/service.rs

This function used to accept a list as parameter because it was initially accepting `&self` and locking an internal mutex.
Now that this is gone, there's no reason to accept a list anymore.

ChainNetwork::discover now takes a single element

---

bin/full-node/src/run.rs
bin/full-node/src/run/consensus_service.rs

Close https://github.com/paritytech/smoldot/issues/1866

Print a warning in the full node when syncing Kusama

---

src/libp2p/peers.rs

At the moment, every time a ping failure happens, smoldot then panics because of a state mismatch. This is because the outside isn't informed of the fact that a connection is shutting down.
This PR fixes this.

Properly report StartShutdown event on ping failure

---

src/sync/warp_sync.rs

Rely on names rather than tuple indices.

Minor clean-up in warp_sync.rs by using a struct instead of tuple

---

src/executor/host/runtime_version.rs

The code that finds the runtime version and APIs in the Wasm module currently traverses the module twice.
This PR refactors the code so that we only traverse it once.
Tested, and parsing succeeds.

Only traverse Wasm module once to find custom sections

---

src/chain/blocks_tree/verify.rs

Simplifies `verify.rs` a bit by removing a struct specific to blocks verification.

Replace VerifyConsensusSpecific with Option<BlockConsensus>

---

bin/light-base/src/runtime_service.rs

cc https://github.com/paritytech/smoldot/issues/2617

Add debug assertions in runtime_service pinned blocks

---

Cargo.lock
bin/wasm-node/CHANGELOG.md
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

Close https://github.com/paritytech/smoldot/issues/2689

Publish v0.6.31

---

src/libp2p/websocket.rs

Handles the situation where the API user tries to send data on a socket after having closed its writing side.
Unfortunately, the `Read`/`Write`/`AsyncRead`/`AsyncWrite` traits are completely unspecified regarding a lot of aspects, and one of these aspects is the situation in question here.
Considering that it is an incorrect API usage, this path is never supposed to be reached anyway.

Handle websocket client API usage error

---

src/sync/optimistic/verification_queue.rs

cc https://github.com/paritytech/smoldot/issues/2726
Didn't manage to reproduce the issue so far, but at least these debug assertions should help diagnosing the next time it happens.

Add debug assertions to the verification queue

---

.github/workflows/ci.yml
Cargo.toml
src/executor/vm/jit.rs

Replace parking_lot with std::sync, and improve CI

---

bin/light-base/src/runtime_service.rs

Minor refactoring to help with clarity of the code.

Use a struct for runtime service pinned blocks

---

src/libp2p/collection/multi_stream.rs
src/libp2p/connection/handshake.rs
src/libp2p/connection/noise.rs

Some preliminary work for WebRTC support.

Allow providing a prologue for Noise handshakes

---

src/network/protocol/block_request.rs

Don't send justifications field if no justification

---

src/libp2p/collection/multi_stream.rs

Right now, if an extra substream is opened during the handshake, we simply ignore it. The substream will plain not work.
In principle, no extra substream should be opened during the handshake, provided we are the client. However, due to bugs and implementation difficulties, it is actually not impossible that this happens in reality, in which case simply ignoring the substream is the worst thing we can do.

Don't ignore extra substreams opened during handshake

---

bin/wasm-node/javascript/src/index-browser.ts

Update to match https://github.com/libp2p/rust-libp2p/pull/2622#pullrequestreview-1123477517

Update WebRTC handshake channel number

---

src/network/protocol/block_request.rs

Check bitfield validity in block requests

---

src/network/protocol/state_request.rs
src/network/service.rs

Instead of decoding the response into owned structs, we do like other protocols are return slices.
As for `service.rs`, we now return an `EncodedStateResponse` object representing a valid but not-decoded state response, which can be decoded by the user. Again, this mimics other protocols.

Make state request protocol functions more zero cost

---

src/libp2p/peers.rs

This merges two nearly-identical blocks of code into one.

Handle StartShutdown and PingOutFailed together in peers.rs

---

bin/full-node/src/run.rs

Instead of randomly generating a new networking key every time, this PR stores this networking key on disk and reloads it if it exists.

Full node: store the libp2p key on disk

---

bin/full-node/src/run/network_service.rs
src/network/protocol/block_request.rs

After this PR, Substrate can now sync from smoldot.

Fix responding to block requests mixing ascending and descending

---

bin/light-base/src/lib.rs

Improve the bad blocks warning

---

.github/workflows/deploy.yml
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/javascript/src/client.ts

Add a new CI stages that uploads the documentation of everything to `gh-pages`.
cc https://github.com/paritytech/smoldot/issues/2092

Add a CI stage that uploads the automatically generated doc to gh-pages

---

src/libp2p/peers.rs

Fixes a TODO.
If a peer opens the same notifications substream multiple times, we refuse all substreams but the first. This is correct.
However when we refuse the substream we do so completely silently. Nothing is logged, and thus it makes it hard to figure out whether this happens.
This PR reports this situation as an event so that the upper layers can output it in a log for example (that's how `InboundError` events are handled at the moment).

Report duplicate notification substreams as InboundError events

---

src/executor/host.rs

I am just playing with the executor and some Debug helps a bit.

impl Debug

---

src/libp2p/peers.rs
src/network/service.rs

Close https://github.com/paritytech/smoldot/issues/2799
Before this PR, calling `set_peer_notifications_out_desired` and marking a peer+substream as "not desired" instantly closes any existing substream or substream in progress without generating any event.
After this PR, the function just flags the substream as "not desired", and the user has to additionally call `fulfilled_undesired_outbound_substreams` to determine the list of substreams that are open but not desired, then `close_out_notification` to close the substream.
This mimics the existing API with `unfulfilled_desired_outbound_substream` and `open_out_notification`.
I don't think (but I'm not sure) that this PR actually changes the behavior anywhere, because right now we mark peers as undesired only as a consequence of a …

Add fulfilled_undesired_outbound_substreams and close_out_notification

---

src/executor/host.rs
src/executor/runtime_host.rs

Closes https://github.com/paritytech/smoldot/issues/2893

support nested transactions

---

src/executor/storage_diff.rs

expose storage diff

---

Cargo.lock
bin/wasm-node/CHANGELOG.md
bin/wasm-node/javascript/package-lock.json
bin/wasm-node/javascript/package.json
bin/wasm-node/rust/Cargo.toml

To merge after https://github.com/paritytech/smoldot/pull/2939

Publish v0.7.4

---

src/executor/host.rs
src/json_rpc/methods.rs

improve verification logic

---

bin/light-base/src/sync_service/standalone.rs
src/sync/all.rs
src/sync/warp_sync.rs

Fix https://github.com/paritytech/smoldot/issues/2222

Indicate the warp sync status in the informant

---

bin/wasm-node/javascript/package-lock.json

I don't know why dependabot isn't handling that, but I've just run `npm update` and noticed a huge diff, so here it is.

Run npm update

---

src/trie/proof_decode.rs

Add iteration functions to DecodedTrieProof

---

src/trie/proof_node_codec.rs

Add proof_node_codec::encode_to_vec

---

src/trie/proof_decode.rs

`iter_ordered` no longer returns a `TrieNodeInfo`, as `TrieNodeInfo` can represent a node that doesn't actually exist in the trie, but a `ProofEntry`.
This is important for https://github.com/paritytech/smoldot/issues/2973 so that you can copy a decoded proof into a `ProofBuilder`.

Return the node value from DecodedTrieProof::iter_ordered

---

src/trie/proof_encode.rs

Check the partial key in ProofBuilder::set_node_value

---

src/trie/proof_node_codec.rs

This is important because `proof_node_codec::encode` indirectly requires providing a `PartialKey`.
Since right now it's possible to build a `PartialKey` (only obtain one when decoding), the possibility to encode trie nodes is limited.

Make it possible to build a proof_node_codec::PartialKey

---

Cargo.lock
Cargo.toml
bin/full-node/Cargo.toml
bin/light-base/Cargo.toml
bin/wasm-node/rust/Cargo.toml

Updated versions will be shortly available on crates.io.

Bump the library versions
